/**
 * Auto-generated GraphQL SDK
 * @generated by @constructive-io/graphql-codegen
 *
 * Tables: CheckConstraint, User, Database, AppLimit, AppAdminGrant, AppOwnerGrant, AppGrant, AppStep, AppAchievement, AppLevel, OrgPermissionDefault, OrgLimit, OrgMembership, OrgMember, OrgAdminGrant, OrgOwnerGrant, OrgGrant, Email, PhoneNumber, CryptoAddress, UserProfile, UserSetting, OrganizationSetting, Invite, ClaimedInvite, OrgInvite, OrgClaimedInvite, AuditLog, Schema, Table, Field, DenormalizedTableField, FieldModule, MembershipsModule, ForeignKeyConstraint, FullTextSearch, Index, LimitFunction, Policy, PrimaryKeyConstraint, TableGrant, Trigger, UniqueConstraint, ConnectedAccountsModule, CryptoAddressesModule, CryptoAuthModule, EmailsModule, EncryptedSecretsModule, InvitesModule, LevelsModule, LimitsModule, MembershipTypesModule, PermissionsModule, PhoneNumbersModule, ProfilesModule, SecretsModule, TokensModule, UsersModule, HierarchyModule, UserProfilesModule, UserSettingsModule, OrganizationSettingsModule, SchemaGrant, ApiSchema, ApiExtension, ApiModule, Domain, SiteMetadatum, SiteModule, SiteTheme, RlsModule, UserAuthModule, UuidModule, DatabaseExtension, Procedure, TriggerFunction, Api, Site, App, DefaultIdsModule, DatabaseProvisionModule, Extension, Object, Commit, Ref, Store, RoleType, AppMembershipDefault, AppMembership, MembershipType, OrgMembershipDefault, AppPermissionDefault, AppPermission, OrgPermission, AppLimitDefault, OrgLimitDefault, AppLevelRequirement
 *
 * Usage:
 *
 * 1. Configure the client:
 * ```ts
 * import { configure } from './generated';
 *
 * configure({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer <token>' },
 * });
 * ```
 *
 * 2. Use the hooks:
 * ```tsx
 * import { useCarsQuery, useCreateCarMutation } from './generated';
 *
 * function MyComponent() {
 *   const { data, isLoading } = useCarsQuery({ first: 10 });
 *   const { mutate } = useCreateCarMutation();
 *   // ...
 * }
 * ```
 */

// Client configuration
export * from './client';

// Entity and filter types
export * from './types';

// Schema types (input, payload, enum types)
export * from './schema-types';

// Query hooks
export * from './queries';

// Mutation hooks
export * from './mutations';
