/**
 * List query hook for AppLimitDefault
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppLimitDefault,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppLimitDefault };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appLimitDefaultsQueryDocument = `
query AppLimitDefaultsQuery($first: Int, $offset: Int, $filter: AppLimitDefaultFilter, $orderBy: [AppLimitDefaultsOrderBy!]) {
  appLimitDefaults(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      name
      max
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppLimitDefaultFilter {
  id?: UUIDFilter;
  name?: StringFilter;
  max?: IntFilter;
  /** Logical AND */
  and?: AppLimitDefaultFilter[];
  /** Logical OR */
  or?: AppLimitDefaultFilter[];
  /** Logical NOT */
  not?: AppLimitDefaultFilter;
}

type AppLimitDefaultsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'MAX_ASC'
  | 'MAX_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppLimitDefaultsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppLimitDefaultFilter;
  orderBy?: AppLimitDefaultsOrderBy[];
}

export interface AppLimitDefaultsQueryResult {
  appLimitDefaults: {
    totalCount: number;
    nodes: AppLimitDefault[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appLimitDefaultsQueryKey = (
  variables?: AppLimitDefaultsQueryVariables
) => ['applimitdefault', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppLimitDefault list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitDefaultsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppLimitDefaultsQuery(
  variables?: AppLimitDefaultsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppLimitDefaultsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appLimitDefaultsQueryKey(variables),
    queryFn: () =>
      execute<AppLimitDefaultsQueryResult, AppLimitDefaultsQueryVariables>(
        appLimitDefaultsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppLimitDefault list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppLimitDefaultsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appLimitDefaultsQueryKey(variables),
 *   queryFn: () => fetchAppLimitDefaultsQuery(variables),
 * });
 * ```
 */
export async function fetchAppLimitDefaultsQuery(
  variables?: AppLimitDefaultsQueryVariables,
  options?: ExecuteOptions
): Promise<AppLimitDefaultsQueryResult> {
  return execute<AppLimitDefaultsQueryResult, AppLimitDefaultsQueryVariables>(
    appLimitDefaultsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppLimitDefault list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLimitDefaultsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppLimitDefaultsQuery(
  queryClient: QueryClient,
  variables?: AppLimitDefaultsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appLimitDefaultsQueryKey(variables),
    queryFn: () =>
      execute<AppLimitDefaultsQueryResult, AppLimitDefaultsQueryVariables>(
        appLimitDefaultsQueryDocument,
        variables,
        options
      ),
  });
}
