/**
 * Custom query hook for appLevelRequirementByNameAndLevel
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type AppLevelRequirement } from '../types';

/** GraphQL query document */
export const appLevelRequirementByNameAndLevelQueryDocument = `
query AppLevelRequirementByNameAndLevelQuery($name: String!, $level: String!) {
  appLevelRequirementByNameAndLevel(name: $name, level: $level) {
    id
    name
    level
    description
    requiredCount
    priority
    createdAt
    updatedAt
  }
}
`;

export interface AppLevelRequirementByNameAndLevelQueryVariables {
  name: string;
  level: string;
}

export interface AppLevelRequirementByNameAndLevelQueryResult {
  appLevelRequirementByNameAndLevel: AppLevelRequirement;
}

/** Query key factory for caching */
export const appLevelRequirementByNameAndLevelQueryKey = (
  variables?: AppLevelRequirementByNameAndLevelQueryVariables
) => ['appLevelRequirementByNameAndLevel', variables] as const;

/**
 * Query hook for appLevelRequirementByNameAndLevel
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLevelRequirementByNameAndLevelQuery({ name, level });
 *
 * if (data?.appLevelRequirementByNameAndLevel) {
 *   console.log(data.appLevelRequirementByNameAndLevel);
 * }
 * ```
 */
export function useAppLevelRequirementByNameAndLevelQuery(
  variables: AppLevelRequirementByNameAndLevelQueryVariables,
  options?: Omit<
    UseQueryOptions<AppLevelRequirementByNameAndLevelQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appLevelRequirementByNameAndLevelQueryKey(variables),
    queryFn: () =>
      execute<
        AppLevelRequirementByNameAndLevelQueryResult,
        AppLevelRequirementByNameAndLevelQueryVariables
      >(appLevelRequirementByNameAndLevelQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch appLevelRequirementByNameAndLevel without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppLevelRequirementByNameAndLevelQuery({ name, level });
 * ```
 */
export async function fetchAppLevelRequirementByNameAndLevelQuery(
  variables: AppLevelRequirementByNameAndLevelQueryVariables,
  options?: ExecuteOptions
): Promise<AppLevelRequirementByNameAndLevelQueryResult> {
  return execute<
    AppLevelRequirementByNameAndLevelQueryResult,
    AppLevelRequirementByNameAndLevelQueryVariables
  >(appLevelRequirementByNameAndLevelQueryDocument, variables, options);
}

/**
 * Prefetch appLevelRequirementByNameAndLevel for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLevelRequirementByNameAndLevelQuery(queryClient, { name, level });
 * ```
 */
export async function prefetchAppLevelRequirementByNameAndLevelQuery(
  queryClient: QueryClient,
  variables: AppLevelRequirementByNameAndLevelQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appLevelRequirementByNameAndLevelQueryKey(variables),
    queryFn: () =>
      execute<
        AppLevelRequirementByNameAndLevelQueryResult,
        AppLevelRequirementByNameAndLevelQueryVariables
      >(appLevelRequirementByNameAndLevelQueryDocument, variables, options),
  });
}
