/**
 * Custom query hook for apiSchemaByApiIdAndSchemaId
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ApiSchema } from '../types';

/** GraphQL query document */
export const apiSchemaByApiIdAndSchemaIdQueryDocument = `
query ApiSchemaByApiIdAndSchemaIdQuery($apiId: UUID!, $schemaId: UUID!) {
  apiSchemaByApiIdAndSchemaId(apiId: $apiId, schemaId: $schemaId) {
    id
    databaseId
    schemaId
    apiId
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    schema {
      id
      databaseId
      name
      schemaName
      label
      description
      smartTags
      category
      module
      scope
      tags
      isPublic
      createdAt
      updatedAt
    }
    api {
      id
      databaseId
      name
      dbname
      roleName
      anonRole
      isPublic
    }
  }
}
`;

export interface ApiSchemaByApiIdAndSchemaIdQueryVariables {
  apiId: string;
  schemaId: string;
}

export interface ApiSchemaByApiIdAndSchemaIdQueryResult {
  apiSchemaByApiIdAndSchemaId: ApiSchema;
}

/** Query key factory for caching */
export const apiSchemaByApiIdAndSchemaIdQueryKey = (
  variables?: ApiSchemaByApiIdAndSchemaIdQueryVariables
) => ['apiSchemaByApiIdAndSchemaId', variables] as const;

/**
 * Query hook for apiSchemaByApiIdAndSchemaId
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useApiSchemaByApiIdAndSchemaIdQuery({ apiId, schemaId });
 *
 * if (data?.apiSchemaByApiIdAndSchemaId) {
 *   console.log(data.apiSchemaByApiIdAndSchemaId);
 * }
 * ```
 */
export function useApiSchemaByApiIdAndSchemaIdQuery(
  variables: ApiSchemaByApiIdAndSchemaIdQueryVariables,
  options?: Omit<
    UseQueryOptions<ApiSchemaByApiIdAndSchemaIdQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: apiSchemaByApiIdAndSchemaIdQueryKey(variables),
    queryFn: () =>
      execute<
        ApiSchemaByApiIdAndSchemaIdQueryResult,
        ApiSchemaByApiIdAndSchemaIdQueryVariables
      >(apiSchemaByApiIdAndSchemaIdQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch apiSchemaByApiIdAndSchemaId without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchApiSchemaByApiIdAndSchemaIdQuery({ apiId, schemaId });
 * ```
 */
export async function fetchApiSchemaByApiIdAndSchemaIdQuery(
  variables: ApiSchemaByApiIdAndSchemaIdQueryVariables,
  options?: ExecuteOptions
): Promise<ApiSchemaByApiIdAndSchemaIdQueryResult> {
  return execute<
    ApiSchemaByApiIdAndSchemaIdQueryResult,
    ApiSchemaByApiIdAndSchemaIdQueryVariables
  >(apiSchemaByApiIdAndSchemaIdQueryDocument, variables, options);
}

/**
 * Prefetch apiSchemaByApiIdAndSchemaId for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchApiSchemaByApiIdAndSchemaIdQuery(queryClient, { apiId, schemaId });
 * ```
 */
export async function prefetchApiSchemaByApiIdAndSchemaIdQuery(
  queryClient: QueryClient,
  variables: ApiSchemaByApiIdAndSchemaIdQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: apiSchemaByApiIdAndSchemaIdQueryKey(variables),
    queryFn: () =>
      execute<
        ApiSchemaByApiIdAndSchemaIdQueryResult,
        ApiSchemaByApiIdAndSchemaIdQueryVariables
      >(apiSchemaByApiIdAndSchemaIdQueryDocument, variables, options),
  });
}
