/**
 * Single item query hook for ApiModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ApiModule } from '../types';

// Re-export entity type for convenience
export type { ApiModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const apiModuleQueryDocument = `
query ApiModuleQuery($id: UUID!) {
  apiModule(id: $id) {
    id
    databaseId
    apiId
    name
    data
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface ApiModuleQueryVariables {
  id: string;
}

export interface ApiModuleQueryResult {
  apiModule: ApiModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const apiModuleQueryKey = (id: string) =>
  ['apimodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single ApiModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useApiModuleQuery('value-here');
 *
 * if (data?.apiModule) {
 *   console.log(data.apiModule.id);
 * }
 * ```
 */
export function useApiModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<ApiModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: apiModuleQueryKey(id),
    queryFn: () =>
      execute<ApiModuleQueryResult, ApiModuleQueryVariables>(
        apiModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single ApiModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchApiModuleQuery('value-here');
 * ```
 */
export async function fetchApiModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<ApiModuleQueryResult> {
  return execute<ApiModuleQueryResult, ApiModuleQueryVariables>(
    apiModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single ApiModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchApiModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchApiModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: apiModuleQueryKey(id),
    queryFn: () =>
      execute<ApiModuleQueryResult, ApiModuleQueryVariables>(
        apiModuleQueryDocument,
        { id },
        options
      ),
  });
}
