/**
 * Single item query hook for AppGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type AppGrant } from '../types';

// Re-export entity type for convenience
export type { AppGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appGrantQueryDocument = `
query AppGrantQuery($id: UUID!) {
  appGrant(id: $id) {
    id
    permissions
    isGrant
    actorId
    grantorId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface AppGrantQueryVariables {
  id: string;
}

export interface AppGrantQueryResult {
  appGrant: AppGrant | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const appGrantQueryKey = (id: string) =>
  ['appgrant', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single AppGrant by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppGrantQuery('value-here');
 *
 * if (data?.appGrant) {
 *   console.log(data.appGrant.id);
 * }
 * ```
 */
export function useAppGrantQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<AppGrantQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appGrantQueryKey(id),
    queryFn: () =>
      execute<AppGrantQueryResult, AppGrantQueryVariables>(
        appGrantQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single AppGrant by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppGrantQuery('value-here');
 * ```
 */
export async function fetchAppGrantQuery(
  id: string,
  options?: ExecuteOptions
): Promise<AppGrantQueryResult> {
  return execute<AppGrantQueryResult, AppGrantQueryVariables>(
    appGrantQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single AppGrant for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppGrantQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchAppGrantQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appGrantQueryKey(id),
    queryFn: () =>
      execute<AppGrantQueryResult, AppGrantQueryVariables>(
        appGrantQueryDocument,
        { id },
        options
      ),
  });
}
