/**
 * Single item query hook for AppLimit
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type AppLimit } from '../types';

// Re-export entity type for convenience
export type { AppLimit };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appLimitQueryDocument = `
query AppLimitQuery($id: UUID!) {
  appLimit(id: $id) {
    id
    name
    actorId
    num
    max
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface AppLimitQueryVariables {
  id: string;
}

export interface AppLimitQueryResult {
  appLimit: AppLimit | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const appLimitQueryKey = (id: string) =>
  ['applimit', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single AppLimit by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitQuery('value-here');
 *
 * if (data?.appLimit) {
 *   console.log(data.appLimit.id);
 * }
 * ```
 */
export function useAppLimitQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<AppLimitQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appLimitQueryKey(id),
    queryFn: () =>
      execute<AppLimitQueryResult, AppLimitQueryVariables>(
        appLimitQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single AppLimit by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitQuery('value-here');
 * ```
 */
export async function fetchAppLimitQuery(
  id: string,
  options?: ExecuteOptions
): Promise<AppLimitQueryResult> {
  return execute<AppLimitQueryResult, AppLimitQueryVariables>(
    appLimitQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single AppLimit for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLimitQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchAppLimitQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appLimitQueryKey(id),
    queryFn: () =>
      execute<AppLimitQueryResult, AppLimitQueryVariables>(
        appLimitQueryDocument,
        { id },
        options
      ),
  });
}
