/**
 * Custom query hook for appPermissionsGetMaskByNames
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';

/** GraphQL query document */
export const appPermissionsGetMaskByNamesQueryDocument = `
query AppPermissionsGetMaskByNamesQuery($names: [String]) {
  appPermissionsGetMaskByNames(names: $names)
}
`;

export interface AppPermissionsGetMaskByNamesQueryVariables {
  names?: string[];
}

export interface AppPermissionsGetMaskByNamesQueryResult {
  appPermissionsGetMaskByNames: string;
}

/** Query key factory for caching */
export const appPermissionsGetMaskByNamesQueryKey = (
  variables?: AppPermissionsGetMaskByNamesQueryVariables
) => ['appPermissionsGetMaskByNames', variables] as const;

/**
 * Query hook for appPermissionsGetMaskByNames
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppPermissionsGetMaskByNamesQuery({ names });
 *
 * if (data?.appPermissionsGetMaskByNames) {
 *   console.log(data.appPermissionsGetMaskByNames);
 * }
 * ```
 */
export function useAppPermissionsGetMaskByNamesQuery(
  variables?: AppPermissionsGetMaskByNamesQueryVariables,
  options?: Omit<
    UseQueryOptions<AppPermissionsGetMaskByNamesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appPermissionsGetMaskByNamesQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionsGetMaskByNamesQueryResult,
        AppPermissionsGetMaskByNamesQueryVariables
      >(appPermissionsGetMaskByNamesQueryDocument, variables),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch appPermissionsGetMaskByNames without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppPermissionsGetMaskByNamesQuery({ names });
 * ```
 */
export async function fetchAppPermissionsGetMaskByNamesQuery(
  variables?: AppPermissionsGetMaskByNamesQueryVariables,
  options?: ExecuteOptions
): Promise<AppPermissionsGetMaskByNamesQueryResult> {
  return execute<
    AppPermissionsGetMaskByNamesQueryResult,
    AppPermissionsGetMaskByNamesQueryVariables
  >(appPermissionsGetMaskByNamesQueryDocument, variables, options);
}

/**
 * Prefetch appPermissionsGetMaskByNames for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppPermissionsGetMaskByNamesQuery(queryClient, { names });
 * ```
 */
export async function prefetchAppPermissionsGetMaskByNamesQuery(
  queryClient: QueryClient,
  variables?: AppPermissionsGetMaskByNamesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appPermissionsGetMaskByNamesQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionsGetMaskByNamesQueryResult,
        AppPermissionsGetMaskByNamesQueryVariables
      >(appPermissionsGetMaskByNamesQueryDocument, variables, options),
  });
}
