/**
 * List query hook for AppLevelRequirement
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppLevelRequirement,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppLevelRequirement };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appLevelRequirementsQueryDocument = `
query AppLevelRequirementsQuery($first: Int, $offset: Int, $filter: AppLevelRequirementFilter, $orderBy: [AppLevelRequirementsOrderBy!]) {
  appLevelRequirements(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      name
      level
      description
      requiredCount
      priority
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppLevelRequirementFilter {
  id?: UUIDFilter;
  name?: StringFilter;
  level?: StringFilter;
  description?: StringFilter;
  requiredCount?: IntFilter;
  priority?: IntFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppLevelRequirementFilter[];
  /** Logical OR */
  or?: AppLevelRequirementFilter[];
  /** Logical NOT */
  not?: AppLevelRequirementFilter;
}

type AppLevelRequirementsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'LEVEL_ASC'
  | 'LEVEL_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'REQUIRED_COUNT_ASC'
  | 'REQUIRED_COUNT_DESC'
  | 'PRIORITY_ASC'
  | 'PRIORITY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppLevelRequirementsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppLevelRequirementFilter;
  orderBy?: AppLevelRequirementsOrderBy[];
}

export interface AppLevelRequirementsQueryResult {
  appLevelRequirements: {
    totalCount: number;
    nodes: AppLevelRequirement[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appLevelRequirementsQueryKey = (
  variables?: AppLevelRequirementsQueryVariables
) => ['applevelrequirement', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppLevelRequirement list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLevelRequirementsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppLevelRequirementsQuery(
  variables?: AppLevelRequirementsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppLevelRequirementsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appLevelRequirementsQueryKey(variables),
    queryFn: () =>
      execute<
        AppLevelRequirementsQueryResult,
        AppLevelRequirementsQueryVariables
      >(appLevelRequirementsQueryDocument, variables),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppLevelRequirement list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppLevelRequirementsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appLevelRequirementsQueryKey(variables),
 *   queryFn: () => fetchAppLevelRequirementsQuery(variables),
 * });
 * ```
 */
export async function fetchAppLevelRequirementsQuery(
  variables?: AppLevelRequirementsQueryVariables,
  options?: ExecuteOptions
): Promise<AppLevelRequirementsQueryResult> {
  return execute<
    AppLevelRequirementsQueryResult,
    AppLevelRequirementsQueryVariables
  >(appLevelRequirementsQueryDocument, variables, options);
}

/**
 * Prefetch AppLevelRequirement list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLevelRequirementsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppLevelRequirementsQuery(
  queryClient: QueryClient,
  variables?: AppLevelRequirementsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appLevelRequirementsQueryKey(variables),
    queryFn: () =>
      execute<
        AppLevelRequirementsQueryResult,
        AppLevelRequirementsQueryVariables
      >(appLevelRequirementsQueryDocument, variables, options),
  });
}
