/**
 * Single item query hook for AppOwnerGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type AppOwnerGrant } from '../types';

// Re-export entity type for convenience
export type { AppOwnerGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appOwnerGrantQueryDocument = `
query AppOwnerGrantQuery($id: UUID!) {
  appOwnerGrant(id: $id) {
    id
    isGrant
    actorId
    grantorId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface AppOwnerGrantQueryVariables {
  id: string;
}

export interface AppOwnerGrantQueryResult {
  appOwnerGrant: AppOwnerGrant | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const appOwnerGrantQueryKey = (id: string) =>
  ['appownergrant', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single AppOwnerGrant by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppOwnerGrantQuery('value-here');
 *
 * if (data?.appOwnerGrant) {
 *   console.log(data.appOwnerGrant.id);
 * }
 * ```
 */
export function useAppOwnerGrantQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<AppOwnerGrantQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appOwnerGrantQueryKey(id),
    queryFn: () =>
      execute<AppOwnerGrantQueryResult, AppOwnerGrantQueryVariables>(
        appOwnerGrantQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single AppOwnerGrant by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppOwnerGrantQuery('value-here');
 * ```
 */
export async function fetchAppOwnerGrantQuery(
  id: string,
  options?: ExecuteOptions
): Promise<AppOwnerGrantQueryResult> {
  return execute<AppOwnerGrantQueryResult, AppOwnerGrantQueryVariables>(
    appOwnerGrantQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single AppOwnerGrant for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppOwnerGrantQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchAppOwnerGrantQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appOwnerGrantQueryKey(id),
    queryFn: () =>
      execute<AppOwnerGrantQueryResult, AppOwnerGrantQueryVariables>(
        appOwnerGrantQueryDocument,
        { id },
        options
      ),
  });
}
