/**
 * List query hook for ApiExtension
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type ApiExtension,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { ApiExtension };

// ============================================================================
// GraphQL Document
// ============================================================================
export const apiExtensionsQueryDocument = `
query ApiExtensionsQuery($first: Int, $offset: Int, $filter: ApiExtensionFilter, $orderBy: [ApiExtensionsOrderBy!]) {
  apiExtensions(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      schemaName
      databaseId
      apiId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface ApiExtensionFilter {
  id?: UUIDFilter;
  schemaName?: StringFilter;
  databaseId?: UUIDFilter;
  apiId?: UUIDFilter;
  /** Logical AND */
  and?: ApiExtensionFilter[];
  /** Logical OR */
  or?: ApiExtensionFilter[];
  /** Logical NOT */
  not?: ApiExtensionFilter;
}

type ApiExtensionsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'SCHEMA_NAME_ASC'
  | 'SCHEMA_NAME_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'API_ID_ASC'
  | 'API_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface ApiExtensionsQueryVariables {
  first?: number;
  offset?: number;
  filter?: ApiExtensionFilter;
  orderBy?: ApiExtensionsOrderBy[];
}

export interface ApiExtensionsQueryResult {
  apiExtensions: {
    totalCount: number;
    nodes: ApiExtension[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const apiExtensionsQueryKey = (
  variables?: ApiExtensionsQueryVariables
) => ['apiextension', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching ApiExtension list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useApiExtensionsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useApiExtensionsQuery(
  variables?: ApiExtensionsQueryVariables,
  options?: Omit<
    UseQueryOptions<ApiExtensionsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: apiExtensionsQueryKey(variables),
    queryFn: () =>
      execute<ApiExtensionsQueryResult, ApiExtensionsQueryVariables>(
        apiExtensionsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch ApiExtension list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchApiExtensionsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: apiExtensionsQueryKey(variables),
 *   queryFn: () => fetchApiExtensionsQuery(variables),
 * });
 * ```
 */
export async function fetchApiExtensionsQuery(
  variables?: ApiExtensionsQueryVariables,
  options?: ExecuteOptions
): Promise<ApiExtensionsQueryResult> {
  return execute<ApiExtensionsQueryResult, ApiExtensionsQueryVariables>(
    apiExtensionsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch ApiExtension list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchApiExtensionsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchApiExtensionsQuery(
  queryClient: QueryClient,
  variables?: ApiExtensionsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: apiExtensionsQueryKey(variables),
    queryFn: () =>
      execute<ApiExtensionsQueryResult, ApiExtensionsQueryVariables>(
        apiExtensionsQueryDocument,
        variables,
        options
      ),
  });
}
