/**
 * List query hook for AppLevel
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppLevel,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppLevel };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appLevelsQueryDocument = `
query AppLevelsQuery($first: Int, $offset: Int, $filter: AppLevelFilter, $orderBy: [AppLevelsOrderBy!]) {
  appLevels(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      name
      description
      image
      ownerId
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppLevelFilter {
  id?: UUIDFilter;
  name?: StringFilter;
  description?: StringFilter;
  image?: JSONFilter;
  ownerId?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppLevelFilter[];
  /** Logical OR */
  or?: AppLevelFilter[];
  /** Logical NOT */
  not?: AppLevelFilter;
}

type AppLevelsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'IMAGE_ASC'
  | 'IMAGE_DESC'
  | 'OWNER_ID_ASC'
  | 'OWNER_ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppLevelsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppLevelFilter;
  orderBy?: AppLevelsOrderBy[];
}

export interface AppLevelsQueryResult {
  appLevels: {
    totalCount: number;
    nodes: AppLevel[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appLevelsQueryKey = (variables?: AppLevelsQueryVariables) =>
  ['applevel', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppLevel list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLevelsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppLevelsQuery(
  variables?: AppLevelsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppLevelsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appLevelsQueryKey(variables),
    queryFn: () =>
      execute<AppLevelsQueryResult, AppLevelsQueryVariables>(
        appLevelsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppLevel list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppLevelsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appLevelsQueryKey(variables),
 *   queryFn: () => fetchAppLevelsQuery(variables),
 * });
 * ```
 */
export async function fetchAppLevelsQuery(
  variables?: AppLevelsQueryVariables,
  options?: ExecuteOptions
): Promise<AppLevelsQueryResult> {
  return execute<AppLevelsQueryResult, AppLevelsQueryVariables>(
    appLevelsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppLevel list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLevelsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppLevelsQuery(
  queryClient: QueryClient,
  variables?: AppLevelsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appLevelsQueryKey(variables),
    queryFn: () =>
      execute<AppLevelsQueryResult, AppLevelsQueryVariables>(
        appLevelsQueryDocument,
        variables,
        options
      ),
  });
}
