/**
 * Custom query hook for appPermissionByName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type AppPermission } from '../types';

/** GraphQL query document */
export const appPermissionByNameQueryDocument = `
query AppPermissionByNameQuery($name: String!) {
  appPermissionByName(name: $name) {
    id
    name
    bitnum
    bitstr
    description
  }
}
`;

export interface AppPermissionByNameQueryVariables {
  name: string;
}

export interface AppPermissionByNameQueryResult {
  appPermissionByName: AppPermission;
}

/** Query key factory for caching */
export const appPermissionByNameQueryKey = (
  variables?: AppPermissionByNameQueryVariables
) => ['appPermissionByName', variables] as const;

/**
 * Query hook for appPermissionByName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppPermissionByNameQuery({ name });
 *
 * if (data?.appPermissionByName) {
 *   console.log(data.appPermissionByName);
 * }
 * ```
 */
export function useAppPermissionByNameQuery(
  variables: AppPermissionByNameQueryVariables,
  options?: Omit<
    UseQueryOptions<AppPermissionByNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appPermissionByNameQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionByNameQueryResult,
        AppPermissionByNameQueryVariables
      >(appPermissionByNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch appPermissionByName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppPermissionByNameQuery({ name });
 * ```
 */
export async function fetchAppPermissionByNameQuery(
  variables: AppPermissionByNameQueryVariables,
  options?: ExecuteOptions
): Promise<AppPermissionByNameQueryResult> {
  return execute<
    AppPermissionByNameQueryResult,
    AppPermissionByNameQueryVariables
  >(appPermissionByNameQueryDocument, variables, options);
}

/**
 * Prefetch appPermissionByName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppPermissionByNameQuery(queryClient, { name });
 * ```
 */
export async function prefetchAppPermissionByNameQuery(
  queryClient: QueryClient,
  variables: AppPermissionByNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appPermissionByNameQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionByNameQueryResult,
        AppPermissionByNameQueryVariables
      >(appPermissionByNameQueryDocument, variables, options),
  });
}
