/**
 * List query hook for AppOwnerGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppOwnerGrant,
  type UUIDFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppOwnerGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appOwnerGrantsQueryDocument = `
query AppOwnerGrantsQuery($first: Int, $offset: Int, $filter: AppOwnerGrantFilter, $orderBy: [AppOwnerGrantsOrderBy!]) {
  appOwnerGrants(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      isGrant
      actorId
      grantorId
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppOwnerGrantFilter {
  id?: UUIDFilter;
  isGrant?: BooleanFilter;
  actorId?: UUIDFilter;
  grantorId?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppOwnerGrantFilter[];
  /** Logical OR */
  or?: AppOwnerGrantFilter[];
  /** Logical NOT */
  not?: AppOwnerGrantFilter;
}

type AppOwnerGrantsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_GRANT_ASC'
  | 'IS_GRANT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'GRANTOR_ID_ASC'
  | 'GRANTOR_ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppOwnerGrantsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppOwnerGrantFilter;
  orderBy?: AppOwnerGrantsOrderBy[];
}

export interface AppOwnerGrantsQueryResult {
  appOwnerGrants: {
    totalCount: number;
    nodes: AppOwnerGrant[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appOwnerGrantsQueryKey = (
  variables?: AppOwnerGrantsQueryVariables
) => ['appownergrant', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppOwnerGrant list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppOwnerGrantsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppOwnerGrantsQuery(
  variables?: AppOwnerGrantsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppOwnerGrantsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appOwnerGrantsQueryKey(variables),
    queryFn: () =>
      execute<AppOwnerGrantsQueryResult, AppOwnerGrantsQueryVariables>(
        appOwnerGrantsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppOwnerGrant list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppOwnerGrantsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appOwnerGrantsQueryKey(variables),
 *   queryFn: () => fetchAppOwnerGrantsQuery(variables),
 * });
 * ```
 */
export async function fetchAppOwnerGrantsQuery(
  variables?: AppOwnerGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<AppOwnerGrantsQueryResult> {
  return execute<AppOwnerGrantsQueryResult, AppOwnerGrantsQueryVariables>(
    appOwnerGrantsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppOwnerGrant list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppOwnerGrantsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppOwnerGrantsQuery(
  queryClient: QueryClient,
  variables?: AppOwnerGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appOwnerGrantsQueryKey(variables),
    queryFn: () =>
      execute<AppOwnerGrantsQueryResult, AppOwnerGrantsQueryVariables>(
        appOwnerGrantsQueryDocument,
        variables,
        options
      ),
  });
}
