/**
 * List query hook for AppAdminGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppAdminGrant,
  type UUIDFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppAdminGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appAdminGrantsQueryDocument = `
query AppAdminGrantsQuery($first: Int, $offset: Int, $filter: AppAdminGrantFilter, $orderBy: [AppAdminGrantsOrderBy!]) {
  appAdminGrants(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      isGrant
      actorId
      grantorId
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppAdminGrantFilter {
  id?: UUIDFilter;
  isGrant?: BooleanFilter;
  actorId?: UUIDFilter;
  grantorId?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppAdminGrantFilter[];
  /** Logical OR */
  or?: AppAdminGrantFilter[];
  /** Logical NOT */
  not?: AppAdminGrantFilter;
}

type AppAdminGrantsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_GRANT_ASC'
  | 'IS_GRANT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'GRANTOR_ID_ASC'
  | 'GRANTOR_ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppAdminGrantsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppAdminGrantFilter;
  orderBy?: AppAdminGrantsOrderBy[];
}

export interface AppAdminGrantsQueryResult {
  appAdminGrants: {
    totalCount: number;
    nodes: AppAdminGrant[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appAdminGrantsQueryKey = (
  variables?: AppAdminGrantsQueryVariables
) => ['appadmingrant', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppAdminGrant list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppAdminGrantsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppAdminGrantsQuery(
  variables?: AppAdminGrantsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppAdminGrantsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appAdminGrantsQueryKey(variables),
    queryFn: () =>
      execute<AppAdminGrantsQueryResult, AppAdminGrantsQueryVariables>(
        appAdminGrantsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppAdminGrant list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppAdminGrantsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appAdminGrantsQueryKey(variables),
 *   queryFn: () => fetchAppAdminGrantsQuery(variables),
 * });
 * ```
 */
export async function fetchAppAdminGrantsQuery(
  variables?: AppAdminGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<AppAdminGrantsQueryResult> {
  return execute<AppAdminGrantsQueryResult, AppAdminGrantsQueryVariables>(
    appAdminGrantsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppAdminGrant list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppAdminGrantsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppAdminGrantsQuery(
  queryClient: QueryClient,
  variables?: AppAdminGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appAdminGrantsQueryKey(variables),
    queryFn: () =>
      execute<AppAdminGrantsQueryResult, AppAdminGrantsQueryVariables>(
        appAdminGrantsQueryDocument,
        variables,
        options
      ),
  });
}
