/**
 * Custom query hook for appPermissionsGetMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';

/** GraphQL query document */
export const appPermissionsGetMaskQueryDocument = `
query AppPermissionsGetMaskQuery($ids: [UUID]) {
  appPermissionsGetMask(ids: $ids)
}
`;

export interface AppPermissionsGetMaskQueryVariables {
  ids?: string[];
}

export interface AppPermissionsGetMaskQueryResult {
  appPermissionsGetMask: string;
}

/** Query key factory for caching */
export const appPermissionsGetMaskQueryKey = (
  variables?: AppPermissionsGetMaskQueryVariables
) => ['appPermissionsGetMask', variables] as const;

/**
 * Query hook for appPermissionsGetMask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppPermissionsGetMaskQuery({ ids });
 *
 * if (data?.appPermissionsGetMask) {
 *   console.log(data.appPermissionsGetMask);
 * }
 * ```
 */
export function useAppPermissionsGetMaskQuery(
  variables?: AppPermissionsGetMaskQueryVariables,
  options?: Omit<
    UseQueryOptions<AppPermissionsGetMaskQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appPermissionsGetMaskQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionsGetMaskQueryResult,
        AppPermissionsGetMaskQueryVariables
      >(appPermissionsGetMaskQueryDocument, variables),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch appPermissionsGetMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppPermissionsGetMaskQuery({ ids });
 * ```
 */
export async function fetchAppPermissionsGetMaskQuery(
  variables?: AppPermissionsGetMaskQueryVariables,
  options?: ExecuteOptions
): Promise<AppPermissionsGetMaskQueryResult> {
  return execute<
    AppPermissionsGetMaskQueryResult,
    AppPermissionsGetMaskQueryVariables
  >(appPermissionsGetMaskQueryDocument, variables, options);
}

/**
 * Prefetch appPermissionsGetMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppPermissionsGetMaskQuery(queryClient, { ids });
 * ```
 */
export async function prefetchAppPermissionsGetMaskQuery(
  queryClient: QueryClient,
  variables?: AppPermissionsGetMaskQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appPermissionsGetMaskQueryKey(variables),
    queryFn: () =>
      execute<
        AppPermissionsGetMaskQueryResult,
        AppPermissionsGetMaskQueryVariables
      >(appPermissionsGetMaskQueryDocument, variables, options),
  });
}
