/**
 * List query hook for AuditLog
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AuditLog,
  type UUIDFilter,
  type StringFilter,
  type InternetAddressFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AuditLog };

// ============================================================================
// GraphQL Document
// ============================================================================
export const auditLogsQueryDocument = `
query AuditLogsQuery($first: Int, $offset: Int, $filter: AuditLogFilter, $orderBy: [AuditLogsOrderBy!]) {
  auditLogs(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      event
      actorId
      origin
      userAgent
      ipAddress
      success
      createdAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AuditLogFilter {
  id?: UUIDFilter;
  event?: StringFilter;
  actorId?: UUIDFilter;
  origin?: StringFilter;
  userAgent?: StringFilter;
  ipAddress?: InternetAddressFilter;
  success?: BooleanFilter;
  createdAt?: DatetimeFilter;
  /** Logical AND */
  and?: AuditLogFilter[];
  /** Logical OR */
  or?: AuditLogFilter[];
  /** Logical NOT */
  not?: AuditLogFilter;
}

type AuditLogsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'EVENT_ASC'
  | 'EVENT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'ORIGIN_ASC'
  | 'ORIGIN_DESC'
  | 'USER_AGENT_ASC'
  | 'USER_AGENT_DESC'
  | 'IP_ADDRESS_ASC'
  | 'IP_ADDRESS_DESC'
  | 'SUCCESS_ASC'
  | 'SUCCESS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AuditLogsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AuditLogFilter;
  orderBy?: AuditLogsOrderBy[];
}

export interface AuditLogsQueryResult {
  auditLogs: {
    totalCount: number;
    nodes: AuditLog[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const auditLogsQueryKey = (variables?: AuditLogsQueryVariables) =>
  ['auditlog', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AuditLog list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAuditLogsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAuditLogsQuery(
  variables?: AuditLogsQueryVariables,
  options?: Omit<
    UseQueryOptions<AuditLogsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: auditLogsQueryKey(variables),
    queryFn: () =>
      execute<AuditLogsQueryResult, AuditLogsQueryVariables>(
        auditLogsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AuditLog list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAuditLogsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: auditLogsQueryKey(variables),
 *   queryFn: () => fetchAuditLogsQuery(variables),
 * });
 * ```
 */
export async function fetchAuditLogsQuery(
  variables?: AuditLogsQueryVariables,
  options?: ExecuteOptions
): Promise<AuditLogsQueryResult> {
  return execute<AuditLogsQueryResult, AuditLogsQueryVariables>(
    auditLogsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AuditLog list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAuditLogsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAuditLogsQuery(
  queryClient: QueryClient,
  variables?: AuditLogsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: auditLogsQueryKey(variables),
    queryFn: () =>
      execute<AuditLogsQueryResult, AuditLogsQueryVariables>(
        auditLogsQueryDocument,
        variables,
        options
      ),
  });
}
