/**
 * List query hook for ApiSchema
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ApiSchema, type UUIDFilter } from '../types';

// Re-export entity type for convenience
export type { ApiSchema };

// ============================================================================
// GraphQL Document
// ============================================================================
export const apiSchemasQueryDocument = `
query ApiSchemasQuery($first: Int, $offset: Int, $filter: ApiSchemaFilter, $orderBy: [ApiSchemasOrderBy!]) {
  apiSchemas(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      apiId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface ApiSchemaFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  apiId?: UUIDFilter;
  /** Logical AND */
  and?: ApiSchemaFilter[];
  /** Logical OR */
  or?: ApiSchemaFilter[];
  /** Logical NOT */
  not?: ApiSchemaFilter;
}

type ApiSchemasOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'API_ID_ASC'
  | 'API_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface ApiSchemasQueryVariables {
  first?: number;
  offset?: number;
  filter?: ApiSchemaFilter;
  orderBy?: ApiSchemasOrderBy[];
}

export interface ApiSchemasQueryResult {
  apiSchemas: {
    totalCount: number;
    nodes: ApiSchema[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const apiSchemasQueryKey = (variables?: ApiSchemasQueryVariables) =>
  ['apischema', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching ApiSchema list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useApiSchemasQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useApiSchemasQuery(
  variables?: ApiSchemasQueryVariables,
  options?: Omit<
    UseQueryOptions<ApiSchemasQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: apiSchemasQueryKey(variables),
    queryFn: () =>
      execute<ApiSchemasQueryResult, ApiSchemasQueryVariables>(
        apiSchemasQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch ApiSchema list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchApiSchemasQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: apiSchemasQueryKey(variables),
 *   queryFn: () => fetchApiSchemasQuery(variables),
 * });
 * ```
 */
export async function fetchApiSchemasQuery(
  variables?: ApiSchemasQueryVariables,
  options?: ExecuteOptions
): Promise<ApiSchemasQueryResult> {
  return execute<ApiSchemasQueryResult, ApiSchemasQueryVariables>(
    apiSchemasQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch ApiSchema list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchApiSchemasQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchApiSchemasQuery(
  queryClient: QueryClient,
  variables?: ApiSchemasQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: apiSchemasQueryKey(variables),
    queryFn: () =>
      execute<ApiSchemasQueryResult, ApiSchemasQueryVariables>(
        apiSchemasQueryDocument,
        variables,
        options
      ),
  });
}
