/**
 * List query hook for AppAchievement
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppAchievement,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppAchievement };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appAchievementsQueryDocument = `
query AppAchievementsQuery($first: Int, $offset: Int, $filter: AppAchievementFilter, $orderBy: [AppAchievementsOrderBy!]) {
  appAchievements(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      actorId
      name
      count
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppAchievementFilter {
  id?: UUIDFilter;
  actorId?: UUIDFilter;
  name?: StringFilter;
  count?: IntFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppAchievementFilter[];
  /** Logical OR */
  or?: AppAchievementFilter[];
  /** Logical NOT */
  not?: AppAchievementFilter;
}

type AppAchievementsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'COUNT_ASC'
  | 'COUNT_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppAchievementsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppAchievementFilter;
  orderBy?: AppAchievementsOrderBy[];
}

export interface AppAchievementsQueryResult {
  appAchievements: {
    totalCount: number;
    nodes: AppAchievement[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appAchievementsQueryKey = (
  variables?: AppAchievementsQueryVariables
) => ['appachievement', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppAchievement list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppAchievementsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppAchievementsQuery(
  variables?: AppAchievementsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppAchievementsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appAchievementsQueryKey(variables),
    queryFn: () =>
      execute<AppAchievementsQueryResult, AppAchievementsQueryVariables>(
        appAchievementsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppAchievement list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppAchievementsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appAchievementsQueryKey(variables),
 *   queryFn: () => fetchAppAchievementsQuery(variables),
 * });
 * ```
 */
export async function fetchAppAchievementsQuery(
  variables?: AppAchievementsQueryVariables,
  options?: ExecuteOptions
): Promise<AppAchievementsQueryResult> {
  return execute<AppAchievementsQueryResult, AppAchievementsQueryVariables>(
    appAchievementsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppAchievement list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppAchievementsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppAchievementsQuery(
  queryClient: QueryClient,
  variables?: AppAchievementsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appAchievementsQueryKey(variables),
    queryFn: () =>
      execute<AppAchievementsQueryResult, AppAchievementsQueryVariables>(
        appAchievementsQueryDocument,
        variables,
        options
      ),
  });
}
