/**
 * List query hook for App
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type App,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
} from '../types';

// Re-export entity type for convenience
export type { App };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appsQueryDocument = `
query AppsQuery($first: Int, $offset: Int, $filter: AppFilter, $orderBy: [AppsOrderBy!]) {
  apps(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      siteId
      name
      appImage
      appStoreLink
      appStoreId
      appIdPrefix
      playStoreLink
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  siteId?: UUIDFilter;
  name?: StringFilter;
  appImage?: JSONFilter;
  appStoreLink?: StringFilter;
  appStoreId?: StringFilter;
  appIdPrefix?: StringFilter;
  playStoreLink?: StringFilter;
  /** Logical AND */
  and?: AppFilter[];
  /** Logical OR */
  or?: AppFilter[];
  /** Logical NOT */
  not?: AppFilter;
}

type AppsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SITE_ID_ASC'
  | 'SITE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'APP_IMAGE_ASC'
  | 'APP_IMAGE_DESC'
  | 'APP_STORE_LINK_ASC'
  | 'APP_STORE_LINK_DESC'
  | 'APP_STORE_ID_ASC'
  | 'APP_STORE_ID_DESC'
  | 'APP_ID_PREFIX_ASC'
  | 'APP_ID_PREFIX_DESC'
  | 'PLAY_STORE_LINK_ASC'
  | 'PLAY_STORE_LINK_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppFilter;
  orderBy?: AppsOrderBy[];
}

export interface AppsQueryResult {
  apps: {
    totalCount: number;
    nodes: App[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appsQueryKey = (variables?: AppsQueryVariables) =>
  ['app', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching App list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppsQuery(
  variables?: AppsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appsQueryKey(variables),
    queryFn: () =>
      execute<AppsQueryResult, AppsQueryVariables>(
        appsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch App list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appsQueryKey(variables),
 *   queryFn: () => fetchAppsQuery(variables),
 * });
 * ```
 */
export async function fetchAppsQuery(
  variables?: AppsQueryVariables,
  options?: ExecuteOptions
): Promise<AppsQueryResult> {
  return execute<AppsQueryResult, AppsQueryVariables>(
    appsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch App list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppsQuery(
  queryClient: QueryClient,
  variables?: AppsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appsQueryKey(variables),
    queryFn: () =>
      execute<AppsQueryResult, AppsQueryVariables>(
        appsQueryDocument,
        variables,
        options
      ),
  });
}
