/**
 * List query hook for AppStep
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type AppStep,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { AppStep };

// ============================================================================
// GraphQL Document
// ============================================================================
export const appStepsQueryDocument = `
query AppStepsQuery($first: Int, $offset: Int, $filter: AppStepFilter, $orderBy: [AppStepsOrderBy!]) {
  appSteps(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      actorId
      name
      count
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface AppStepFilter {
  id?: UUIDFilter;
  actorId?: UUIDFilter;
  name?: StringFilter;
  count?: IntFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: AppStepFilter[];
  /** Logical OR */
  or?: AppStepFilter[];
  /** Logical NOT */
  not?: AppStepFilter;
}

type AppStepsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'COUNT_ASC'
  | 'COUNT_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface AppStepsQueryVariables {
  first?: number;
  offset?: number;
  filter?: AppStepFilter;
  orderBy?: AppStepsOrderBy[];
}

export interface AppStepsQueryResult {
  appSteps: {
    totalCount: number;
    nodes: AppStep[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const appStepsQueryKey = (variables?: AppStepsQueryVariables) =>
  ['appstep', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching AppStep list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppStepsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useAppStepsQuery(
  variables?: AppStepsQueryVariables,
  options?: Omit<
    UseQueryOptions<AppStepsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: appStepsQueryKey(variables),
    queryFn: () =>
      execute<AppStepsQueryResult, AppStepsQueryVariables>(
        appStepsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch AppStep list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchAppStepsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: appStepsQueryKey(variables),
 *   queryFn: () => fetchAppStepsQuery(variables),
 * });
 * ```
 */
export async function fetchAppStepsQuery(
  variables?: AppStepsQueryVariables,
  options?: ExecuteOptions
): Promise<AppStepsQueryResult> {
  return execute<AppStepsQueryResult, AppStepsQueryVariables>(
    appStepsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch AppStep list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppStepsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchAppStepsQuery(
  queryClient: QueryClient,
  variables?: AppStepsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: appStepsQueryKey(variables),
    queryFn: () =>
      execute<AppStepsQueryResult, AppStepsQueryVariables>(
        appStepsQueryDocument,
        variables,
        options
      ),
  });
}
