/**
 * Custom query hook for currentUserId
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';

/** GraphQL query document */
export const currentUserIdQueryDocument = `
query CurrentUserIdQuery {
  currentUserId
}
`;

export interface CurrentUserIdQueryResult {
  currentUserId: string;
}

/** Query key factory for caching */
export const currentUserIdQueryKey = () => ['currentUserId'] as const;

/**
 * Query hook for currentUserId
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCurrentUserIdQuery();
 *
 * if (data?.currentUserId) {
 *   console.log(data.currentUserId);
 * }
 * ```
 */
export function useCurrentUserIdQuery(
  options?: Omit<
    UseQueryOptions<CurrentUserIdQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: currentUserIdQueryKey(),
    queryFn: () =>
      execute<CurrentUserIdQueryResult>(currentUserIdQueryDocument),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch currentUserId without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchCurrentUserIdQuery();
 * ```
 */
export async function fetchCurrentUserIdQuery(
  options?: ExecuteOptions
): Promise<CurrentUserIdQueryResult> {
  return execute<CurrentUserIdQueryResult>(
    currentUserIdQueryDocument,
    undefined,
    options
  );
}

/**
 * Prefetch currentUserId for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchCurrentUserIdQuery(queryClient);
 * ```
 */
export async function prefetchCurrentUserIdQuery(
  queryClient: QueryClient,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: currentUserIdQueryKey(),
    queryFn: () =>
      execute<CurrentUserIdQueryResult>(
        currentUserIdQueryDocument,
        undefined,
        options
      ),
  });
}
