/**
 * List query hook for CryptoAddress
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type CryptoAddress,
  type UUIDFilter,
  type StringFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { CryptoAddress };

// ============================================================================
// GraphQL Document
// ============================================================================
export const cryptoAddressesQueryDocument = `
query CryptoAddressesQuery($first: Int, $offset: Int, $filter: CryptoAddressFilter, $orderBy: [CryptoAddressesOrderBy!]) {
  cryptoAddresses(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      ownerId
      address
      isVerified
      isPrimary
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface CryptoAddressFilter {
  id?: UUIDFilter;
  ownerId?: UUIDFilter;
  address?: StringFilter;
  isVerified?: BooleanFilter;
  isPrimary?: BooleanFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: CryptoAddressFilter[];
  /** Logical OR */
  or?: CryptoAddressFilter[];
  /** Logical NOT */
  not?: CryptoAddressFilter;
}

type CryptoAddressesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'OWNER_ID_ASC'
  | 'OWNER_ID_DESC'
  | 'ADDRESS_ASC'
  | 'ADDRESS_DESC'
  | 'IS_VERIFIED_ASC'
  | 'IS_VERIFIED_DESC'
  | 'IS_PRIMARY_ASC'
  | 'IS_PRIMARY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface CryptoAddressesQueryVariables {
  first?: number;
  offset?: number;
  filter?: CryptoAddressFilter;
  orderBy?: CryptoAddressesOrderBy[];
}

export interface CryptoAddressesQueryResult {
  cryptoAddresses: {
    totalCount: number;
    nodes: CryptoAddress[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const cryptoAddressesQueryKey = (
  variables?: CryptoAddressesQueryVariables
) => ['cryptoaddress', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching CryptoAddress list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCryptoAddressesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useCryptoAddressesQuery(
  variables?: CryptoAddressesQueryVariables,
  options?: Omit<
    UseQueryOptions<CryptoAddressesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: cryptoAddressesQueryKey(variables),
    queryFn: () =>
      execute<CryptoAddressesQueryResult, CryptoAddressesQueryVariables>(
        cryptoAddressesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch CryptoAddress list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchCryptoAddressesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: cryptoAddressesQueryKey(variables),
 *   queryFn: () => fetchCryptoAddressesQuery(variables),
 * });
 * ```
 */
export async function fetchCryptoAddressesQuery(
  variables?: CryptoAddressesQueryVariables,
  options?: ExecuteOptions
): Promise<CryptoAddressesQueryResult> {
  return execute<CryptoAddressesQueryResult, CryptoAddressesQueryVariables>(
    cryptoAddressesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch CryptoAddress list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchCryptoAddressesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchCryptoAddressesQuery(
  queryClient: QueryClient,
  variables?: CryptoAddressesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: cryptoAddressesQueryKey(variables),
    queryFn: () =>
      execute<CryptoAddressesQueryResult, CryptoAddressesQueryVariables>(
        cryptoAddressesQueryDocument,
        variables,
        options
      ),
  });
}
