/**
 * List query hook for ConnectedAccountsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type ConnectedAccountsModule,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { ConnectedAccountsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const connectedAccountsModulesQueryDocument = `
query ConnectedAccountsModulesQuery($first: Int, $offset: Int, $filter: ConnectedAccountsModuleFilter, $orderBy: [ConnectedAccountsModulesOrderBy!]) {
  connectedAccountsModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      tableId
      ownerTableId
      tableName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface ConnectedAccountsModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  ownerTableId?: UUIDFilter;
  tableName?: StringFilter;
  /** Logical AND */
  and?: ConnectedAccountsModuleFilter[];
  /** Logical OR */
  or?: ConnectedAccountsModuleFilter[];
  /** Logical NOT */
  not?: ConnectedAccountsModuleFilter;
}

type ConnectedAccountsModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'OWNER_TABLE_ID_ASC'
  | 'OWNER_TABLE_ID_DESC'
  | 'TABLE_NAME_ASC'
  | 'TABLE_NAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface ConnectedAccountsModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: ConnectedAccountsModuleFilter;
  orderBy?: ConnectedAccountsModulesOrderBy[];
}

export interface ConnectedAccountsModulesQueryResult {
  connectedAccountsModules: {
    totalCount: number;
    nodes: ConnectedAccountsModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const connectedAccountsModulesQueryKey = (
  variables?: ConnectedAccountsModulesQueryVariables
) => ['connectedaccountsmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching ConnectedAccountsModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useConnectedAccountsModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useConnectedAccountsModulesQuery(
  variables?: ConnectedAccountsModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<ConnectedAccountsModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: connectedAccountsModulesQueryKey(variables),
    queryFn: () =>
      execute<
        ConnectedAccountsModulesQueryResult,
        ConnectedAccountsModulesQueryVariables
      >(connectedAccountsModulesQueryDocument, variables),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch ConnectedAccountsModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchConnectedAccountsModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: connectedAccountsModulesQueryKey(variables),
 *   queryFn: () => fetchConnectedAccountsModulesQuery(variables),
 * });
 * ```
 */
export async function fetchConnectedAccountsModulesQuery(
  variables?: ConnectedAccountsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<ConnectedAccountsModulesQueryResult> {
  return execute<
    ConnectedAccountsModulesQueryResult,
    ConnectedAccountsModulesQueryVariables
  >(connectedAccountsModulesQueryDocument, variables, options);
}

/**
 * Prefetch ConnectedAccountsModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchConnectedAccountsModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchConnectedAccountsModulesQuery(
  queryClient: QueryClient,
  variables?: ConnectedAccountsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: connectedAccountsModulesQueryKey(variables),
    queryFn: () =>
      execute<
        ConnectedAccountsModulesQueryResult,
        ConnectedAccountsModulesQueryVariables
      >(connectedAccountsModulesQueryDocument, variables, options),
  });
}
