/**
 * Single item query hook for ConnectedAccountsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ConnectedAccountsModule } from '../types';

// Re-export entity type for convenience
export type { ConnectedAccountsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const connectedAccountsModuleQueryDocument = `
query ConnectedAccountsModuleQuery($id: UUID!) {
  connectedAccountsModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    tableId
    ownerTableId
    tableName
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface ConnectedAccountsModuleQueryVariables {
  id: string;
}

export interface ConnectedAccountsModuleQueryResult {
  connectedAccountsModule: ConnectedAccountsModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const connectedAccountsModuleQueryKey = (id: string) =>
  ['connectedaccountsmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single ConnectedAccountsModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useConnectedAccountsModuleQuery('value-here');
 *
 * if (data?.connectedAccountsModule) {
 *   console.log(data.connectedAccountsModule.id);
 * }
 * ```
 */
export function useConnectedAccountsModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<ConnectedAccountsModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: connectedAccountsModuleQueryKey(id),
    queryFn: () =>
      execute<
        ConnectedAccountsModuleQueryResult,
        ConnectedAccountsModuleQueryVariables
      >(connectedAccountsModuleQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single ConnectedAccountsModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchConnectedAccountsModuleQuery('value-here');
 * ```
 */
export async function fetchConnectedAccountsModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<ConnectedAccountsModuleQueryResult> {
  return execute<
    ConnectedAccountsModuleQueryResult,
    ConnectedAccountsModuleQueryVariables
  >(connectedAccountsModuleQueryDocument, { id }, options);
}

/**
 * Prefetch a single ConnectedAccountsModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchConnectedAccountsModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchConnectedAccountsModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: connectedAccountsModuleQueryKey(id),
    queryFn: () =>
      execute<
        ConnectedAccountsModuleQueryResult,
        ConnectedAccountsModuleQueryVariables
      >(connectedAccountsModuleQueryDocument, { id }, options),
  });
}
