/**
 * Single item query hook for ClaimedInvite
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ClaimedInvite } from '../types';

// Re-export entity type for convenience
export type { ClaimedInvite };

// ============================================================================
// GraphQL Document
// ============================================================================
export const claimedInviteQueryDocument = `
query ClaimedInviteQuery($id: UUID!) {
  claimedInvite(id: $id) {
    id
    data
    senderId
    receiverId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface ClaimedInviteQueryVariables {
  id: string;
}

export interface ClaimedInviteQueryResult {
  claimedInvite: ClaimedInvite | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const claimedInviteQueryKey = (id: string) =>
  ['claimedinvite', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single ClaimedInvite by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useClaimedInviteQuery('value-here');
 *
 * if (data?.claimedInvite) {
 *   console.log(data.claimedInvite.id);
 * }
 * ```
 */
export function useClaimedInviteQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<ClaimedInviteQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: claimedInviteQueryKey(id),
    queryFn: () =>
      execute<ClaimedInviteQueryResult, ClaimedInviteQueryVariables>(
        claimedInviteQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single ClaimedInvite by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchClaimedInviteQuery('value-here');
 * ```
 */
export async function fetchClaimedInviteQuery(
  id: string,
  options?: ExecuteOptions
): Promise<ClaimedInviteQueryResult> {
  return execute<ClaimedInviteQueryResult, ClaimedInviteQueryVariables>(
    claimedInviteQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single ClaimedInvite for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchClaimedInviteQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchClaimedInviteQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: claimedInviteQueryKey(id),
    queryFn: () =>
      execute<ClaimedInviteQueryResult, ClaimedInviteQueryVariables>(
        claimedInviteQueryDocument,
        { id },
        options
      ),
  });
}
