/**
 * List query hook for CryptoAuthModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type CryptoAuthModule,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { CryptoAuthModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const cryptoAuthModulesQueryDocument = `
query CryptoAuthModulesQuery($first: Int, $offset: Int, $filter: CryptoAuthModuleFilter, $orderBy: [CryptoAuthModulesOrderBy!]) {
  cryptoAuthModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      usersTableId
      tokensTableId
      secretsTableId
      addressesTableId
      userField
      cryptoNetwork
      signInRequestChallenge
      signInRecordFailure
      signUpWithKey
      signInWithChallenge
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface CryptoAuthModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  usersTableId?: UUIDFilter;
  tokensTableId?: UUIDFilter;
  secretsTableId?: UUIDFilter;
  addressesTableId?: UUIDFilter;
  userField?: StringFilter;
  cryptoNetwork?: StringFilter;
  signInRequestChallenge?: StringFilter;
  signInRecordFailure?: StringFilter;
  signUpWithKey?: StringFilter;
  signInWithChallenge?: StringFilter;
  /** Logical AND */
  and?: CryptoAuthModuleFilter[];
  /** Logical OR */
  or?: CryptoAuthModuleFilter[];
  /** Logical NOT */
  not?: CryptoAuthModuleFilter;
}

type CryptoAuthModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'USERS_TABLE_ID_ASC'
  | 'USERS_TABLE_ID_DESC'
  | 'TOKENS_TABLE_ID_ASC'
  | 'TOKENS_TABLE_ID_DESC'
  | 'SECRETS_TABLE_ID_ASC'
  | 'SECRETS_TABLE_ID_DESC'
  | 'ADDRESSES_TABLE_ID_ASC'
  | 'ADDRESSES_TABLE_ID_DESC'
  | 'USER_FIELD_ASC'
  | 'USER_FIELD_DESC'
  | 'CRYPTO_NETWORK_ASC'
  | 'CRYPTO_NETWORK_DESC'
  | 'SIGN_IN_REQUEST_CHALLENGE_ASC'
  | 'SIGN_IN_REQUEST_CHALLENGE_DESC'
  | 'SIGN_IN_RECORD_FAILURE_ASC'
  | 'SIGN_IN_RECORD_FAILURE_DESC'
  | 'SIGN_UP_WITH_KEY_ASC'
  | 'SIGN_UP_WITH_KEY_DESC'
  | 'SIGN_IN_WITH_CHALLENGE_ASC'
  | 'SIGN_IN_WITH_CHALLENGE_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface CryptoAuthModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: CryptoAuthModuleFilter;
  orderBy?: CryptoAuthModulesOrderBy[];
}

export interface CryptoAuthModulesQueryResult {
  cryptoAuthModules: {
    totalCount: number;
    nodes: CryptoAuthModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const cryptoAuthModulesQueryKey = (
  variables?: CryptoAuthModulesQueryVariables
) => ['cryptoauthmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching CryptoAuthModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCryptoAuthModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useCryptoAuthModulesQuery(
  variables?: CryptoAuthModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<CryptoAuthModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: cryptoAuthModulesQueryKey(variables),
    queryFn: () =>
      execute<CryptoAuthModulesQueryResult, CryptoAuthModulesQueryVariables>(
        cryptoAuthModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch CryptoAuthModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchCryptoAuthModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: cryptoAuthModulesQueryKey(variables),
 *   queryFn: () => fetchCryptoAuthModulesQuery(variables),
 * });
 * ```
 */
export async function fetchCryptoAuthModulesQuery(
  variables?: CryptoAuthModulesQueryVariables,
  options?: ExecuteOptions
): Promise<CryptoAuthModulesQueryResult> {
  return execute<CryptoAuthModulesQueryResult, CryptoAuthModulesQueryVariables>(
    cryptoAuthModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch CryptoAuthModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchCryptoAuthModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchCryptoAuthModulesQuery(
  queryClient: QueryClient,
  variables?: CryptoAuthModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: cryptoAuthModulesQueryKey(variables),
    queryFn: () =>
      execute<CryptoAuthModulesQueryResult, CryptoAuthModulesQueryVariables>(
        cryptoAuthModulesQueryDocument,
        variables,
        options
      ),
  });
}
