/**
 * Single item query hook for Commit
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Commit } from '../types';

// Re-export entity type for convenience
export type { Commit };

// ============================================================================
// GraphQL Document
// ============================================================================
export const commitQueryDocument = `
query CommitQuery($id: UUID!) {
  commit(id: $id) {
    id
    message
    databaseId
    storeId
    parentIds
    authorId
    committerId
    treeId
    date
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface CommitQueryVariables {
  id: string;
}

export interface CommitQueryResult {
  commit: Commit | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const commitQueryKey = (id: string) => ['commit', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Commit by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCommitQuery('value-here');
 *
 * if (data?.commit) {
 *   console.log(data.commit.id);
 * }
 * ```
 */
export function useCommitQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<CommitQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: commitQueryKey(id),
    queryFn: () =>
      execute<CommitQueryResult, CommitQueryVariables>(commitQueryDocument, {
        id,
      }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Commit by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchCommitQuery('value-here');
 * ```
 */
export async function fetchCommitQuery(
  id: string,
  options?: ExecuteOptions
): Promise<CommitQueryResult> {
  return execute<CommitQueryResult, CommitQueryVariables>(
    commitQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Commit for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchCommitQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchCommitQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: commitQueryKey(id),
    queryFn: () =>
      execute<CommitQueryResult, CommitQueryVariables>(
        commitQueryDocument,
        { id },
        options
      ),
  });
}
