/**
 * Single item query hook for CryptoAuthModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type CryptoAuthModule } from '../types';

// Re-export entity type for convenience
export type { CryptoAuthModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const cryptoAuthModuleQueryDocument = `
query CryptoAuthModuleQuery($id: UUID!) {
  cryptoAuthModule(id: $id) {
    id
    databaseId
    schemaId
    usersTableId
    tokensTableId
    secretsTableId
    addressesTableId
    userField
    cryptoNetwork
    signInRequestChallenge
    signInRecordFailure
    signUpWithKey
    signInWithChallenge
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface CryptoAuthModuleQueryVariables {
  id: string;
}

export interface CryptoAuthModuleQueryResult {
  cryptoAuthModule: CryptoAuthModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const cryptoAuthModuleQueryKey = (id: string) =>
  ['cryptoauthmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single CryptoAuthModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCryptoAuthModuleQuery('value-here');
 *
 * if (data?.cryptoAuthModule) {
 *   console.log(data.cryptoAuthModule.id);
 * }
 * ```
 */
export function useCryptoAuthModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<CryptoAuthModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: cryptoAuthModuleQueryKey(id),
    queryFn: () =>
      execute<CryptoAuthModuleQueryResult, CryptoAuthModuleQueryVariables>(
        cryptoAuthModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single CryptoAuthModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchCryptoAuthModuleQuery('value-here');
 * ```
 */
export async function fetchCryptoAuthModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<CryptoAuthModuleQueryResult> {
  return execute<CryptoAuthModuleQueryResult, CryptoAuthModuleQueryVariables>(
    cryptoAuthModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single CryptoAuthModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchCryptoAuthModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchCryptoAuthModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: cryptoAuthModuleQueryKey(id),
    queryFn: () =>
      execute<CryptoAuthModuleQueryResult, CryptoAuthModuleQueryVariables>(
        cryptoAuthModuleQueryDocument,
        { id },
        options
      ),
  });
}
