/**
 * Single item query hook for Database
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Database } from '../types';

// Re-export entity type for convenience
export type { Database };

// ============================================================================
// GraphQL Document
// ============================================================================
export const databaseQueryDocument = `
query DatabaseQuery($id: UUID!) {
  database(id: $id) {
    id
    ownerId
    schemaName
    privateSchemaName
    name
    label
    hash
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface DatabaseQueryVariables {
  id: string;
}

export interface DatabaseQueryResult {
  database: Database | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const databaseQueryKey = (id: string) =>
  ['database', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Database by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDatabaseQuery('value-here');
 *
 * if (data?.database) {
 *   console.log(data.database.id);
 * }
 * ```
 */
export function useDatabaseQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<DatabaseQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: databaseQueryKey(id),
    queryFn: () =>
      execute<DatabaseQueryResult, DatabaseQueryVariables>(
        databaseQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Database by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchDatabaseQuery('value-here');
 * ```
 */
export async function fetchDatabaseQuery(
  id: string,
  options?: ExecuteOptions
): Promise<DatabaseQueryResult> {
  return execute<DatabaseQueryResult, DatabaseQueryVariables>(
    databaseQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Database for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDatabaseQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchDatabaseQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: databaseQueryKey(id),
    queryFn: () =>
      execute<DatabaseQueryResult, DatabaseQueryVariables>(
        databaseQueryDocument,
        { id },
        options
      ),
  });
}
