/**
 * List query hook for Database
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Database,
  type UUIDFilter,
  type StringFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Database };

// ============================================================================
// GraphQL Document
// ============================================================================
export const databasesQueryDocument = `
query DatabasesQuery($first: Int, $offset: Int, $filter: DatabaseFilter, $orderBy: [DatabasesOrderBy!]) {
  databases(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface DatabaseFilter {
  id?: UUIDFilter;
  ownerId?: UUIDFilter;
  schemaName?: StringFilter;
  privateSchemaName?: StringFilter;
  name?: StringFilter;
  label?: StringFilter;
  hash?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: DatabaseFilter[];
  /** Logical OR */
  or?: DatabaseFilter[];
  /** Logical NOT */
  not?: DatabaseFilter;
}

type DatabasesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'OWNER_ID_ASC'
  | 'OWNER_ID_DESC'
  | 'SCHEMA_NAME_ASC'
  | 'SCHEMA_NAME_DESC'
  | 'PRIVATE_SCHEMA_NAME_ASC'
  | 'PRIVATE_SCHEMA_NAME_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'LABEL_ASC'
  | 'LABEL_DESC'
  | 'HASH_ASC'
  | 'HASH_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface DatabasesQueryVariables {
  first?: number;
  offset?: number;
  filter?: DatabaseFilter;
  orderBy?: DatabasesOrderBy[];
}

export interface DatabasesQueryResult {
  databases: {
    totalCount: number;
    nodes: Database[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const databasesQueryKey = (variables?: DatabasesQueryVariables) =>
  ['database', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Database list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDatabasesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useDatabasesQuery(
  variables?: DatabasesQueryVariables,
  options?: Omit<
    UseQueryOptions<DatabasesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: databasesQueryKey(variables),
    queryFn: () =>
      execute<DatabasesQueryResult, DatabasesQueryVariables>(
        databasesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Database list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchDatabasesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: databasesQueryKey(variables),
 *   queryFn: () => fetchDatabasesQuery(variables),
 * });
 * ```
 */
export async function fetchDatabasesQuery(
  variables?: DatabasesQueryVariables,
  options?: ExecuteOptions
): Promise<DatabasesQueryResult> {
  return execute<DatabasesQueryResult, DatabasesQueryVariables>(
    databasesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Database list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDatabasesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchDatabasesQuery(
  queryClient: QueryClient,
  variables?: DatabasesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: databasesQueryKey(variables),
    queryFn: () =>
      execute<DatabasesQueryResult, DatabasesQueryVariables>(
        databasesQueryDocument,
        variables,
        options
      ),
  });
}
