/**
 * Custom query hook for domainBySubdomainAndDomain
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Domain } from '../types';

/** GraphQL query document */
export const domainBySubdomainAndDomainQueryDocument = `
query DomainBySubdomainAndDomainQuery($subdomain: String!, $domain: String!) {
  domainBySubdomainAndDomain(subdomain: $subdomain, domain: $domain) {
    id
    databaseId
    apiId
    siteId
    subdomain
    domain
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    api {
      id
      databaseId
      name
      dbname
      roleName
      anonRole
      isPublic
    }
    site {
      id
      databaseId
      title
      description
      ogImage
      favicon
      appleTouchIcon
      logo
      dbname
    }
  }
}
`;

export interface DomainBySubdomainAndDomainQueryVariables {
  subdomain: string;
  domain: string;
}

export interface DomainBySubdomainAndDomainQueryResult {
  domainBySubdomainAndDomain: Domain;
}

/** Query key factory for caching */
export const domainBySubdomainAndDomainQueryKey = (
  variables?: DomainBySubdomainAndDomainQueryVariables
) => ['domainBySubdomainAndDomain', variables] as const;

/**
 * Query hook for domainBySubdomainAndDomain
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDomainBySubdomainAndDomainQuery({ subdomain, domain });
 *
 * if (data?.domainBySubdomainAndDomain) {
 *   console.log(data.domainBySubdomainAndDomain);
 * }
 * ```
 */
export function useDomainBySubdomainAndDomainQuery(
  variables: DomainBySubdomainAndDomainQueryVariables,
  options?: Omit<
    UseQueryOptions<DomainBySubdomainAndDomainQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: domainBySubdomainAndDomainQueryKey(variables),
    queryFn: () =>
      execute<
        DomainBySubdomainAndDomainQueryResult,
        DomainBySubdomainAndDomainQueryVariables
      >(domainBySubdomainAndDomainQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch domainBySubdomainAndDomain without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchDomainBySubdomainAndDomainQuery({ subdomain, domain });
 * ```
 */
export async function fetchDomainBySubdomainAndDomainQuery(
  variables: DomainBySubdomainAndDomainQueryVariables,
  options?: ExecuteOptions
): Promise<DomainBySubdomainAndDomainQueryResult> {
  return execute<
    DomainBySubdomainAndDomainQueryResult,
    DomainBySubdomainAndDomainQueryVariables
  >(domainBySubdomainAndDomainQueryDocument, variables, options);
}

/**
 * Prefetch domainBySubdomainAndDomain for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDomainBySubdomainAndDomainQuery(queryClient, { subdomain, domain });
 * ```
 */
export async function prefetchDomainBySubdomainAndDomainQuery(
  queryClient: QueryClient,
  variables: DomainBySubdomainAndDomainQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: domainBySubdomainAndDomainQueryKey(variables),
    queryFn: () =>
      execute<
        DomainBySubdomainAndDomainQueryResult,
        DomainBySubdomainAndDomainQueryVariables
      >(domainBySubdomainAndDomainQueryDocument, variables, options),
  });
}
