/**
 * Single item query hook for Domain
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Domain } from '../types';

// Re-export entity type for convenience
export type { Domain };

// ============================================================================
// GraphQL Document
// ============================================================================
export const domainQueryDocument = `
query DomainQuery($id: UUID!) {
  domain(id: $id) {
    id
    databaseId
    apiId
    siteId
    subdomain
    domain
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface DomainQueryVariables {
  id: string;
}

export interface DomainQueryResult {
  domain: Domain | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const domainQueryKey = (id: string) => ['domain', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Domain by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDomainQuery('value-here');
 *
 * if (data?.domain) {
 *   console.log(data.domain.id);
 * }
 * ```
 */
export function useDomainQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<DomainQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: domainQueryKey(id),
    queryFn: () =>
      execute<DomainQueryResult, DomainQueryVariables>(domainQueryDocument, {
        id,
      }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Domain by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchDomainQuery('value-here');
 * ```
 */
export async function fetchDomainQuery(
  id: string,
  options?: ExecuteOptions
): Promise<DomainQueryResult> {
  return execute<DomainQueryResult, DomainQueryVariables>(
    domainQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Domain for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDomainQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchDomainQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: domainQueryKey(id),
    queryFn: () =>
      execute<DomainQueryResult, DomainQueryVariables>(
        domainQueryDocument,
        { id },
        options
      ),
  });
}
