/**
 * List query hook for DatabaseExtension
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type DatabaseExtension,
  type StringFilter,
  type UUIDFilter,
} from '../types';

// Re-export entity type for convenience
export type { DatabaseExtension };

// ============================================================================
// GraphQL Document
// ============================================================================
export const databaseExtensionsQueryDocument = `
query DatabaseExtensionsQuery($first: Int, $offset: Int, $filter: DatabaseExtensionFilter, $orderBy: [DatabaseExtensionsOrderBy!]) {
  databaseExtensions(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      name
      databaseId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface DatabaseExtensionFilter {
  name?: StringFilter;
  databaseId?: UUIDFilter;
  /** Logical AND */
  and?: DatabaseExtensionFilter[];
  /** Logical OR */
  or?: DatabaseExtensionFilter[];
  /** Logical NOT */
  not?: DatabaseExtensionFilter;
}

type DatabaseExtensionsOrderBy =
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface DatabaseExtensionsQueryVariables {
  first?: number;
  offset?: number;
  filter?: DatabaseExtensionFilter;
  orderBy?: DatabaseExtensionsOrderBy[];
}

export interface DatabaseExtensionsQueryResult {
  databaseExtensions: {
    totalCount: number;
    nodes: DatabaseExtension[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const databaseExtensionsQueryKey = (
  variables?: DatabaseExtensionsQueryVariables
) => ['databaseextension', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching DatabaseExtension list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDatabaseExtensionsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useDatabaseExtensionsQuery(
  variables?: DatabaseExtensionsQueryVariables,
  options?: Omit<
    UseQueryOptions<DatabaseExtensionsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: databaseExtensionsQueryKey(variables),
    queryFn: () =>
      execute<DatabaseExtensionsQueryResult, DatabaseExtensionsQueryVariables>(
        databaseExtensionsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch DatabaseExtension list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchDatabaseExtensionsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: databaseExtensionsQueryKey(variables),
 *   queryFn: () => fetchDatabaseExtensionsQuery(variables),
 * });
 * ```
 */
export async function fetchDatabaseExtensionsQuery(
  variables?: DatabaseExtensionsQueryVariables,
  options?: ExecuteOptions
): Promise<DatabaseExtensionsQueryResult> {
  return execute<
    DatabaseExtensionsQueryResult,
    DatabaseExtensionsQueryVariables
  >(databaseExtensionsQueryDocument, variables, options);
}

/**
 * Prefetch DatabaseExtension list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDatabaseExtensionsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchDatabaseExtensionsQuery(
  queryClient: QueryClient,
  variables?: DatabaseExtensionsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: databaseExtensionsQueryKey(variables),
    queryFn: () =>
      execute<DatabaseExtensionsQueryResult, DatabaseExtensionsQueryVariables>(
        databaseExtensionsQueryDocument,
        variables,
        options
      ),
  });
}
