/**
 * Single item query hook for DenormalizedTableField
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type DenormalizedTableField } from '../types';

// Re-export entity type for convenience
export type { DenormalizedTableField };

// ============================================================================
// GraphQL Document
// ============================================================================
export const denormalizedTableFieldQueryDocument = `
query DenormalizedTableFieldQuery($id: UUID!) {
  denormalizedTableField(id: $id) {
    id
    databaseId
    tableId
    fieldId
    setIds
    refTableId
    refFieldId
    refIds
    useUpdates
    updateDefaults
    funcName
    funcOrder
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface DenormalizedTableFieldQueryVariables {
  id: string;
}

export interface DenormalizedTableFieldQueryResult {
  denormalizedTableField: DenormalizedTableField | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const denormalizedTableFieldQueryKey = (id: string) =>
  ['denormalizedtablefield', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single DenormalizedTableField by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDenormalizedTableFieldQuery('value-here');
 *
 * if (data?.denormalizedTableField) {
 *   console.log(data.denormalizedTableField.id);
 * }
 * ```
 */
export function useDenormalizedTableFieldQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<DenormalizedTableFieldQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: denormalizedTableFieldQueryKey(id),
    queryFn: () =>
      execute<
        DenormalizedTableFieldQueryResult,
        DenormalizedTableFieldQueryVariables
      >(denormalizedTableFieldQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single DenormalizedTableField by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchDenormalizedTableFieldQuery('value-here');
 * ```
 */
export async function fetchDenormalizedTableFieldQuery(
  id: string,
  options?: ExecuteOptions
): Promise<DenormalizedTableFieldQueryResult> {
  return execute<
    DenormalizedTableFieldQueryResult,
    DenormalizedTableFieldQueryVariables
  >(denormalizedTableFieldQueryDocument, { id }, options);
}

/**
 * Prefetch a single DenormalizedTableField for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDenormalizedTableFieldQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchDenormalizedTableFieldQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: denormalizedTableFieldQueryKey(id),
    queryFn: () =>
      execute<
        DenormalizedTableFieldQueryResult,
        DenormalizedTableFieldQueryVariables
      >(denormalizedTableFieldQueryDocument, { id }, options),
  });
}
