/**
 * Single item query hook for DatabaseProvisionModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type DatabaseProvisionModule } from '../types';

// Re-export entity type for convenience
export type { DatabaseProvisionModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const databaseProvisionModuleQueryDocument = `
query DatabaseProvisionModuleQuery($id: UUID!) {
  databaseProvisionModule(id: $id) {
    id
    databaseName
    ownerId
    subdomain
    domain
    modules
    options
    bootstrapUser
    status
    errorMessage
    databaseId
    createdAt
    updatedAt
    completedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface DatabaseProvisionModuleQueryVariables {
  id: string;
}

export interface DatabaseProvisionModuleQueryResult {
  databaseProvisionModule: DatabaseProvisionModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const databaseProvisionModuleQueryKey = (id: string) =>
  ['databaseprovisionmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single DatabaseProvisionModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useDatabaseProvisionModuleQuery('value-here');
 *
 * if (data?.databaseProvisionModule) {
 *   console.log(data.databaseProvisionModule.id);
 * }
 * ```
 */
export function useDatabaseProvisionModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<DatabaseProvisionModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: databaseProvisionModuleQueryKey(id),
    queryFn: () =>
      execute<
        DatabaseProvisionModuleQueryResult,
        DatabaseProvisionModuleQueryVariables
      >(databaseProvisionModuleQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single DatabaseProvisionModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchDatabaseProvisionModuleQuery('value-here');
 * ```
 */
export async function fetchDatabaseProvisionModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<DatabaseProvisionModuleQueryResult> {
  return execute<
    DatabaseProvisionModuleQueryResult,
    DatabaseProvisionModuleQueryVariables
  >(databaseProvisionModuleQueryDocument, { id }, options);
}

/**
 * Prefetch a single DatabaseProvisionModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchDatabaseProvisionModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchDatabaseProvisionModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: databaseProvisionModuleQueryKey(id),
    queryFn: () =>
      execute<
        DatabaseProvisionModuleQueryResult,
        DatabaseProvisionModuleQueryVariables
      >(databaseProvisionModuleQueryDocument, { id }, options),
  });
}
