/**
 * List query hook for Email
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Email,
  type UUIDFilter,
  type StringFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Email };

// ============================================================================
// GraphQL Document
// ============================================================================
export const emailsQueryDocument = `
query EmailsQuery($first: Int, $offset: Int, $filter: EmailFilter, $orderBy: [EmailsOrderBy!]) {
  emails(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      ownerId
      email
      isVerified
      isPrimary
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface EmailFilter {
  id?: UUIDFilter;
  ownerId?: UUIDFilter;
  email?: StringFilter;
  isVerified?: BooleanFilter;
  isPrimary?: BooleanFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: EmailFilter[];
  /** Logical OR */
  or?: EmailFilter[];
  /** Logical NOT */
  not?: EmailFilter;
}

type EmailsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'OWNER_ID_ASC'
  | 'OWNER_ID_DESC'
  | 'EMAIL_ASC'
  | 'EMAIL_DESC'
  | 'IS_VERIFIED_ASC'
  | 'IS_VERIFIED_DESC'
  | 'IS_PRIMARY_ASC'
  | 'IS_PRIMARY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface EmailsQueryVariables {
  first?: number;
  offset?: number;
  filter?: EmailFilter;
  orderBy?: EmailsOrderBy[];
}

export interface EmailsQueryResult {
  emails: {
    totalCount: number;
    nodes: Email[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const emailsQueryKey = (variables?: EmailsQueryVariables) =>
  ['email', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Email list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useEmailsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useEmailsQuery(
  variables?: EmailsQueryVariables,
  options?: Omit<
    UseQueryOptions<EmailsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: emailsQueryKey(variables),
    queryFn: () =>
      execute<EmailsQueryResult, EmailsQueryVariables>(
        emailsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Email list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchEmailsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: emailsQueryKey(variables),
 *   queryFn: () => fetchEmailsQuery(variables),
 * });
 * ```
 */
export async function fetchEmailsQuery(
  variables?: EmailsQueryVariables,
  options?: ExecuteOptions
): Promise<EmailsQueryResult> {
  return execute<EmailsQueryResult, EmailsQueryVariables>(
    emailsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Email list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchEmailsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchEmailsQuery(
  queryClient: QueryClient,
  variables?: EmailsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: emailsQueryKey(variables),
    queryFn: () =>
      execute<EmailsQueryResult, EmailsQueryVariables>(
        emailsQueryDocument,
        variables,
        options
      ),
  });
}
