/**
 * List query hook for EmailsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type EmailsModule,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { EmailsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const emailsModulesQueryDocument = `
query EmailsModulesQuery($first: Int, $offset: Int, $filter: EmailsModuleFilter, $orderBy: [EmailsModulesOrderBy!]) {
  emailsModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      tableId
      ownerTableId
      tableName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface EmailsModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  ownerTableId?: UUIDFilter;
  tableName?: StringFilter;
  /** Logical AND */
  and?: EmailsModuleFilter[];
  /** Logical OR */
  or?: EmailsModuleFilter[];
  /** Logical NOT */
  not?: EmailsModuleFilter;
}

type EmailsModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'OWNER_TABLE_ID_ASC'
  | 'OWNER_TABLE_ID_DESC'
  | 'TABLE_NAME_ASC'
  | 'TABLE_NAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface EmailsModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: EmailsModuleFilter;
  orderBy?: EmailsModulesOrderBy[];
}

export interface EmailsModulesQueryResult {
  emailsModules: {
    totalCount: number;
    nodes: EmailsModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const emailsModulesQueryKey = (
  variables?: EmailsModulesQueryVariables
) => ['emailsmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching EmailsModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useEmailsModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useEmailsModulesQuery(
  variables?: EmailsModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<EmailsModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: emailsModulesQueryKey(variables),
    queryFn: () =>
      execute<EmailsModulesQueryResult, EmailsModulesQueryVariables>(
        emailsModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch EmailsModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchEmailsModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: emailsModulesQueryKey(variables),
 *   queryFn: () => fetchEmailsModulesQuery(variables),
 * });
 * ```
 */
export async function fetchEmailsModulesQuery(
  variables?: EmailsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<EmailsModulesQueryResult> {
  return execute<EmailsModulesQueryResult, EmailsModulesQueryVariables>(
    emailsModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch EmailsModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchEmailsModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchEmailsModulesQuery(
  queryClient: QueryClient,
  variables?: EmailsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: emailsModulesQueryKey(variables),
    queryFn: () =>
      execute<EmailsModulesQueryResult, EmailsModulesQueryVariables>(
        emailsModulesQueryDocument,
        variables,
        options
      ),
  });
}
