/**
 * Single item query hook for ForeignKeyConstraint
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ForeignKeyConstraint } from '../types';

// Re-export entity type for convenience
export type { ForeignKeyConstraint };

// ============================================================================
// GraphQL Document
// ============================================================================
export const foreignKeyConstraintQueryDocument = `
query ForeignKeyConstraintQuery($id: UUID!) {
  foreignKeyConstraint(id: $id) {
    id
    databaseId
    tableId
    name
    description
    smartTags
    type
    fieldIds
    refTableId
    refFieldIds
    deleteAction
    updateAction
    category
    module
    scope
    tags
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface ForeignKeyConstraintQueryVariables {
  id: string;
}

export interface ForeignKeyConstraintQueryResult {
  foreignKeyConstraint: ForeignKeyConstraint | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const foreignKeyConstraintQueryKey = (id: string) =>
  ['foreignkeyconstraint', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single ForeignKeyConstraint by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useForeignKeyConstraintQuery('value-here');
 *
 * if (data?.foreignKeyConstraint) {
 *   console.log(data.foreignKeyConstraint.id);
 * }
 * ```
 */
export function useForeignKeyConstraintQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<ForeignKeyConstraintQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: foreignKeyConstraintQueryKey(id),
    queryFn: () =>
      execute<
        ForeignKeyConstraintQueryResult,
        ForeignKeyConstraintQueryVariables
      >(foreignKeyConstraintQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single ForeignKeyConstraint by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchForeignKeyConstraintQuery('value-here');
 * ```
 */
export async function fetchForeignKeyConstraintQuery(
  id: string,
  options?: ExecuteOptions
): Promise<ForeignKeyConstraintQueryResult> {
  return execute<
    ForeignKeyConstraintQueryResult,
    ForeignKeyConstraintQueryVariables
  >(foreignKeyConstraintQueryDocument, { id }, options);
}

/**
 * Prefetch a single ForeignKeyConstraint for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchForeignKeyConstraintQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchForeignKeyConstraintQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: foreignKeyConstraintQueryKey(id),
    queryFn: () =>
      execute<
        ForeignKeyConstraintQueryResult,
        ForeignKeyConstraintQueryVariables
      >(foreignKeyConstraintQueryDocument, { id }, options),
  });
}
