/**
 * Custom query hook for getAll
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type GetAllConnection,
  type GetAllRecordFilter,
} from '../schema-types';

/** GraphQL query document */
export const getAllQueryDocument = `
query GetAllQuery($databaseId: UUID, $id: UUID, $first: Int, $last: Int, $offset: Int, $before: Cursor, $after: Cursor, $filter: GetAllRecordFilter) {
  getAll(
    databaseId: $databaseId
    id: $id
    first: $first
    last: $last
    offset: $offset
    before: $before
    after: $after
    filter: $filter
  ) {
    totalCount
    nodes {
      path
      data
    }
  }
}
`;

export interface GetAllQueryVariables {
  databaseId?: string;
  id?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /** Only read the last `n` values of the set. */
  last?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set before (above) this cursor. */
  before?: string;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
  /** A filter to be used in determining which values should be returned by the collection. */
  filter?: GetAllRecordFilter;
}

export interface GetAllQueryResult {
  getAll: GetAllConnection;
}

/** Query key factory for caching */
export const getAllQueryKey = (variables?: GetAllQueryVariables) =>
  ['getAll', variables] as const;

/**
 * Query hook for getAll
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useGetAllQuery({ databaseId, id, first, last, offset, before, after, filter });
 *
 * if (data?.getAll) {
 *   console.log(data.getAll);
 * }
 * ```
 */
export function useGetAllQuery(
  variables?: GetAllQueryVariables,
  options?: Omit<
    UseQueryOptions<GetAllQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: getAllQueryKey(variables),
    queryFn: () =>
      execute<GetAllQueryResult, GetAllQueryVariables>(
        getAllQueryDocument,
        variables
      ),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch getAll without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchGetAllQuery({ databaseId, id, first, last, offset, before, after, filter });
 * ```
 */
export async function fetchGetAllQuery(
  variables?: GetAllQueryVariables,
  options?: ExecuteOptions
): Promise<GetAllQueryResult> {
  return execute<GetAllQueryResult, GetAllQueryVariables>(
    getAllQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch getAll for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchGetAllQuery(queryClient, { databaseId, id, first, last, offset, before, after, filter });
 * ```
 */
export async function prefetchGetAllQuery(
  queryClient: QueryClient,
  variables?: GetAllQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: getAllQueryKey(variables),
    queryFn: () =>
      execute<GetAllQueryResult, GetAllQueryVariables>(
        getAllQueryDocument,
        variables,
        options
      ),
  });
}
