/**
 * Custom query hook for getPathObjectsFromRoot
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ObjectFilter, type ObjectsConnection } from '../schema-types';

/** GraphQL query document */
export const getPathObjectsFromRootQueryDocument = `
query GetPathObjectsFromRootQuery($databaseId: UUID, $id: UUID, $path: [String], $first: Int, $last: Int, $offset: Int, $before: Cursor, $after: Cursor, $filter: ObjectFilter) {
  getPathObjectsFromRoot(
    databaseId: $databaseId
    id: $id
    path: $path
    first: $first
    last: $last
    offset: $offset
    before: $before
    after: $after
    filter: $filter
  ) {
    totalCount
    nodes {
      id
      databaseId
      kids
      ktree
      data
      frzn
      createdAt
      hashUuid
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

export interface GetPathObjectsFromRootQueryVariables {
  databaseId?: string;
  id?: string;
  path?: string[];
  /** Only read the first `n` values of the set. */
  first?: number;
  /** Only read the last `n` values of the set. */
  last?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set before (above) this cursor. */
  before?: string;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
  /** A filter to be used in determining which values should be returned by the collection. */
  filter?: ObjectFilter;
}

export interface GetPathObjectsFromRootQueryResult {
  getPathObjectsFromRoot: ObjectsConnection;
}

/** Query key factory for caching */
export const getPathObjectsFromRootQueryKey = (
  variables?: GetPathObjectsFromRootQueryVariables
) => ['getPathObjectsFromRoot', variables] as const;

/**
 * Reads and enables pagination through a set of `Object`.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useGetPathObjectsFromRootQuery({ databaseId, id, path, first, last, offset, before, after, filter });
 *
 * if (data?.getPathObjectsFromRoot) {
 *   console.log(data.getPathObjectsFromRoot);
 * }
 * ```
 */
export function useGetPathObjectsFromRootQuery(
  variables?: GetPathObjectsFromRootQueryVariables,
  options?: Omit<
    UseQueryOptions<GetPathObjectsFromRootQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: getPathObjectsFromRootQueryKey(variables),
    queryFn: () =>
      execute<
        GetPathObjectsFromRootQueryResult,
        GetPathObjectsFromRootQueryVariables
      >(getPathObjectsFromRootQueryDocument, variables),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch getPathObjectsFromRoot without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchGetPathObjectsFromRootQuery({ databaseId, id, path, first, last, offset, before, after, filter });
 * ```
 */
export async function fetchGetPathObjectsFromRootQuery(
  variables?: GetPathObjectsFromRootQueryVariables,
  options?: ExecuteOptions
): Promise<GetPathObjectsFromRootQueryResult> {
  return execute<
    GetPathObjectsFromRootQueryResult,
    GetPathObjectsFromRootQueryVariables
  >(getPathObjectsFromRootQueryDocument, variables, options);
}

/**
 * Prefetch getPathObjectsFromRoot for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchGetPathObjectsFromRootQuery(queryClient, { databaseId, id, path, first, last, offset, before, after, filter });
 * ```
 */
export async function prefetchGetPathObjectsFromRootQuery(
  queryClient: QueryClient,
  variables?: GetPathObjectsFromRootQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: getPathObjectsFromRootQueryKey(variables),
    queryFn: () =>
      execute<
        GetPathObjectsFromRootQueryResult,
        GetPathObjectsFromRootQueryVariables
      >(getPathObjectsFromRootQueryDocument, variables, options),
  });
}
