/**
 * Custom query hook for getAllObjectsFromRoot
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ObjectFilter, type ObjectsConnection } from '../schema-types';

/** GraphQL query document */
export const getAllObjectsFromRootQueryDocument = `
query GetAllObjectsFromRootQuery($databaseId: UUID, $id: UUID, $first: Int, $last: Int, $offset: Int, $before: Cursor, $after: Cursor, $filter: ObjectFilter) {
  getAllObjectsFromRoot(
    databaseId: $databaseId
    id: $id
    first: $first
    last: $last
    offset: $offset
    before: $before
    after: $after
    filter: $filter
  ) {
    totalCount
    nodes {
      id
      databaseId
      kids
      ktree
      data
      frzn
      createdAt
      hashUuid
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

export interface GetAllObjectsFromRootQueryVariables {
  databaseId?: string;
  id?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /** Only read the last `n` values of the set. */
  last?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set before (above) this cursor. */
  before?: string;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
  /** A filter to be used in determining which values should be returned by the collection. */
  filter?: ObjectFilter;
}

export interface GetAllObjectsFromRootQueryResult {
  getAllObjectsFromRoot: ObjectsConnection;
}

/** Query key factory for caching */
export const getAllObjectsFromRootQueryKey = (
  variables?: GetAllObjectsFromRootQueryVariables
) => ['getAllObjectsFromRoot', variables] as const;

/**
 * Reads and enables pagination through a set of `Object`.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useGetAllObjectsFromRootQuery({ databaseId, id, first, last, offset, before, after, filter });
 *
 * if (data?.getAllObjectsFromRoot) {
 *   console.log(data.getAllObjectsFromRoot);
 * }
 * ```
 */
export function useGetAllObjectsFromRootQuery(
  variables?: GetAllObjectsFromRootQueryVariables,
  options?: Omit<
    UseQueryOptions<GetAllObjectsFromRootQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: getAllObjectsFromRootQueryKey(variables),
    queryFn: () =>
      execute<
        GetAllObjectsFromRootQueryResult,
        GetAllObjectsFromRootQueryVariables
      >(getAllObjectsFromRootQueryDocument, variables),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch getAllObjectsFromRoot without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchGetAllObjectsFromRootQuery({ databaseId, id, first, last, offset, before, after, filter });
 * ```
 */
export async function fetchGetAllObjectsFromRootQuery(
  variables?: GetAllObjectsFromRootQueryVariables,
  options?: ExecuteOptions
): Promise<GetAllObjectsFromRootQueryResult> {
  return execute<
    GetAllObjectsFromRootQueryResult,
    GetAllObjectsFromRootQueryVariables
  >(getAllObjectsFromRootQueryDocument, variables, options);
}

/**
 * Prefetch getAllObjectsFromRoot for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchGetAllObjectsFromRootQuery(queryClient, { databaseId, id, first, last, offset, before, after, filter });
 * ```
 */
export async function prefetchGetAllObjectsFromRootQuery(
  queryClient: QueryClient,
  variables?: GetAllObjectsFromRootQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: getAllObjectsFromRootQueryKey(variables),
    queryFn: () =>
      execute<
        GetAllObjectsFromRootQueryResult,
        GetAllObjectsFromRootQueryVariables
      >(getAllObjectsFromRootQueryDocument, variables, options),
  });
}
