/**
 * Single item query hook for InvitesModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type InvitesModule } from '../types';

// Re-export entity type for convenience
export type { InvitesModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const invitesModuleQueryDocument = `
query InvitesModuleQuery($id: UUID!) {
  invitesModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    emailsTableId
    usersTableId
    invitesTableId
    claimedInvitesTableId
    invitesTableName
    claimedInvitesTableName
    submitInviteCodeFunction
    prefix
    membershipType
    entityTableId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface InvitesModuleQueryVariables {
  id: string;
}

export interface InvitesModuleQueryResult {
  invitesModule: InvitesModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const invitesModuleQueryKey = (id: string) =>
  ['invitesmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single InvitesModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useInvitesModuleQuery('value-here');
 *
 * if (data?.invitesModule) {
 *   console.log(data.invitesModule.id);
 * }
 * ```
 */
export function useInvitesModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<InvitesModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: invitesModuleQueryKey(id),
    queryFn: () =>
      execute<InvitesModuleQueryResult, InvitesModuleQueryVariables>(
        invitesModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single InvitesModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchInvitesModuleQuery('value-here');
 * ```
 */
export async function fetchInvitesModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<InvitesModuleQueryResult> {
  return execute<InvitesModuleQueryResult, InvitesModuleQueryVariables>(
    invitesModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single InvitesModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchInvitesModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchInvitesModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: invitesModuleQueryKey(id),
    queryFn: () =>
      execute<InvitesModuleQueryResult, InvitesModuleQueryVariables>(
        invitesModuleQueryDocument,
        { id },
        options
      ),
  });
}
