/**
 * List query hook for LevelsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type LevelsModule,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
} from '../types';

// Re-export entity type for convenience
export type { LevelsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const levelsModulesQueryDocument = `
query LevelsModulesQuery($first: Int, $offset: Int, $filter: LevelsModuleFilter, $orderBy: [LevelsModulesOrderBy!]) {
  levelsModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      stepsTableId
      stepsTableName
      achievementsTableId
      achievementsTableName
      levelsTableId
      levelsTableName
      levelRequirementsTableId
      levelRequirementsTableName
      completedStep
      incompletedStep
      tgAchievement
      tgAchievementToggle
      tgAchievementToggleBoolean
      tgAchievementBoolean
      upsertAchievement
      tgUpdateAchievements
      stepsRequired
      levelAchieved
      prefix
      membershipType
      entityTableId
      actorTableId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface LevelsModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  stepsTableId?: UUIDFilter;
  stepsTableName?: StringFilter;
  achievementsTableId?: UUIDFilter;
  achievementsTableName?: StringFilter;
  levelsTableId?: UUIDFilter;
  levelsTableName?: StringFilter;
  levelRequirementsTableId?: UUIDFilter;
  levelRequirementsTableName?: StringFilter;
  completedStep?: StringFilter;
  incompletedStep?: StringFilter;
  tgAchievement?: StringFilter;
  tgAchievementToggle?: StringFilter;
  tgAchievementToggleBoolean?: StringFilter;
  tgAchievementBoolean?: StringFilter;
  upsertAchievement?: StringFilter;
  tgUpdateAchievements?: StringFilter;
  stepsRequired?: StringFilter;
  levelAchieved?: StringFilter;
  prefix?: StringFilter;
  membershipType?: IntFilter;
  entityTableId?: UUIDFilter;
  actorTableId?: UUIDFilter;
  /** Logical AND */
  and?: LevelsModuleFilter[];
  /** Logical OR */
  or?: LevelsModuleFilter[];
  /** Logical NOT */
  not?: LevelsModuleFilter;
}

type LevelsModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'STEPS_TABLE_ID_ASC'
  | 'STEPS_TABLE_ID_DESC'
  | 'STEPS_TABLE_NAME_ASC'
  | 'STEPS_TABLE_NAME_DESC'
  | 'ACHIEVEMENTS_TABLE_ID_ASC'
  | 'ACHIEVEMENTS_TABLE_ID_DESC'
  | 'ACHIEVEMENTS_TABLE_NAME_ASC'
  | 'ACHIEVEMENTS_TABLE_NAME_DESC'
  | 'LEVELS_TABLE_ID_ASC'
  | 'LEVELS_TABLE_ID_DESC'
  | 'LEVELS_TABLE_NAME_ASC'
  | 'LEVELS_TABLE_NAME_DESC'
  | 'LEVEL_REQUIREMENTS_TABLE_ID_ASC'
  | 'LEVEL_REQUIREMENTS_TABLE_ID_DESC'
  | 'LEVEL_REQUIREMENTS_TABLE_NAME_ASC'
  | 'LEVEL_REQUIREMENTS_TABLE_NAME_DESC'
  | 'COMPLETED_STEP_ASC'
  | 'COMPLETED_STEP_DESC'
  | 'INCOMPLETED_STEP_ASC'
  | 'INCOMPLETED_STEP_DESC'
  | 'TG_ACHIEVEMENT_ASC'
  | 'TG_ACHIEVEMENT_DESC'
  | 'TG_ACHIEVEMENT_TOGGLE_ASC'
  | 'TG_ACHIEVEMENT_TOGGLE_DESC'
  | 'TG_ACHIEVEMENT_TOGGLE_BOOLEAN_ASC'
  | 'TG_ACHIEVEMENT_TOGGLE_BOOLEAN_DESC'
  | 'TG_ACHIEVEMENT_BOOLEAN_ASC'
  | 'TG_ACHIEVEMENT_BOOLEAN_DESC'
  | 'UPSERT_ACHIEVEMENT_ASC'
  | 'UPSERT_ACHIEVEMENT_DESC'
  | 'TG_UPDATE_ACHIEVEMENTS_ASC'
  | 'TG_UPDATE_ACHIEVEMENTS_DESC'
  | 'STEPS_REQUIRED_ASC'
  | 'STEPS_REQUIRED_DESC'
  | 'LEVEL_ACHIEVED_ASC'
  | 'LEVEL_ACHIEVED_DESC'
  | 'PREFIX_ASC'
  | 'PREFIX_DESC'
  | 'MEMBERSHIP_TYPE_ASC'
  | 'MEMBERSHIP_TYPE_DESC'
  | 'ENTITY_TABLE_ID_ASC'
  | 'ENTITY_TABLE_ID_DESC'
  | 'ACTOR_TABLE_ID_ASC'
  | 'ACTOR_TABLE_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface LevelsModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: LevelsModuleFilter;
  orderBy?: LevelsModulesOrderBy[];
}

export interface LevelsModulesQueryResult {
  levelsModules: {
    totalCount: number;
    nodes: LevelsModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const levelsModulesQueryKey = (
  variables?: LevelsModulesQueryVariables
) => ['levelsmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching LevelsModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useLevelsModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useLevelsModulesQuery(
  variables?: LevelsModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<LevelsModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: levelsModulesQueryKey(variables),
    queryFn: () =>
      execute<LevelsModulesQueryResult, LevelsModulesQueryVariables>(
        levelsModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch LevelsModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchLevelsModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: levelsModulesQueryKey(variables),
 *   queryFn: () => fetchLevelsModulesQuery(variables),
 * });
 * ```
 */
export async function fetchLevelsModulesQuery(
  variables?: LevelsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<LevelsModulesQueryResult> {
  return execute<LevelsModulesQueryResult, LevelsModulesQueryVariables>(
    levelsModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch LevelsModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchLevelsModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchLevelsModulesQuery(
  queryClient: QueryClient,
  variables?: LevelsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: levelsModulesQueryKey(variables),
    queryFn: () =>
      execute<LevelsModulesQueryResult, LevelsModulesQueryVariables>(
        levelsModulesQueryDocument,
        variables,
        options
      ),
  });
}
