/**
 * Single item query hook for LevelsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type LevelsModule } from '../types';

// Re-export entity type for convenience
export type { LevelsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const levelsModuleQueryDocument = `
query LevelsModuleQuery($id: UUID!) {
  levelsModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    stepsTableId
    stepsTableName
    achievementsTableId
    achievementsTableName
    levelsTableId
    levelsTableName
    levelRequirementsTableId
    levelRequirementsTableName
    completedStep
    incompletedStep
    tgAchievement
    tgAchievementToggle
    tgAchievementToggleBoolean
    tgAchievementBoolean
    upsertAchievement
    tgUpdateAchievements
    stepsRequired
    levelAchieved
    prefix
    membershipType
    entityTableId
    actorTableId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface LevelsModuleQueryVariables {
  id: string;
}

export interface LevelsModuleQueryResult {
  levelsModule: LevelsModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const levelsModuleQueryKey = (id: string) =>
  ['levelsmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single LevelsModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useLevelsModuleQuery('value-here');
 *
 * if (data?.levelsModule) {
 *   console.log(data.levelsModule.id);
 * }
 * ```
 */
export function useLevelsModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<LevelsModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: levelsModuleQueryKey(id),
    queryFn: () =>
      execute<LevelsModuleQueryResult, LevelsModuleQueryVariables>(
        levelsModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single LevelsModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchLevelsModuleQuery('value-here');
 * ```
 */
export async function fetchLevelsModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<LevelsModuleQueryResult> {
  return execute<LevelsModuleQueryResult, LevelsModuleQueryVariables>(
    levelsModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single LevelsModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchLevelsModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchLevelsModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: levelsModuleQueryKey(id),
    queryFn: () =>
      execute<LevelsModuleQueryResult, LevelsModuleQueryVariables>(
        levelsModuleQueryDocument,
        { id },
        options
      ),
  });
}
