/**
 * Custom query hook for limitFunctionByDatabaseIdAndName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type LimitFunction } from '../types';

/** GraphQL query document */
export const limitFunctionByDatabaseIdAndNameQueryDocument = `
query LimitFunctionByDatabaseIdAndNameQuery($databaseId: UUID!, $name: String!) {
  limitFunctionByDatabaseIdAndName(databaseId: $databaseId, name: $name) {
    id
    databaseId
    tableId
    name
    label
    description
    data
    security
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    table {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
  }
}
`;

export interface LimitFunctionByDatabaseIdAndNameQueryVariables {
  databaseId: string;
  name: string;
}

export interface LimitFunctionByDatabaseIdAndNameQueryResult {
  limitFunctionByDatabaseIdAndName: LimitFunction;
}

/** Query key factory for caching */
export const limitFunctionByDatabaseIdAndNameQueryKey = (
  variables?: LimitFunctionByDatabaseIdAndNameQueryVariables
) => ['limitFunctionByDatabaseIdAndName', variables] as const;

/**
 * Query hook for limitFunctionByDatabaseIdAndName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useLimitFunctionByDatabaseIdAndNameQuery({ databaseId, name });
 *
 * if (data?.limitFunctionByDatabaseIdAndName) {
 *   console.log(data.limitFunctionByDatabaseIdAndName);
 * }
 * ```
 */
export function useLimitFunctionByDatabaseIdAndNameQuery(
  variables: LimitFunctionByDatabaseIdAndNameQueryVariables,
  options?: Omit<
    UseQueryOptions<LimitFunctionByDatabaseIdAndNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: limitFunctionByDatabaseIdAndNameQueryKey(variables),
    queryFn: () =>
      execute<
        LimitFunctionByDatabaseIdAndNameQueryResult,
        LimitFunctionByDatabaseIdAndNameQueryVariables
      >(limitFunctionByDatabaseIdAndNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch limitFunctionByDatabaseIdAndName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchLimitFunctionByDatabaseIdAndNameQuery({ databaseId, name });
 * ```
 */
export async function fetchLimitFunctionByDatabaseIdAndNameQuery(
  variables: LimitFunctionByDatabaseIdAndNameQueryVariables,
  options?: ExecuteOptions
): Promise<LimitFunctionByDatabaseIdAndNameQueryResult> {
  return execute<
    LimitFunctionByDatabaseIdAndNameQueryResult,
    LimitFunctionByDatabaseIdAndNameQueryVariables
  >(limitFunctionByDatabaseIdAndNameQueryDocument, variables, options);
}

/**
 * Prefetch limitFunctionByDatabaseIdAndName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchLimitFunctionByDatabaseIdAndNameQuery(queryClient, { databaseId, name });
 * ```
 */
export async function prefetchLimitFunctionByDatabaseIdAndNameQuery(
  queryClient: QueryClient,
  variables: LimitFunctionByDatabaseIdAndNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: limitFunctionByDatabaseIdAndNameQueryKey(variables),
    queryFn: () =>
      execute<
        LimitFunctionByDatabaseIdAndNameQueryResult,
        LimitFunctionByDatabaseIdAndNameQueryVariables
      >(limitFunctionByDatabaseIdAndNameQueryDocument, variables, options),
  });
}
