/**
 * List query hook for LimitFunction
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type LimitFunction,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type IntFilter,
} from '../types';

// Re-export entity type for convenience
export type { LimitFunction };

// ============================================================================
// GraphQL Document
// ============================================================================
export const limitFunctionsQueryDocument = `
query LimitFunctionsQuery($first: Int, $offset: Int, $filter: LimitFunctionFilter, $orderBy: [LimitFunctionsOrderBy!]) {
  limitFunctions(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      tableId
      name
      label
      description
      data
      security
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface LimitFunctionFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  tableId?: UUIDFilter;
  name?: StringFilter;
  label?: StringFilter;
  description?: StringFilter;
  data?: JSONFilter;
  security?: IntFilter;
  /** Logical AND */
  and?: LimitFunctionFilter[];
  /** Logical OR */
  or?: LimitFunctionFilter[];
  /** Logical NOT */
  not?: LimitFunctionFilter;
}

type LimitFunctionsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'LABEL_ASC'
  | 'LABEL_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'DATA_ASC'
  | 'DATA_DESC'
  | 'SECURITY_ASC'
  | 'SECURITY_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface LimitFunctionsQueryVariables {
  first?: number;
  offset?: number;
  filter?: LimitFunctionFilter;
  orderBy?: LimitFunctionsOrderBy[];
}

export interface LimitFunctionsQueryResult {
  limitFunctions: {
    totalCount: number;
    nodes: LimitFunction[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const limitFunctionsQueryKey = (
  variables?: LimitFunctionsQueryVariables
) => ['limitfunction', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching LimitFunction list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useLimitFunctionsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useLimitFunctionsQuery(
  variables?: LimitFunctionsQueryVariables,
  options?: Omit<
    UseQueryOptions<LimitFunctionsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: limitFunctionsQueryKey(variables),
    queryFn: () =>
      execute<LimitFunctionsQueryResult, LimitFunctionsQueryVariables>(
        limitFunctionsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch LimitFunction list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchLimitFunctionsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: limitFunctionsQueryKey(variables),
 *   queryFn: () => fetchLimitFunctionsQuery(variables),
 * });
 * ```
 */
export async function fetchLimitFunctionsQuery(
  variables?: LimitFunctionsQueryVariables,
  options?: ExecuteOptions
): Promise<LimitFunctionsQueryResult> {
  return execute<LimitFunctionsQueryResult, LimitFunctionsQueryVariables>(
    limitFunctionsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch LimitFunction list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchLimitFunctionsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchLimitFunctionsQuery(
  queryClient: QueryClient,
  variables?: LimitFunctionsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: limitFunctionsQueryKey(variables),
    queryFn: () =>
      execute<LimitFunctionsQueryResult, LimitFunctionsQueryVariables>(
        limitFunctionsQueryDocument,
        variables,
        options
      ),
  });
}
