/**
 * List query hook for MembershipsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type MembershipsModule,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
  type BooleanFilter,
} from '../types';

// Re-export entity type for convenience
export type { MembershipsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const membershipsModulesQueryDocument = `
query MembershipsModulesQuery($first: Int, $offset: Int, $filter: MembershipsModuleFilter, $orderBy: [MembershipsModulesOrderBy!]) {
  membershipsModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      membershipsTableId
      membershipsTableName
      membersTableId
      membersTableName
      membershipDefaultsTableId
      membershipDefaultsTableName
      grantsTableId
      grantsTableName
      actorTableId
      limitsTableId
      defaultLimitsTableId
      permissionsTableId
      defaultPermissionsTableId
      sprtTableId
      adminGrantsTableId
      adminGrantsTableName
      ownerGrantsTableId
      ownerGrantsTableName
      membershipType
      entityTableId
      entityTableOwnerId
      prefix
      actorMaskCheck
      actorPermCheck
      entityIdsByMask
      entityIdsByPerm
      entityIdsFunction
      defaultIsApproved
      defaultIsVerified
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface MembershipsModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  membershipsTableId?: UUIDFilter;
  membershipsTableName?: StringFilter;
  membersTableId?: UUIDFilter;
  membersTableName?: StringFilter;
  membershipDefaultsTableId?: UUIDFilter;
  membershipDefaultsTableName?: StringFilter;
  grantsTableId?: UUIDFilter;
  grantsTableName?: StringFilter;
  actorTableId?: UUIDFilter;
  limitsTableId?: UUIDFilter;
  defaultLimitsTableId?: UUIDFilter;
  permissionsTableId?: UUIDFilter;
  defaultPermissionsTableId?: UUIDFilter;
  sprtTableId?: UUIDFilter;
  adminGrantsTableId?: UUIDFilter;
  adminGrantsTableName?: StringFilter;
  ownerGrantsTableId?: UUIDFilter;
  ownerGrantsTableName?: StringFilter;
  membershipType?: IntFilter;
  entityTableId?: UUIDFilter;
  entityTableOwnerId?: UUIDFilter;
  prefix?: StringFilter;
  actorMaskCheck?: StringFilter;
  actorPermCheck?: StringFilter;
  entityIdsByMask?: StringFilter;
  entityIdsByPerm?: StringFilter;
  entityIdsFunction?: StringFilter;
  defaultIsApproved?: BooleanFilter;
  defaultIsVerified?: BooleanFilter;
  /** Logical AND */
  and?: MembershipsModuleFilter[];
  /** Logical OR */
  or?: MembershipsModuleFilter[];
  /** Logical NOT */
  not?: MembershipsModuleFilter;
}

type MembershipsModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'MEMBERSHIPS_TABLE_ID_ASC'
  | 'MEMBERSHIPS_TABLE_ID_DESC'
  | 'MEMBERSHIPS_TABLE_NAME_ASC'
  | 'MEMBERSHIPS_TABLE_NAME_DESC'
  | 'MEMBERS_TABLE_ID_ASC'
  | 'MEMBERS_TABLE_ID_DESC'
  | 'MEMBERS_TABLE_NAME_ASC'
  | 'MEMBERS_TABLE_NAME_DESC'
  | 'MEMBERSHIP_DEFAULTS_TABLE_ID_ASC'
  | 'MEMBERSHIP_DEFAULTS_TABLE_ID_DESC'
  | 'MEMBERSHIP_DEFAULTS_TABLE_NAME_ASC'
  | 'MEMBERSHIP_DEFAULTS_TABLE_NAME_DESC'
  | 'GRANTS_TABLE_ID_ASC'
  | 'GRANTS_TABLE_ID_DESC'
  | 'GRANTS_TABLE_NAME_ASC'
  | 'GRANTS_TABLE_NAME_DESC'
  | 'ACTOR_TABLE_ID_ASC'
  | 'ACTOR_TABLE_ID_DESC'
  | 'LIMITS_TABLE_ID_ASC'
  | 'LIMITS_TABLE_ID_DESC'
  | 'DEFAULT_LIMITS_TABLE_ID_ASC'
  | 'DEFAULT_LIMITS_TABLE_ID_DESC'
  | 'PERMISSIONS_TABLE_ID_ASC'
  | 'PERMISSIONS_TABLE_ID_DESC'
  | 'DEFAULT_PERMISSIONS_TABLE_ID_ASC'
  | 'DEFAULT_PERMISSIONS_TABLE_ID_DESC'
  | 'SPRT_TABLE_ID_ASC'
  | 'SPRT_TABLE_ID_DESC'
  | 'ADMIN_GRANTS_TABLE_ID_ASC'
  | 'ADMIN_GRANTS_TABLE_ID_DESC'
  | 'ADMIN_GRANTS_TABLE_NAME_ASC'
  | 'ADMIN_GRANTS_TABLE_NAME_DESC'
  | 'OWNER_GRANTS_TABLE_ID_ASC'
  | 'OWNER_GRANTS_TABLE_ID_DESC'
  | 'OWNER_GRANTS_TABLE_NAME_ASC'
  | 'OWNER_GRANTS_TABLE_NAME_DESC'
  | 'MEMBERSHIP_TYPE_ASC'
  | 'MEMBERSHIP_TYPE_DESC'
  | 'ENTITY_TABLE_ID_ASC'
  | 'ENTITY_TABLE_ID_DESC'
  | 'ENTITY_TABLE_OWNER_ID_ASC'
  | 'ENTITY_TABLE_OWNER_ID_DESC'
  | 'PREFIX_ASC'
  | 'PREFIX_DESC'
  | 'ACTOR_MASK_CHECK_ASC'
  | 'ACTOR_MASK_CHECK_DESC'
  | 'ACTOR_PERM_CHECK_ASC'
  | 'ACTOR_PERM_CHECK_DESC'
  | 'ENTITY_IDS_BY_MASK_ASC'
  | 'ENTITY_IDS_BY_MASK_DESC'
  | 'ENTITY_IDS_BY_PERM_ASC'
  | 'ENTITY_IDS_BY_PERM_DESC'
  | 'ENTITY_IDS_FUNCTION_ASC'
  | 'ENTITY_IDS_FUNCTION_DESC'
  | 'DEFAULT_IS_APPROVED_ASC'
  | 'DEFAULT_IS_APPROVED_DESC'
  | 'DEFAULT_IS_VERIFIED_ASC'
  | 'DEFAULT_IS_VERIFIED_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface MembershipsModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: MembershipsModuleFilter;
  orderBy?: MembershipsModulesOrderBy[];
}

export interface MembershipsModulesQueryResult {
  membershipsModules: {
    totalCount: number;
    nodes: MembershipsModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const membershipsModulesQueryKey = (
  variables?: MembershipsModulesQueryVariables
) => ['membershipsmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching MembershipsModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMembershipsModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useMembershipsModulesQuery(
  variables?: MembershipsModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<MembershipsModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: membershipsModulesQueryKey(variables),
    queryFn: () =>
      execute<MembershipsModulesQueryResult, MembershipsModulesQueryVariables>(
        membershipsModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch MembershipsModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchMembershipsModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: membershipsModulesQueryKey(variables),
 *   queryFn: () => fetchMembershipsModulesQuery(variables),
 * });
 * ```
 */
export async function fetchMembershipsModulesQuery(
  variables?: MembershipsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<MembershipsModulesQueryResult> {
  return execute<
    MembershipsModulesQueryResult,
    MembershipsModulesQueryVariables
  >(membershipsModulesQueryDocument, variables, options);
}

/**
 * Prefetch MembershipsModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchMembershipsModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchMembershipsModulesQuery(
  queryClient: QueryClient,
  variables?: MembershipsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: membershipsModulesQueryKey(variables),
    queryFn: () =>
      execute<MembershipsModulesQueryResult, MembershipsModulesQueryVariables>(
        membershipsModulesQueryDocument,
        variables,
        options
      ),
  });
}
