/**
 * Custom query hook for membershipTypeByName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type MembershipType } from '../types';

/** GraphQL query document */
export const membershipTypeByNameQueryDocument = `
query MembershipTypeByNameQuery($name: String!) {
  membershipTypeByName(name: $name) {
    id
    name
    description
    prefix
  }
}
`;

export interface MembershipTypeByNameQueryVariables {
  name: string;
}

export interface MembershipTypeByNameQueryResult {
  membershipTypeByName: MembershipType;
}

/** Query key factory for caching */
export const membershipTypeByNameQueryKey = (
  variables?: MembershipTypeByNameQueryVariables
) => ['membershipTypeByName', variables] as const;

/**
 * Query hook for membershipTypeByName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMembershipTypeByNameQuery({ name });
 *
 * if (data?.membershipTypeByName) {
 *   console.log(data.membershipTypeByName);
 * }
 * ```
 */
export function useMembershipTypeByNameQuery(
  variables: MembershipTypeByNameQueryVariables,
  options?: Omit<
    UseQueryOptions<MembershipTypeByNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: membershipTypeByNameQueryKey(variables),
    queryFn: () =>
      execute<
        MembershipTypeByNameQueryResult,
        MembershipTypeByNameQueryVariables
      >(membershipTypeByNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch membershipTypeByName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchMembershipTypeByNameQuery({ name });
 * ```
 */
export async function fetchMembershipTypeByNameQuery(
  variables: MembershipTypeByNameQueryVariables,
  options?: ExecuteOptions
): Promise<MembershipTypeByNameQueryResult> {
  return execute<
    MembershipTypeByNameQueryResult,
    MembershipTypeByNameQueryVariables
  >(membershipTypeByNameQueryDocument, variables, options);
}

/**
 * Prefetch membershipTypeByName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchMembershipTypeByNameQuery(queryClient, { name });
 * ```
 */
export async function prefetchMembershipTypeByNameQuery(
  queryClient: QueryClient,
  variables: MembershipTypeByNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: membershipTypeByNameQueryKey(variables),
    queryFn: () =>
      execute<
        MembershipTypeByNameQueryResult,
        MembershipTypeByNameQueryVariables
      >(membershipTypeByNameQueryDocument, variables, options),
  });
}
