/**
 * Single item query hook for OrgAdminGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgAdminGrant } from '../types';

// Re-export entity type for convenience
export type { OrgAdminGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgAdminGrantQueryDocument = `
query OrgAdminGrantQuery($id: UUID!) {
  orgAdminGrant(id: $id) {
    id
    isGrant
    actorId
    entityId
    grantorId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgAdminGrantQueryVariables {
  id: string;
}

export interface OrgAdminGrantQueryResult {
  orgAdminGrant: OrgAdminGrant | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgAdminGrantQueryKey = (id: string) =>
  ['orgadmingrant', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgAdminGrant by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgAdminGrantQuery('value-here');
 *
 * if (data?.orgAdminGrant) {
 *   console.log(data.orgAdminGrant.id);
 * }
 * ```
 */
export function useOrgAdminGrantQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgAdminGrantQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgAdminGrantQueryKey(id),
    queryFn: () =>
      execute<OrgAdminGrantQueryResult, OrgAdminGrantQueryVariables>(
        orgAdminGrantQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgAdminGrant by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgAdminGrantQuery('value-here');
 * ```
 */
export async function fetchOrgAdminGrantQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgAdminGrantQueryResult> {
  return execute<OrgAdminGrantQueryResult, OrgAdminGrantQueryVariables>(
    orgAdminGrantQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single OrgAdminGrant for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgAdminGrantQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgAdminGrantQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgAdminGrantQueryKey(id),
    queryFn: () =>
      execute<OrgAdminGrantQueryResult, OrgAdminGrantQueryVariables>(
        orgAdminGrantQueryDocument,
        { id },
        options
      ),
  });
}
