/**
 * Single item query hook for OrgClaimedInvite
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgClaimedInvite } from '../types';

// Re-export entity type for convenience
export type { OrgClaimedInvite };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgClaimedInviteQueryDocument = `
query OrgClaimedInviteQuery($id: UUID!) {
  orgClaimedInvite(id: $id) {
    id
    data
    senderId
    receiverId
    createdAt
    updatedAt
    entityId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgClaimedInviteQueryVariables {
  id: string;
}

export interface OrgClaimedInviteQueryResult {
  orgClaimedInvite: OrgClaimedInvite | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgClaimedInviteQueryKey = (id: string) =>
  ['orgclaimedinvite', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgClaimedInvite by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgClaimedInviteQuery('value-here');
 *
 * if (data?.orgClaimedInvite) {
 *   console.log(data.orgClaimedInvite.id);
 * }
 * ```
 */
export function useOrgClaimedInviteQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgClaimedInviteQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgClaimedInviteQueryKey(id),
    queryFn: () =>
      execute<OrgClaimedInviteQueryResult, OrgClaimedInviteQueryVariables>(
        orgClaimedInviteQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgClaimedInvite by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgClaimedInviteQuery('value-here');
 * ```
 */
export async function fetchOrgClaimedInviteQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgClaimedInviteQueryResult> {
  return execute<OrgClaimedInviteQueryResult, OrgClaimedInviteQueryVariables>(
    orgClaimedInviteQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single OrgClaimedInvite for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgClaimedInviteQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgClaimedInviteQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgClaimedInviteQueryKey(id),
    queryFn: () =>
      execute<OrgClaimedInviteQueryResult, OrgClaimedInviteQueryVariables>(
        orgClaimedInviteQueryDocument,
        { id },
        options
      ),
  });
}
