/**
 * List query hook for OrgMembershipDefault
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type OrgMembershipDefault,
  type UUIDFilter,
  type DatetimeFilter,
  type BooleanFilter,
} from '../types';

// Re-export entity type for convenience
export type { OrgMembershipDefault };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgMembershipDefaultsQueryDocument = `
query OrgMembershipDefaultsQuery($first: Int, $offset: Int, $filter: OrgMembershipDefaultFilter, $orderBy: [OrgMembershipDefaultsOrderBy!]) {
  orgMembershipDefaults(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      createdAt
      updatedAt
      createdBy
      updatedBy
      isApproved
      entityId
      deleteMemberCascadeGroups
      createGroupsCascadeMembers
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface OrgMembershipDefaultFilter {
  id?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  createdBy?: UUIDFilter;
  updatedBy?: UUIDFilter;
  isApproved?: BooleanFilter;
  entityId?: UUIDFilter;
  deleteMemberCascadeGroups?: BooleanFilter;
  createGroupsCascadeMembers?: BooleanFilter;
  /** Logical AND */
  and?: OrgMembershipDefaultFilter[];
  /** Logical OR */
  or?: OrgMembershipDefaultFilter[];
  /** Logical NOT */
  not?: OrgMembershipDefaultFilter;
}

type OrgMembershipDefaultsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'CREATED_BY_ASC'
  | 'CREATED_BY_DESC'
  | 'UPDATED_BY_ASC'
  | 'UPDATED_BY_DESC'
  | 'IS_APPROVED_ASC'
  | 'IS_APPROVED_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'DELETE_MEMBER_CASCADE_GROUPS_ASC'
  | 'DELETE_MEMBER_CASCADE_GROUPS_DESC'
  | 'CREATE_GROUPS_CASCADE_MEMBERS_ASC'
  | 'CREATE_GROUPS_CASCADE_MEMBERS_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface OrgMembershipDefaultsQueryVariables {
  first?: number;
  offset?: number;
  filter?: OrgMembershipDefaultFilter;
  orderBy?: OrgMembershipDefaultsOrderBy[];
}

export interface OrgMembershipDefaultsQueryResult {
  orgMembershipDefaults: {
    totalCount: number;
    nodes: OrgMembershipDefault[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const orgMembershipDefaultsQueryKey = (
  variables?: OrgMembershipDefaultsQueryVariables
) => ['orgmembershipdefault', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching OrgMembershipDefault list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipDefaultsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useOrgMembershipDefaultsQuery(
  variables?: OrgMembershipDefaultsQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgMembershipDefaultsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgMembershipDefaultsQueryKey(variables),
    queryFn: () =>
      execute<
        OrgMembershipDefaultsQueryResult,
        OrgMembershipDefaultsQueryVariables
      >(orgMembershipDefaultsQueryDocument, variables),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch OrgMembershipDefault list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchOrgMembershipDefaultsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: orgMembershipDefaultsQueryKey(variables),
 *   queryFn: () => fetchOrgMembershipDefaultsQuery(variables),
 * });
 * ```
 */
export async function fetchOrgMembershipDefaultsQuery(
  variables?: OrgMembershipDefaultsQueryVariables,
  options?: ExecuteOptions
): Promise<OrgMembershipDefaultsQueryResult> {
  return execute<
    OrgMembershipDefaultsQueryResult,
    OrgMembershipDefaultsQueryVariables
  >(orgMembershipDefaultsQueryDocument, variables, options);
}

/**
 * Prefetch OrgMembershipDefault list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipDefaultsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchOrgMembershipDefaultsQuery(
  queryClient: QueryClient,
  variables?: OrgMembershipDefaultsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgMembershipDefaultsQueryKey(variables),
    queryFn: () =>
      execute<
        OrgMembershipDefaultsQueryResult,
        OrgMembershipDefaultsQueryVariables
      >(orgMembershipDefaultsQueryDocument, variables, options),
  });
}
