/**
 * List query hook for OrgOwnerGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type OrgOwnerGrant,
  type UUIDFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { OrgOwnerGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgOwnerGrantsQueryDocument = `
query OrgOwnerGrantsQuery($first: Int, $offset: Int, $filter: OrgOwnerGrantFilter, $orderBy: [OrgOwnerGrantsOrderBy!]) {
  orgOwnerGrants(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      isGrant
      actorId
      entityId
      grantorId
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface OrgOwnerGrantFilter {
  id?: UUIDFilter;
  isGrant?: BooleanFilter;
  actorId?: UUIDFilter;
  entityId?: UUIDFilter;
  grantorId?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: OrgOwnerGrantFilter[];
  /** Logical OR */
  or?: OrgOwnerGrantFilter[];
  /** Logical NOT */
  not?: OrgOwnerGrantFilter;
}

type OrgOwnerGrantsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_GRANT_ASC'
  | 'IS_GRANT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'GRANTOR_ID_ASC'
  | 'GRANTOR_ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface OrgOwnerGrantsQueryVariables {
  first?: number;
  offset?: number;
  filter?: OrgOwnerGrantFilter;
  orderBy?: OrgOwnerGrantsOrderBy[];
}

export interface OrgOwnerGrantsQueryResult {
  orgOwnerGrants: {
    totalCount: number;
    nodes: OrgOwnerGrant[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const orgOwnerGrantsQueryKey = (
  variables?: OrgOwnerGrantsQueryVariables
) => ['orgownergrant', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching OrgOwnerGrant list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgOwnerGrantsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useOrgOwnerGrantsQuery(
  variables?: OrgOwnerGrantsQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgOwnerGrantsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgOwnerGrantsQueryKey(variables),
    queryFn: () =>
      execute<OrgOwnerGrantsQueryResult, OrgOwnerGrantsQueryVariables>(
        orgOwnerGrantsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch OrgOwnerGrant list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchOrgOwnerGrantsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: orgOwnerGrantsQueryKey(variables),
 *   queryFn: () => fetchOrgOwnerGrantsQuery(variables),
 * });
 * ```
 */
export async function fetchOrgOwnerGrantsQuery(
  variables?: OrgOwnerGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<OrgOwnerGrantsQueryResult> {
  return execute<OrgOwnerGrantsQueryResult, OrgOwnerGrantsQueryVariables>(
    orgOwnerGrantsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch OrgOwnerGrant list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgOwnerGrantsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchOrgOwnerGrantsQuery(
  queryClient: QueryClient,
  variables?: OrgOwnerGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgOwnerGrantsQueryKey(variables),
    queryFn: () =>
      execute<OrgOwnerGrantsQueryResult, OrgOwnerGrantsQueryVariables>(
        orgOwnerGrantsQueryDocument,
        variables,
        options
      ),
  });
}
