/**
 * List query hook for OrgLimit
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type OrgLimit,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
} from '../types';

// Re-export entity type for convenience
export type { OrgLimit };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgLimitsQueryDocument = `
query OrgLimitsQuery($first: Int, $offset: Int, $filter: OrgLimitFilter, $orderBy: [OrgLimitsOrderBy!]) {
  orgLimits(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      name
      actorId
      num
      max
      entityId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface OrgLimitFilter {
  id?: UUIDFilter;
  name?: StringFilter;
  actorId?: UUIDFilter;
  num?: IntFilter;
  max?: IntFilter;
  entityId?: UUIDFilter;
  /** Logical AND */
  and?: OrgLimitFilter[];
  /** Logical OR */
  or?: OrgLimitFilter[];
  /** Logical NOT */
  not?: OrgLimitFilter;
}

type OrgLimitsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'NUM_ASC'
  | 'NUM_DESC'
  | 'MAX_ASC'
  | 'MAX_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface OrgLimitsQueryVariables {
  first?: number;
  offset?: number;
  filter?: OrgLimitFilter;
  orderBy?: OrgLimitsOrderBy[];
}

export interface OrgLimitsQueryResult {
  orgLimits: {
    totalCount: number;
    nodes: OrgLimit[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const orgLimitsQueryKey = (variables?: OrgLimitsQueryVariables) =>
  ['orglimit', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching OrgLimit list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useOrgLimitsQuery(
  variables?: OrgLimitsQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgLimitsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgLimitsQueryKey(variables),
    queryFn: () =>
      execute<OrgLimitsQueryResult, OrgLimitsQueryVariables>(
        orgLimitsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch OrgLimit list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchOrgLimitsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: orgLimitsQueryKey(variables),
 *   queryFn: () => fetchOrgLimitsQuery(variables),
 * });
 * ```
 */
export async function fetchOrgLimitsQuery(
  variables?: OrgLimitsQueryVariables,
  options?: ExecuteOptions
): Promise<OrgLimitsQueryResult> {
  return execute<OrgLimitsQueryResult, OrgLimitsQueryVariables>(
    orgLimitsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch OrgLimit list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgLimitsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchOrgLimitsQuery(
  queryClient: QueryClient,
  variables?: OrgLimitsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgLimitsQueryKey(variables),
    queryFn: () =>
      execute<OrgLimitsQueryResult, OrgLimitsQueryVariables>(
        orgLimitsQueryDocument,
        variables,
        options
      ),
  });
}
