/**
 * Single item query hook for OrgGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgGrant } from '../types';

// Re-export entity type for convenience
export type { OrgGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgGrantQueryDocument = `
query OrgGrantQuery($id: UUID!) {
  orgGrant(id: $id) {
    id
    permissions
    isGrant
    actorId
    entityId
    grantorId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgGrantQueryVariables {
  id: string;
}

export interface OrgGrantQueryResult {
  orgGrant: OrgGrant | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgGrantQueryKey = (id: string) =>
  ['orggrant', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgGrant by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgGrantQuery('value-here');
 *
 * if (data?.orgGrant) {
 *   console.log(data.orgGrant.id);
 * }
 * ```
 */
export function useOrgGrantQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgGrantQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgGrantQueryKey(id),
    queryFn: () =>
      execute<OrgGrantQueryResult, OrgGrantQueryVariables>(
        orgGrantQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgGrant by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgGrantQuery('value-here');
 * ```
 */
export async function fetchOrgGrantQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgGrantQueryResult> {
  return execute<OrgGrantQueryResult, OrgGrantQueryVariables>(
    orgGrantQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single OrgGrant for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgGrantQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgGrantQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgGrantQueryKey(id),
    queryFn: () =>
      execute<OrgGrantQueryResult, OrgGrantQueryVariables>(
        orgGrantQueryDocument,
        { id },
        options
      ),
  });
}
