/**
 * Custom query hook for orgPermissionByName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgPermission } from '../types';

/** GraphQL query document */
export const orgPermissionByNameQueryDocument = `
query OrgPermissionByNameQuery($name: String!) {
  orgPermissionByName(name: $name) {
    id
    name
    bitnum
    bitstr
    description
  }
}
`;

export interface OrgPermissionByNameQueryVariables {
  name: string;
}

export interface OrgPermissionByNameQueryResult {
  orgPermissionByName: OrgPermission;
}

/** Query key factory for caching */
export const orgPermissionByNameQueryKey = (
  variables?: OrgPermissionByNameQueryVariables
) => ['orgPermissionByName', variables] as const;

/**
 * Query hook for orgPermissionByName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgPermissionByNameQuery({ name });
 *
 * if (data?.orgPermissionByName) {
 *   console.log(data.orgPermissionByName);
 * }
 * ```
 */
export function useOrgPermissionByNameQuery(
  variables: OrgPermissionByNameQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgPermissionByNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgPermissionByNameQueryKey(variables),
    queryFn: () =>
      execute<
        OrgPermissionByNameQueryResult,
        OrgPermissionByNameQueryVariables
      >(orgPermissionByNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch orgPermissionByName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgPermissionByNameQuery({ name });
 * ```
 */
export async function fetchOrgPermissionByNameQuery(
  variables: OrgPermissionByNameQueryVariables,
  options?: ExecuteOptions
): Promise<OrgPermissionByNameQueryResult> {
  return execute<
    OrgPermissionByNameQueryResult,
    OrgPermissionByNameQueryVariables
  >(orgPermissionByNameQueryDocument, variables, options);
}

/**
 * Prefetch orgPermissionByName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgPermissionByNameQuery(queryClient, { name });
 * ```
 */
export async function prefetchOrgPermissionByNameQuery(
  queryClient: QueryClient,
  variables: OrgPermissionByNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgPermissionByNameQueryKey(variables),
    queryFn: () =>
      execute<
        OrgPermissionByNameQueryResult,
        OrgPermissionByNameQueryVariables
      >(orgPermissionByNameQueryDocument, variables, options),
  });
}
