/**
 * Custom query hook for orgLimitByNameAndActorIdAndEntityId
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgLimit } from '../types';

/** GraphQL query document */
export const orgLimitByNameAndActorIdAndEntityIdQueryDocument = `
query OrgLimitByNameAndActorIdAndEntityIdQuery($name: String!, $actorId: UUID!, $entityId: UUID!) {
  orgLimitByNameAndActorIdAndEntityId(
    name: $name
    actorId: $actorId
    entityId: $entityId
  ) {
    id
    name
    actorId
    num
    max
    entityId
    actor {
      id
      username
      displayName
      profilePicture
      searchTsv
      type
      createdAt
      updatedAt
      searchTsvRank
    }
    entity {
      id
      username
      displayName
      profilePicture
      searchTsv
      type
      createdAt
      updatedAt
      searchTsvRank
    }
  }
}
`;

export interface OrgLimitByNameAndActorIdAndEntityIdQueryVariables {
  name: string;
  actorId: string;
  entityId: string;
}

export interface OrgLimitByNameAndActorIdAndEntityIdQueryResult {
  orgLimitByNameAndActorIdAndEntityId: OrgLimit;
}

/** Query key factory for caching */
export const orgLimitByNameAndActorIdAndEntityIdQueryKey = (
  variables?: OrgLimitByNameAndActorIdAndEntityIdQueryVariables
) => ['orgLimitByNameAndActorIdAndEntityId', variables] as const;

/**
 * Query hook for orgLimitByNameAndActorIdAndEntityId
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitByNameAndActorIdAndEntityIdQuery({ name, actorId, entityId });
 *
 * if (data?.orgLimitByNameAndActorIdAndEntityId) {
 *   console.log(data.orgLimitByNameAndActorIdAndEntityId);
 * }
 * ```
 */
export function useOrgLimitByNameAndActorIdAndEntityIdQuery(
  variables: OrgLimitByNameAndActorIdAndEntityIdQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgLimitByNameAndActorIdAndEntityIdQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgLimitByNameAndActorIdAndEntityIdQueryKey(variables),
    queryFn: () =>
      execute<
        OrgLimitByNameAndActorIdAndEntityIdQueryResult,
        OrgLimitByNameAndActorIdAndEntityIdQueryVariables
      >(orgLimitByNameAndActorIdAndEntityIdQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch orgLimitByNameAndActorIdAndEntityId without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgLimitByNameAndActorIdAndEntityIdQuery({ name, actorId, entityId });
 * ```
 */
export async function fetchOrgLimitByNameAndActorIdAndEntityIdQuery(
  variables: OrgLimitByNameAndActorIdAndEntityIdQueryVariables,
  options?: ExecuteOptions
): Promise<OrgLimitByNameAndActorIdAndEntityIdQueryResult> {
  return execute<
    OrgLimitByNameAndActorIdAndEntityIdQueryResult,
    OrgLimitByNameAndActorIdAndEntityIdQueryVariables
  >(orgLimitByNameAndActorIdAndEntityIdQueryDocument, variables, options);
}

/**
 * Prefetch orgLimitByNameAndActorIdAndEntityId for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgLimitByNameAndActorIdAndEntityIdQuery(queryClient, { name, actorId, entityId });
 * ```
 */
export async function prefetchOrgLimitByNameAndActorIdAndEntityIdQuery(
  queryClient: QueryClient,
  variables: OrgLimitByNameAndActorIdAndEntityIdQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgLimitByNameAndActorIdAndEntityIdQueryKey(variables),
    queryFn: () =>
      execute<
        OrgLimitByNameAndActorIdAndEntityIdQueryResult,
        OrgLimitByNameAndActorIdAndEntityIdQueryVariables
      >(orgLimitByNameAndActorIdAndEntityIdQueryDocument, variables, options),
  });
}
