/**
 * Single item query hook for OrgMembershipDefault
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgMembershipDefault } from '../types';

// Re-export entity type for convenience
export type { OrgMembershipDefault };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgMembershipDefaultQueryDocument = `
query OrgMembershipDefaultQuery($id: UUID!) {
  orgMembershipDefault(id: $id) {
    id
    createdAt
    updatedAt
    createdBy
    updatedBy
    isApproved
    entityId
    deleteMemberCascadeGroups
    createGroupsCascadeMembers
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgMembershipDefaultQueryVariables {
  id: string;
}

export interface OrgMembershipDefaultQueryResult {
  orgMembershipDefault: OrgMembershipDefault | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgMembershipDefaultQueryKey = (id: string) =>
  ['orgmembershipdefault', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgMembershipDefault by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipDefaultQuery('value-here');
 *
 * if (data?.orgMembershipDefault) {
 *   console.log(data.orgMembershipDefault.id);
 * }
 * ```
 */
export function useOrgMembershipDefaultQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgMembershipDefaultQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgMembershipDefaultQueryKey(id),
    queryFn: () =>
      execute<
        OrgMembershipDefaultQueryResult,
        OrgMembershipDefaultQueryVariables
      >(orgMembershipDefaultQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgMembershipDefault by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipDefaultQuery('value-here');
 * ```
 */
export async function fetchOrgMembershipDefaultQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgMembershipDefaultQueryResult> {
  return execute<
    OrgMembershipDefaultQueryResult,
    OrgMembershipDefaultQueryVariables
  >(orgMembershipDefaultQueryDocument, { id }, options);
}

/**
 * Prefetch a single OrgMembershipDefault for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipDefaultQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgMembershipDefaultQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgMembershipDefaultQueryKey(id),
    queryFn: () =>
      execute<
        OrgMembershipDefaultQueryResult,
        OrgMembershipDefaultQueryVariables
      >(orgMembershipDefaultQueryDocument, { id }, options),
  });
}
