/**
 * Single item query hook for OrgLimit
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgLimit } from '../types';

// Re-export entity type for convenience
export type { OrgLimit };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgLimitQueryDocument = `
query OrgLimitQuery($id: UUID!) {
  orgLimit(id: $id) {
    id
    name
    actorId
    num
    max
    entityId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgLimitQueryVariables {
  id: string;
}

export interface OrgLimitQueryResult {
  orgLimit: OrgLimit | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgLimitQueryKey = (id: string) =>
  ['orglimit', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgLimit by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitQuery('value-here');
 *
 * if (data?.orgLimit) {
 *   console.log(data.orgLimit.id);
 * }
 * ```
 */
export function useOrgLimitQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgLimitQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgLimitQueryKey(id),
    queryFn: () =>
      execute<OrgLimitQueryResult, OrgLimitQueryVariables>(
        orgLimitQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgLimit by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgLimitQuery('value-here');
 * ```
 */
export async function fetchOrgLimitQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgLimitQueryResult> {
  return execute<OrgLimitQueryResult, OrgLimitQueryVariables>(
    orgLimitQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single OrgLimit for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgLimitQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgLimitQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgLimitQueryKey(id),
    queryFn: () =>
      execute<OrgLimitQueryResult, OrgLimitQueryVariables>(
        orgLimitQueryDocument,
        { id },
        options
      ),
  });
}
