/**
 * Custom query hook for orgLimitDefaultByName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgLimitDefault } from '../types';

/** GraphQL query document */
export const orgLimitDefaultByNameQueryDocument = `
query OrgLimitDefaultByNameQuery($name: String!) {
  orgLimitDefaultByName(name: $name) {
    id
    name
    max
  }
}
`;

export interface OrgLimitDefaultByNameQueryVariables {
  name: string;
}

export interface OrgLimitDefaultByNameQueryResult {
  orgLimitDefaultByName: OrgLimitDefault;
}

/** Query key factory for caching */
export const orgLimitDefaultByNameQueryKey = (
  variables?: OrgLimitDefaultByNameQueryVariables
) => ['orgLimitDefaultByName', variables] as const;

/**
 * Query hook for orgLimitDefaultByName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitDefaultByNameQuery({ name });
 *
 * if (data?.orgLimitDefaultByName) {
 *   console.log(data.orgLimitDefaultByName);
 * }
 * ```
 */
export function useOrgLimitDefaultByNameQuery(
  variables: OrgLimitDefaultByNameQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgLimitDefaultByNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgLimitDefaultByNameQueryKey(variables),
    queryFn: () =>
      execute<
        OrgLimitDefaultByNameQueryResult,
        OrgLimitDefaultByNameQueryVariables
      >(orgLimitDefaultByNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch orgLimitDefaultByName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgLimitDefaultByNameQuery({ name });
 * ```
 */
export async function fetchOrgLimitDefaultByNameQuery(
  variables: OrgLimitDefaultByNameQueryVariables,
  options?: ExecuteOptions
): Promise<OrgLimitDefaultByNameQueryResult> {
  return execute<
    OrgLimitDefaultByNameQueryResult,
    OrgLimitDefaultByNameQueryVariables
  >(orgLimitDefaultByNameQueryDocument, variables, options);
}

/**
 * Prefetch orgLimitDefaultByName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgLimitDefaultByNameQuery(queryClient, { name });
 * ```
 */
export async function prefetchOrgLimitDefaultByNameQuery(
  queryClient: QueryClient,
  variables: OrgLimitDefaultByNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgLimitDefaultByNameQueryKey(variables),
    queryFn: () =>
      execute<
        OrgLimitDefaultByNameQueryResult,
        OrgLimitDefaultByNameQueryVariables
      >(orgLimitDefaultByNameQueryDocument, variables, options),
  });
}
