/**
 * List query hook for OrgMembership
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type OrgMembership,
  type UUIDFilter,
  type DatetimeFilter,
  type BooleanFilter,
  type BitStringFilter,
} from '../types';

// Re-export entity type for convenience
export type { OrgMembership };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgMembershipsQueryDocument = `
query OrgMembershipsQuery($first: Int, $offset: Int, $filter: OrgMembershipFilter, $orderBy: [OrgMembershipsOrderBy!]) {
  orgMemberships(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      createdAt
      updatedAt
      createdBy
      updatedBy
      isApproved
      isBanned
      isDisabled
      isActive
      isOwner
      isAdmin
      permissions
      granted
      actorId
      entityId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface OrgMembershipFilter {
  id?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  createdBy?: UUIDFilter;
  updatedBy?: UUIDFilter;
  isApproved?: BooleanFilter;
  isBanned?: BooleanFilter;
  isDisabled?: BooleanFilter;
  isActive?: BooleanFilter;
  isOwner?: BooleanFilter;
  isAdmin?: BooleanFilter;
  permissions?: BitStringFilter;
  granted?: BitStringFilter;
  actorId?: UUIDFilter;
  entityId?: UUIDFilter;
  /** Logical AND */
  and?: OrgMembershipFilter[];
  /** Logical OR */
  or?: OrgMembershipFilter[];
  /** Logical NOT */
  not?: OrgMembershipFilter;
}

type OrgMembershipsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'CREATED_BY_ASC'
  | 'CREATED_BY_DESC'
  | 'UPDATED_BY_ASC'
  | 'UPDATED_BY_DESC'
  | 'IS_APPROVED_ASC'
  | 'IS_APPROVED_DESC'
  | 'IS_BANNED_ASC'
  | 'IS_BANNED_DESC'
  | 'IS_DISABLED_ASC'
  | 'IS_DISABLED_DESC'
  | 'IS_ACTIVE_ASC'
  | 'IS_ACTIVE_DESC'
  | 'IS_OWNER_ASC'
  | 'IS_OWNER_DESC'
  | 'IS_ADMIN_ASC'
  | 'IS_ADMIN_DESC'
  | 'PERMISSIONS_ASC'
  | 'PERMISSIONS_DESC'
  | 'GRANTED_ASC'
  | 'GRANTED_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface OrgMembershipsQueryVariables {
  first?: number;
  offset?: number;
  filter?: OrgMembershipFilter;
  orderBy?: OrgMembershipsOrderBy[];
}

export interface OrgMembershipsQueryResult {
  orgMemberships: {
    totalCount: number;
    nodes: OrgMembership[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const orgMembershipsQueryKey = (
  variables?: OrgMembershipsQueryVariables
) => ['orgmembership', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching OrgMembership list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useOrgMembershipsQuery(
  variables?: OrgMembershipsQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgMembershipsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgMembershipsQueryKey(variables),
    queryFn: () =>
      execute<OrgMembershipsQueryResult, OrgMembershipsQueryVariables>(
        orgMembershipsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch OrgMembership list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchOrgMembershipsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: orgMembershipsQueryKey(variables),
 *   queryFn: () => fetchOrgMembershipsQuery(variables),
 * });
 * ```
 */
export async function fetchOrgMembershipsQuery(
  variables?: OrgMembershipsQueryVariables,
  options?: ExecuteOptions
): Promise<OrgMembershipsQueryResult> {
  return execute<OrgMembershipsQueryResult, OrgMembershipsQueryVariables>(
    orgMembershipsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch OrgMembership list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchOrgMembershipsQuery(
  queryClient: QueryClient,
  variables?: OrgMembershipsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgMembershipsQueryKey(variables),
    queryFn: () =>
      execute<OrgMembershipsQueryResult, OrgMembershipsQueryVariables>(
        orgMembershipsQueryDocument,
        variables,
        options
      ),
  });
}
