/**
 * Single item query hook for OrgOwnerGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgOwnerGrant } from '../types';

// Re-export entity type for convenience
export type { OrgOwnerGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgOwnerGrantQueryDocument = `
query OrgOwnerGrantQuery($id: UUID!) {
  orgOwnerGrant(id: $id) {
    id
    isGrant
    actorId
    entityId
    grantorId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgOwnerGrantQueryVariables {
  id: string;
}

export interface OrgOwnerGrantQueryResult {
  orgOwnerGrant: OrgOwnerGrant | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgOwnerGrantQueryKey = (id: string) =>
  ['orgownergrant', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgOwnerGrant by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgOwnerGrantQuery('value-here');
 *
 * if (data?.orgOwnerGrant) {
 *   console.log(data.orgOwnerGrant.id);
 * }
 * ```
 */
export function useOrgOwnerGrantQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgOwnerGrantQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgOwnerGrantQueryKey(id),
    queryFn: () =>
      execute<OrgOwnerGrantQueryResult, OrgOwnerGrantQueryVariables>(
        orgOwnerGrantQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgOwnerGrant by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgOwnerGrantQuery('value-here');
 * ```
 */
export async function fetchOrgOwnerGrantQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgOwnerGrantQueryResult> {
  return execute<OrgOwnerGrantQueryResult, OrgOwnerGrantQueryVariables>(
    orgOwnerGrantQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single OrgOwnerGrant for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgOwnerGrantQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgOwnerGrantQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgOwnerGrantQueryKey(id),
    queryFn: () =>
      execute<OrgOwnerGrantQueryResult, OrgOwnerGrantQueryVariables>(
        orgOwnerGrantQueryDocument,
        { id },
        options
      ),
  });
}
