/**
 * Single item query hook for OrgPermissionDefault
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type OrgPermissionDefault } from '../types';

// Re-export entity type for convenience
export type { OrgPermissionDefault };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgPermissionDefaultQueryDocument = `
query OrgPermissionDefaultQuery($id: UUID!) {
  orgPermissionDefault(id: $id) {
    id
    permissions
    entityId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface OrgPermissionDefaultQueryVariables {
  id: string;
}

export interface OrgPermissionDefaultQueryResult {
  orgPermissionDefault: OrgPermissionDefault | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const orgPermissionDefaultQueryKey = (id: string) =>
  ['orgpermissiondefault', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single OrgPermissionDefault by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgPermissionDefaultQuery('value-here');
 *
 * if (data?.orgPermissionDefault) {
 *   console.log(data.orgPermissionDefault.id);
 * }
 * ```
 */
export function useOrgPermissionDefaultQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<OrgPermissionDefaultQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgPermissionDefaultQueryKey(id),
    queryFn: () =>
      execute<
        OrgPermissionDefaultQueryResult,
        OrgPermissionDefaultQueryVariables
      >(orgPermissionDefaultQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single OrgPermissionDefault by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgPermissionDefaultQuery('value-here');
 * ```
 */
export async function fetchOrgPermissionDefaultQuery(
  id: string,
  options?: ExecuteOptions
): Promise<OrgPermissionDefaultQueryResult> {
  return execute<
    OrgPermissionDefaultQueryResult,
    OrgPermissionDefaultQueryVariables
  >(orgPermissionDefaultQueryDocument, { id }, options);
}

/**
 * Prefetch a single OrgPermissionDefault for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgPermissionDefaultQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchOrgPermissionDefaultQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgPermissionDefaultQueryKey(id),
    queryFn: () =>
      execute<
        OrgPermissionDefaultQueryResult,
        OrgPermissionDefaultQueryVariables
      >(orgPermissionDefaultQueryDocument, { id }, options),
  });
}
