/**
 * List query hook for OrgInvite
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type OrgInvite,
  type UUIDFilter,
  type StringFilter,
  type BooleanFilter,
  type IntFilter,
  type JSONFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { OrgInvite };

// ============================================================================
// GraphQL Document
// ============================================================================
export const orgInvitesQueryDocument = `
query OrgInvitesQuery($first: Int, $offset: Int, $filter: OrgInviteFilter, $orderBy: [OrgInvitesOrderBy!]) {
  orgInvites(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      email
      senderId
      receiverId
      inviteToken
      inviteValid
      inviteLimit
      inviteCount
      multiple
      data
      expiresAt
      createdAt
      updatedAt
      entityId
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface OrgInviteFilter {
  id?: UUIDFilter;
  email?: StringFilter;
  senderId?: UUIDFilter;
  receiverId?: UUIDFilter;
  inviteToken?: StringFilter;
  inviteValid?: BooleanFilter;
  inviteLimit?: IntFilter;
  inviteCount?: IntFilter;
  multiple?: BooleanFilter;
  data?: JSONFilter;
  expiresAt?: DatetimeFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  entityId?: UUIDFilter;
  /** Logical AND */
  and?: OrgInviteFilter[];
  /** Logical OR */
  or?: OrgInviteFilter[];
  /** Logical NOT */
  not?: OrgInviteFilter;
}

type OrgInvitesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'EMAIL_ASC'
  | 'EMAIL_DESC'
  | 'SENDER_ID_ASC'
  | 'SENDER_ID_DESC'
  | 'RECEIVER_ID_ASC'
  | 'RECEIVER_ID_DESC'
  | 'INVITE_TOKEN_ASC'
  | 'INVITE_TOKEN_DESC'
  | 'INVITE_VALID_ASC'
  | 'INVITE_VALID_DESC'
  | 'INVITE_LIMIT_ASC'
  | 'INVITE_LIMIT_DESC'
  | 'INVITE_COUNT_ASC'
  | 'INVITE_COUNT_DESC'
  | 'MULTIPLE_ASC'
  | 'MULTIPLE_DESC'
  | 'DATA_ASC'
  | 'DATA_DESC'
  | 'EXPIRES_AT_ASC'
  | 'EXPIRES_AT_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface OrgInvitesQueryVariables {
  first?: number;
  offset?: number;
  filter?: OrgInviteFilter;
  orderBy?: OrgInvitesOrderBy[];
}

export interface OrgInvitesQueryResult {
  orgInvites: {
    totalCount: number;
    nodes: OrgInvite[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const orgInvitesQueryKey = (variables?: OrgInvitesQueryVariables) =>
  ['orginvite', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching OrgInvite list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgInvitesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useOrgInvitesQuery(
  variables?: OrgInvitesQueryVariables,
  options?: Omit<
    UseQueryOptions<OrgInvitesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: orgInvitesQueryKey(variables),
    queryFn: () =>
      execute<OrgInvitesQueryResult, OrgInvitesQueryVariables>(
        orgInvitesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch OrgInvite list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchOrgInvitesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: orgInvitesQueryKey(variables),
 *   queryFn: () => fetchOrgInvitesQuery(variables),
 * });
 * ```
 */
export async function fetchOrgInvitesQuery(
  variables?: OrgInvitesQueryVariables,
  options?: ExecuteOptions
): Promise<OrgInvitesQueryResult> {
  return execute<OrgInvitesQueryResult, OrgInvitesQueryVariables>(
    orgInvitesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch OrgInvite list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgInvitesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchOrgInvitesQuery(
  queryClient: QueryClient,
  variables?: OrgInvitesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: orgInvitesQueryKey(variables),
    queryFn: () =>
      execute<OrgInvitesQueryResult, OrgInvitesQueryVariables>(
        orgInvitesQueryDocument,
        variables,
        options
      ),
  });
}
