/**
 * Custom query hook for phoneNumberByNumber
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PhoneNumber } from '../types';

/** GraphQL query document */
export const phoneNumberByNumberQueryDocument = `
query PhoneNumberByNumberQuery($number: String!) {
  phoneNumberByNumber(number: $number) {
    id
    ownerId
    cc
    number
    isVerified
    isPrimary
    createdAt
    updatedAt
    owner {
      id
      username
      displayName
      profilePicture
      searchTsv
      type
      createdAt
      updatedAt
      searchTsvRank
    }
  }
}
`;

export interface PhoneNumberByNumberQueryVariables {
  number: string;
}

export interface PhoneNumberByNumberQueryResult {
  phoneNumberByNumber: PhoneNumber;
}

/** Query key factory for caching */
export const phoneNumberByNumberQueryKey = (
  variables?: PhoneNumberByNumberQueryVariables
) => ['phoneNumberByNumber', variables] as const;

/**
 * Query hook for phoneNumberByNumber
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePhoneNumberByNumberQuery({ number });
 *
 * if (data?.phoneNumberByNumber) {
 *   console.log(data.phoneNumberByNumber);
 * }
 * ```
 */
export function usePhoneNumberByNumberQuery(
  variables: PhoneNumberByNumberQueryVariables,
  options?: Omit<
    UseQueryOptions<PhoneNumberByNumberQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: phoneNumberByNumberQueryKey(variables),
    queryFn: () =>
      execute<
        PhoneNumberByNumberQueryResult,
        PhoneNumberByNumberQueryVariables
      >(phoneNumberByNumberQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch phoneNumberByNumber without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPhoneNumberByNumberQuery({ number });
 * ```
 */
export async function fetchPhoneNumberByNumberQuery(
  variables: PhoneNumberByNumberQueryVariables,
  options?: ExecuteOptions
): Promise<PhoneNumberByNumberQueryResult> {
  return execute<
    PhoneNumberByNumberQueryResult,
    PhoneNumberByNumberQueryVariables
  >(phoneNumberByNumberQueryDocument, variables, options);
}

/**
 * Prefetch phoneNumberByNumber for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPhoneNumberByNumberQuery(queryClient, { number });
 * ```
 */
export async function prefetchPhoneNumberByNumberQuery(
  queryClient: QueryClient,
  variables: PhoneNumberByNumberQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: phoneNumberByNumberQueryKey(variables),
    queryFn: () =>
      execute<
        PhoneNumberByNumberQueryResult,
        PhoneNumberByNumberQueryVariables
      >(phoneNumberByNumberQueryDocument, variables, options),
  });
}
