/**
 * Single item query hook for PrimaryKeyConstraint
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PrimaryKeyConstraint } from '../types';

// Re-export entity type for convenience
export type { PrimaryKeyConstraint };

// ============================================================================
// GraphQL Document
// ============================================================================
export const primaryKeyConstraintQueryDocument = `
query PrimaryKeyConstraintQuery($id: UUID!) {
  primaryKeyConstraint(id: $id) {
    id
    databaseId
    tableId
    name
    type
    fieldIds
    smartTags
    category
    module
    scope
    tags
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface PrimaryKeyConstraintQueryVariables {
  id: string;
}

export interface PrimaryKeyConstraintQueryResult {
  primaryKeyConstraint: PrimaryKeyConstraint | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const primaryKeyConstraintQueryKey = (id: string) =>
  ['primarykeyconstraint', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single PrimaryKeyConstraint by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePrimaryKeyConstraintQuery('value-here');
 *
 * if (data?.primaryKeyConstraint) {
 *   console.log(data.primaryKeyConstraint.id);
 * }
 * ```
 */
export function usePrimaryKeyConstraintQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<PrimaryKeyConstraintQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: primaryKeyConstraintQueryKey(id),
    queryFn: () =>
      execute<
        PrimaryKeyConstraintQueryResult,
        PrimaryKeyConstraintQueryVariables
      >(primaryKeyConstraintQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single PrimaryKeyConstraint by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPrimaryKeyConstraintQuery('value-here');
 * ```
 */
export async function fetchPrimaryKeyConstraintQuery(
  id: string,
  options?: ExecuteOptions
): Promise<PrimaryKeyConstraintQueryResult> {
  return execute<
    PrimaryKeyConstraintQueryResult,
    PrimaryKeyConstraintQueryVariables
  >(primaryKeyConstraintQueryDocument, { id }, options);
}

/**
 * Prefetch a single PrimaryKeyConstraint for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPrimaryKeyConstraintQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchPrimaryKeyConstraintQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: primaryKeyConstraintQueryKey(id),
    queryFn: () =>
      execute<
        PrimaryKeyConstraintQueryResult,
        PrimaryKeyConstraintQueryVariables
      >(primaryKeyConstraintQueryDocument, { id }, options),
  });
}
