/**
 * Single item query hook for PhoneNumber
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PhoneNumber } from '../types';

// Re-export entity type for convenience
export type { PhoneNumber };

// ============================================================================
// GraphQL Document
// ============================================================================
export const phoneNumberQueryDocument = `
query PhoneNumberQuery($id: UUID!) {
  phoneNumber(id: $id) {
    id
    ownerId
    cc
    number
    isVerified
    isPrimary
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface PhoneNumberQueryVariables {
  id: string;
}

export interface PhoneNumberQueryResult {
  phoneNumber: PhoneNumber | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const phoneNumberQueryKey = (id: string) =>
  ['phonenumber', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single PhoneNumber by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePhoneNumberQuery('value-here');
 *
 * if (data?.phoneNumber) {
 *   console.log(data.phoneNumber.id);
 * }
 * ```
 */
export function usePhoneNumberQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<PhoneNumberQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: phoneNumberQueryKey(id),
    queryFn: () =>
      execute<PhoneNumberQueryResult, PhoneNumberQueryVariables>(
        phoneNumberQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single PhoneNumber by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPhoneNumberQuery('value-here');
 * ```
 */
export async function fetchPhoneNumberQuery(
  id: string,
  options?: ExecuteOptions
): Promise<PhoneNumberQueryResult> {
  return execute<PhoneNumberQueryResult, PhoneNumberQueryVariables>(
    phoneNumberQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single PhoneNumber for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPhoneNumberQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchPhoneNumberQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: phoneNumberQueryKey(id),
    queryFn: () =>
      execute<PhoneNumberQueryResult, PhoneNumberQueryVariables>(
        phoneNumberQueryDocument,
        { id },
        options
      ),
  });
}
