/**
 * Custom query hook for profilesModuleByDatabaseIdAndMembershipType
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ProfilesModule } from '../types';

/** GraphQL query document */
export const profilesModuleByDatabaseIdAndMembershipTypeQueryDocument = `
query ProfilesModuleByDatabaseIdAndMembershipTypeQuery($databaseId: UUID!, $membershipType: Int!) {
  profilesModuleByDatabaseIdAndMembershipType(
    databaseId: $databaseId
    membershipType: $membershipType
  ) {
    id
    databaseId
    schemaId
    privateSchemaId
    tableId
    tableName
    profilePermissionsTableId
    profilePermissionsTableName
    profileGrantsTableId
    profileGrantsTableName
    profileDefinitionGrantsTableId
    profileDefinitionGrantsTableName
    bitlen
    membershipType
    entityTableId
    actorTableId
    permissionsTableId
    membershipsTableId
    prefix
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    schema {
      id
      databaseId
      name
      schemaName
      label
      description
      smartTags
      category
      module
      scope
      tags
      isPublic
      createdAt
      updatedAt
    }
    privateSchema {
      id
      databaseId
      name
      schemaName
      label
      description
      smartTags
      category
      module
      scope
      tags
      isPublic
      createdAt
      updatedAt
    }
    table {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    profilePermissionsTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    profileGrantsTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    profileDefinitionGrantsTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    entityTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    actorTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    permissionsTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    membershipsTable {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
  }
}
`;

export interface ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables {
  databaseId: string;
  membershipType: number;
}

export interface ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult {
  profilesModuleByDatabaseIdAndMembershipType: ProfilesModule;
}

/** Query key factory for caching */
export const profilesModuleByDatabaseIdAndMembershipTypeQueryKey = (
  variables?: ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables
) => ['profilesModuleByDatabaseIdAndMembershipType', variables] as const;

/**
 * Query hook for profilesModuleByDatabaseIdAndMembershipType
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useProfilesModuleByDatabaseIdAndMembershipTypeQuery({ databaseId, membershipType });
 *
 * if (data?.profilesModuleByDatabaseIdAndMembershipType) {
 *   console.log(data.profilesModuleByDatabaseIdAndMembershipType);
 * }
 * ```
 */
export function useProfilesModuleByDatabaseIdAndMembershipTypeQuery(
  variables: ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables,
  options?: Omit<
    UseQueryOptions<
      ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult,
      Error
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: profilesModuleByDatabaseIdAndMembershipTypeQueryKey(variables),
    queryFn: () =>
      execute<
        ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult,
        ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables
      >(profilesModuleByDatabaseIdAndMembershipTypeQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch profilesModuleByDatabaseIdAndMembershipType without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchProfilesModuleByDatabaseIdAndMembershipTypeQuery({ databaseId, membershipType });
 * ```
 */
export async function fetchProfilesModuleByDatabaseIdAndMembershipTypeQuery(
  variables: ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables,
  options?: ExecuteOptions
): Promise<ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult> {
  return execute<
    ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult,
    ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables
  >(
    profilesModuleByDatabaseIdAndMembershipTypeQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch profilesModuleByDatabaseIdAndMembershipType for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchProfilesModuleByDatabaseIdAndMembershipTypeQuery(queryClient, { databaseId, membershipType });
 * ```
 */
export async function prefetchProfilesModuleByDatabaseIdAndMembershipTypeQuery(
  queryClient: QueryClient,
  variables: ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: profilesModuleByDatabaseIdAndMembershipTypeQueryKey(variables),
    queryFn: () =>
      execute<
        ProfilesModuleByDatabaseIdAndMembershipTypeQueryResult,
        ProfilesModuleByDatabaseIdAndMembershipTypeQueryVariables
      >(
        profilesModuleByDatabaseIdAndMembershipTypeQueryDocument,
        variables,
        options
      ),
  });
}
