/**
 * Single item query hook for PhoneNumbersModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PhoneNumbersModule } from '../types';

// Re-export entity type for convenience
export type { PhoneNumbersModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const phoneNumbersModuleQueryDocument = `
query PhoneNumbersModuleQuery($id: UUID!) {
  phoneNumbersModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    tableId
    ownerTableId
    tableName
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface PhoneNumbersModuleQueryVariables {
  id: string;
}

export interface PhoneNumbersModuleQueryResult {
  phoneNumbersModule: PhoneNumbersModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const phoneNumbersModuleQueryKey = (id: string) =>
  ['phonenumbersmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single PhoneNumbersModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePhoneNumbersModuleQuery('value-here');
 *
 * if (data?.phoneNumbersModule) {
 *   console.log(data.phoneNumbersModule.id);
 * }
 * ```
 */
export function usePhoneNumbersModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<PhoneNumbersModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: phoneNumbersModuleQueryKey(id),
    queryFn: () =>
      execute<PhoneNumbersModuleQueryResult, PhoneNumbersModuleQueryVariables>(
        phoneNumbersModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single PhoneNumbersModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPhoneNumbersModuleQuery('value-here');
 * ```
 */
export async function fetchPhoneNumbersModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<PhoneNumbersModuleQueryResult> {
  return execute<
    PhoneNumbersModuleQueryResult,
    PhoneNumbersModuleQueryVariables
  >(phoneNumbersModuleQueryDocument, { id }, options);
}

/**
 * Prefetch a single PhoneNumbersModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPhoneNumbersModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchPhoneNumbersModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: phoneNumbersModuleQueryKey(id),
    queryFn: () =>
      execute<PhoneNumbersModuleQueryResult, PhoneNumbersModuleQueryVariables>(
        phoneNumbersModuleQueryDocument,
        { id },
        options
      ),
  });
}
