/**
 * List query hook for PermissionsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type PermissionsModule,
  type UUIDFilter,
  type StringFilter,
  type IntFilter,
} from '../types';

// Re-export entity type for convenience
export type { PermissionsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const permissionsModulesQueryDocument = `
query PermissionsModulesQuery($first: Int, $offset: Int, $filter: PermissionsModuleFilter, $orderBy: [PermissionsModulesOrderBy!]) {
  permissionsModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      tableId
      tableName
      defaultTableId
      defaultTableName
      bitlen
      membershipType
      entityTableId
      actorTableId
      prefix
      getPaddedMask
      getMask
      getByMask
      getMaskByName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface PermissionsModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  tableName?: StringFilter;
  defaultTableId?: UUIDFilter;
  defaultTableName?: StringFilter;
  bitlen?: IntFilter;
  membershipType?: IntFilter;
  entityTableId?: UUIDFilter;
  actorTableId?: UUIDFilter;
  prefix?: StringFilter;
  getPaddedMask?: StringFilter;
  getMask?: StringFilter;
  getByMask?: StringFilter;
  getMaskByName?: StringFilter;
  /** Logical AND */
  and?: PermissionsModuleFilter[];
  /** Logical OR */
  or?: PermissionsModuleFilter[];
  /** Logical NOT */
  not?: PermissionsModuleFilter;
}

type PermissionsModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'TABLE_NAME_ASC'
  | 'TABLE_NAME_DESC'
  | 'DEFAULT_TABLE_ID_ASC'
  | 'DEFAULT_TABLE_ID_DESC'
  | 'DEFAULT_TABLE_NAME_ASC'
  | 'DEFAULT_TABLE_NAME_DESC'
  | 'BITLEN_ASC'
  | 'BITLEN_DESC'
  | 'MEMBERSHIP_TYPE_ASC'
  | 'MEMBERSHIP_TYPE_DESC'
  | 'ENTITY_TABLE_ID_ASC'
  | 'ENTITY_TABLE_ID_DESC'
  | 'ACTOR_TABLE_ID_ASC'
  | 'ACTOR_TABLE_ID_DESC'
  | 'PREFIX_ASC'
  | 'PREFIX_DESC'
  | 'GET_PADDED_MASK_ASC'
  | 'GET_PADDED_MASK_DESC'
  | 'GET_MASK_ASC'
  | 'GET_MASK_DESC'
  | 'GET_BY_MASK_ASC'
  | 'GET_BY_MASK_DESC'
  | 'GET_MASK_BY_NAME_ASC'
  | 'GET_MASK_BY_NAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface PermissionsModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: PermissionsModuleFilter;
  orderBy?: PermissionsModulesOrderBy[];
}

export interface PermissionsModulesQueryResult {
  permissionsModules: {
    totalCount: number;
    nodes: PermissionsModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const permissionsModulesQueryKey = (
  variables?: PermissionsModulesQueryVariables
) => ['permissionsmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching PermissionsModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePermissionsModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function usePermissionsModulesQuery(
  variables?: PermissionsModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<PermissionsModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: permissionsModulesQueryKey(variables),
    queryFn: () =>
      execute<PermissionsModulesQueryResult, PermissionsModulesQueryVariables>(
        permissionsModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch PermissionsModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchPermissionsModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: permissionsModulesQueryKey(variables),
 *   queryFn: () => fetchPermissionsModulesQuery(variables),
 * });
 * ```
 */
export async function fetchPermissionsModulesQuery(
  variables?: PermissionsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<PermissionsModulesQueryResult> {
  return execute<
    PermissionsModulesQueryResult,
    PermissionsModulesQueryVariables
  >(permissionsModulesQueryDocument, variables, options);
}

/**
 * Prefetch PermissionsModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPermissionsModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchPermissionsModulesQuery(
  queryClient: QueryClient,
  variables?: PermissionsModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: permissionsModulesQueryKey(variables),
    queryFn: () =>
      execute<PermissionsModulesQueryResult, PermissionsModulesQueryVariables>(
        permissionsModulesQueryDocument,
        variables,
        options
      ),
  });
}
