/**
 * List query hook for PhoneNumber
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type PhoneNumber,
  type UUIDFilter,
  type StringFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { PhoneNumber };

// ============================================================================
// GraphQL Document
// ============================================================================
export const phoneNumbersQueryDocument = `
query PhoneNumbersQuery($first: Int, $offset: Int, $filter: PhoneNumberFilter, $orderBy: [PhoneNumbersOrderBy!]) {
  phoneNumbers(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      ownerId
      cc
      number
      isVerified
      isPrimary
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface PhoneNumberFilter {
  id?: UUIDFilter;
  ownerId?: UUIDFilter;
  cc?: StringFilter;
  number?: StringFilter;
  isVerified?: BooleanFilter;
  isPrimary?: BooleanFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: PhoneNumberFilter[];
  /** Logical OR */
  or?: PhoneNumberFilter[];
  /** Logical NOT */
  not?: PhoneNumberFilter;
}

type PhoneNumbersOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'OWNER_ID_ASC'
  | 'OWNER_ID_DESC'
  | 'CC_ASC'
  | 'CC_DESC'
  | 'NUMBER_ASC'
  | 'NUMBER_DESC'
  | 'IS_VERIFIED_ASC'
  | 'IS_VERIFIED_DESC'
  | 'IS_PRIMARY_ASC'
  | 'IS_PRIMARY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface PhoneNumbersQueryVariables {
  first?: number;
  offset?: number;
  filter?: PhoneNumberFilter;
  orderBy?: PhoneNumbersOrderBy[];
}

export interface PhoneNumbersQueryResult {
  phoneNumbers: {
    totalCount: number;
    nodes: PhoneNumber[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const phoneNumbersQueryKey = (variables?: PhoneNumbersQueryVariables) =>
  ['phonenumber', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching PhoneNumber list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePhoneNumbersQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function usePhoneNumbersQuery(
  variables?: PhoneNumbersQueryVariables,
  options?: Omit<
    UseQueryOptions<PhoneNumbersQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: phoneNumbersQueryKey(variables),
    queryFn: () =>
      execute<PhoneNumbersQueryResult, PhoneNumbersQueryVariables>(
        phoneNumbersQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch PhoneNumber list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchPhoneNumbersQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: phoneNumbersQueryKey(variables),
 *   queryFn: () => fetchPhoneNumbersQuery(variables),
 * });
 * ```
 */
export async function fetchPhoneNumbersQuery(
  variables?: PhoneNumbersQueryVariables,
  options?: ExecuteOptions
): Promise<PhoneNumbersQueryResult> {
  return execute<PhoneNumbersQueryResult, PhoneNumbersQueryVariables>(
    phoneNumbersQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch PhoneNumber list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPhoneNumbersQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchPhoneNumbersQuery(
  queryClient: QueryClient,
  variables?: PhoneNumbersQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: phoneNumbersQueryKey(variables),
    queryFn: () =>
      execute<PhoneNumbersQueryResult, PhoneNumbersQueryVariables>(
        phoneNumbersQueryDocument,
        variables,
        options
      ),
  });
}
