/**
 * Single item query hook for ProfilesModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type ProfilesModule } from '../types';

// Re-export entity type for convenience
export type { ProfilesModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const profilesModuleQueryDocument = `
query ProfilesModuleQuery($id: UUID!) {
  profilesModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    tableId
    tableName
    profilePermissionsTableId
    profilePermissionsTableName
    profileGrantsTableId
    profileGrantsTableName
    profileDefinitionGrantsTableId
    profileDefinitionGrantsTableName
    bitlen
    membershipType
    entityTableId
    actorTableId
    permissionsTableId
    membershipsTableId
    prefix
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface ProfilesModuleQueryVariables {
  id: string;
}

export interface ProfilesModuleQueryResult {
  profilesModule: ProfilesModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const profilesModuleQueryKey = (id: string) =>
  ['profilesmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single ProfilesModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useProfilesModuleQuery('value-here');
 *
 * if (data?.profilesModule) {
 *   console.log(data.profilesModule.id);
 * }
 * ```
 */
export function useProfilesModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<ProfilesModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: profilesModuleQueryKey(id),
    queryFn: () =>
      execute<ProfilesModuleQueryResult, ProfilesModuleQueryVariables>(
        profilesModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single ProfilesModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchProfilesModuleQuery('value-here');
 * ```
 */
export async function fetchProfilesModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<ProfilesModuleQueryResult> {
  return execute<ProfilesModuleQueryResult, ProfilesModuleQueryVariables>(
    profilesModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single ProfilesModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchProfilesModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchProfilesModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: profilesModuleQueryKey(id),
    queryFn: () =>
      execute<ProfilesModuleQueryResult, ProfilesModuleQueryVariables>(
        profilesModuleQueryDocument,
        { id },
        options
      ),
  });
}
