/**
 * List query hook for Procedure
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Procedure,
  type UUIDFilter,
  type StringFilter,
  type StringListFilter,
  type JSONFilter,
  type IntFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Procedure };

// ============================================================================
// GraphQL Document
// ============================================================================
export const proceduresQueryDocument = `
query ProceduresQuery($first: Int, $offset: Int, $filter: ProcedureFilter, $orderBy: [ProceduresOrderBy!]) {
  procedures(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      name
      argnames
      argtypes
      argdefaults
      langName
      definition
      smartTags
      category
      module
      scope
      tags
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface ProcedureFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  name?: StringFilter;
  argnames?: StringListFilter;
  argtypes?: StringListFilter;
  argdefaults?: StringListFilter;
  langName?: StringFilter;
  definition?: StringFilter;
  smartTags?: JSONFilter;
  module?: StringFilter;
  scope?: IntFilter;
  tags?: StringListFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: ProcedureFilter[];
  /** Logical OR */
  or?: ProcedureFilter[];
  /** Logical NOT */
  not?: ProcedureFilter;
}

type ProceduresOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'ARGNAMES_ASC'
  | 'ARGNAMES_DESC'
  | 'ARGTYPES_ASC'
  | 'ARGTYPES_DESC'
  | 'ARGDEFAULTS_ASC'
  | 'ARGDEFAULTS_DESC'
  | 'LANG_NAME_ASC'
  | 'LANG_NAME_DESC'
  | 'DEFINITION_ASC'
  | 'DEFINITION_DESC'
  | 'SMART_TAGS_ASC'
  | 'SMART_TAGS_DESC'
  | 'CATEGORY_ASC'
  | 'CATEGORY_DESC'
  | 'MODULE_ASC'
  | 'MODULE_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface ProceduresQueryVariables {
  first?: number;
  offset?: number;
  filter?: ProcedureFilter;
  orderBy?: ProceduresOrderBy[];
}

export interface ProceduresQueryResult {
  procedures: {
    totalCount: number;
    nodes: Procedure[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const proceduresQueryKey = (variables?: ProceduresQueryVariables) =>
  ['procedure', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Procedure list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useProceduresQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useProceduresQuery(
  variables?: ProceduresQueryVariables,
  options?: Omit<
    UseQueryOptions<ProceduresQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: proceduresQueryKey(variables),
    queryFn: () =>
      execute<ProceduresQueryResult, ProceduresQueryVariables>(
        proceduresQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Procedure list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchProceduresQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: proceduresQueryKey(variables),
 *   queryFn: () => fetchProceduresQuery(variables),
 * });
 * ```
 */
export async function fetchProceduresQuery(
  variables?: ProceduresQueryVariables,
  options?: ExecuteOptions
): Promise<ProceduresQueryResult> {
  return execute<ProceduresQueryResult, ProceduresQueryVariables>(
    proceduresQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Procedure list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchProceduresQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchProceduresQuery(
  queryClient: QueryClient,
  variables?: ProceduresQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: proceduresQueryKey(variables),
    queryFn: () =>
      execute<ProceduresQueryResult, ProceduresQueryVariables>(
        proceduresQueryDocument,
        variables,
        options
      ),
  });
}
