/**
 * Custom query hook for primaryKeyConstraintByTableIdAndName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PrimaryKeyConstraint } from '../types';

/** GraphQL query document */
export const primaryKeyConstraintByTableIdAndNameQueryDocument = `
query PrimaryKeyConstraintByTableIdAndNameQuery($tableId: UUID!, $name: String!) {
  primaryKeyConstraintByTableIdAndName(tableId: $tableId, name: $name) {
    id
    databaseId
    tableId
    name
    type
    fieldIds
    smartTags
    category
    module
    scope
    tags
    createdAt
    updatedAt
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    table {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
  }
}
`;

export interface PrimaryKeyConstraintByTableIdAndNameQueryVariables {
  tableId: string;
  name: string;
}

export interface PrimaryKeyConstraintByTableIdAndNameQueryResult {
  primaryKeyConstraintByTableIdAndName: PrimaryKeyConstraint;
}

/** Query key factory for caching */
export const primaryKeyConstraintByTableIdAndNameQueryKey = (
  variables?: PrimaryKeyConstraintByTableIdAndNameQueryVariables
) => ['primaryKeyConstraintByTableIdAndName', variables] as const;

/**
 * Query hook for primaryKeyConstraintByTableIdAndName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePrimaryKeyConstraintByTableIdAndNameQuery({ tableId, name });
 *
 * if (data?.primaryKeyConstraintByTableIdAndName) {
 *   console.log(data.primaryKeyConstraintByTableIdAndName);
 * }
 * ```
 */
export function usePrimaryKeyConstraintByTableIdAndNameQuery(
  variables: PrimaryKeyConstraintByTableIdAndNameQueryVariables,
  options?: Omit<
    UseQueryOptions<PrimaryKeyConstraintByTableIdAndNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: primaryKeyConstraintByTableIdAndNameQueryKey(variables),
    queryFn: () =>
      execute<
        PrimaryKeyConstraintByTableIdAndNameQueryResult,
        PrimaryKeyConstraintByTableIdAndNameQueryVariables
      >(primaryKeyConstraintByTableIdAndNameQueryDocument, variables),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch primaryKeyConstraintByTableIdAndName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPrimaryKeyConstraintByTableIdAndNameQuery({ tableId, name });
 * ```
 */
export async function fetchPrimaryKeyConstraintByTableIdAndNameQuery(
  variables: PrimaryKeyConstraintByTableIdAndNameQueryVariables,
  options?: ExecuteOptions
): Promise<PrimaryKeyConstraintByTableIdAndNameQueryResult> {
  return execute<
    PrimaryKeyConstraintByTableIdAndNameQueryResult,
    PrimaryKeyConstraintByTableIdAndNameQueryVariables
  >(primaryKeyConstraintByTableIdAndNameQueryDocument, variables, options);
}

/**
 * Prefetch primaryKeyConstraintByTableIdAndName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPrimaryKeyConstraintByTableIdAndNameQuery(queryClient, { tableId, name });
 * ```
 */
export async function prefetchPrimaryKeyConstraintByTableIdAndNameQuery(
  queryClient: QueryClient,
  variables: PrimaryKeyConstraintByTableIdAndNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: primaryKeyConstraintByTableIdAndNameQueryKey(variables),
    queryFn: () =>
      execute<
        PrimaryKeyConstraintByTableIdAndNameQueryResult,
        PrimaryKeyConstraintByTableIdAndNameQueryVariables
      >(primaryKeyConstraintByTableIdAndNameQueryDocument, variables, options),
  });
}
