/**
 * Single item query hook for PermissionsModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type PermissionsModule } from '../types';

// Re-export entity type for convenience
export type { PermissionsModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const permissionsModuleQueryDocument = `
query PermissionsModuleQuery($id: UUID!) {
  permissionsModule(id: $id) {
    id
    databaseId
    schemaId
    privateSchemaId
    tableId
    tableName
    defaultTableId
    defaultTableName
    bitlen
    membershipType
    entityTableId
    actorTableId
    prefix
    getPaddedMask
    getMask
    getByMask
    getMaskByName
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface PermissionsModuleQueryVariables {
  id: string;
}

export interface PermissionsModuleQueryResult {
  permissionsModule: PermissionsModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const permissionsModuleQueryKey = (id: string) =>
  ['permissionsmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single PermissionsModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePermissionsModuleQuery('value-here');
 *
 * if (data?.permissionsModule) {
 *   console.log(data.permissionsModule.id);
 * }
 * ```
 */
export function usePermissionsModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<PermissionsModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: permissionsModuleQueryKey(id),
    queryFn: () =>
      execute<PermissionsModuleQueryResult, PermissionsModuleQueryVariables>(
        permissionsModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single PermissionsModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPermissionsModuleQuery('value-here');
 * ```
 */
export async function fetchPermissionsModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<PermissionsModuleQueryResult> {
  return execute<PermissionsModuleQueryResult, PermissionsModuleQueryVariables>(
    permissionsModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single PermissionsModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPermissionsModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchPermissionsModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: permissionsModuleQueryKey(id),
    queryFn: () =>
      execute<PermissionsModuleQueryResult, PermissionsModuleQueryVariables>(
        permissionsModuleQueryDocument,
        { id },
        options
      ),
  });
}
