/**
 * Custom query hook for revParse
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';

/** GraphQL query document */
export const revParseQueryDocument = `
query RevParseQuery($dbId: UUID, $storeId: UUID, $refname: String) {
  revParse(dbId: $dbId, storeId: $storeId, refname: $refname)
}
`;

export interface RevParseQueryVariables {
  dbId?: string;
  storeId?: string;
  refname?: string;
}

export interface RevParseQueryResult {
  revParse: string;
}

/** Query key factory for caching */
export const revParseQueryKey = (variables?: RevParseQueryVariables) =>
  ['revParse', variables] as const;

/**
 * Query hook for revParse
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useRevParseQuery({ dbId, storeId, refname });
 *
 * if (data?.revParse) {
 *   console.log(data.revParse);
 * }
 * ```
 */
export function useRevParseQuery(
  variables?: RevParseQueryVariables,
  options?: Omit<
    UseQueryOptions<RevParseQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: revParseQueryKey(variables),
    queryFn: () =>
      execute<RevParseQueryResult, RevParseQueryVariables>(
        revParseQueryDocument,
        variables
      ),

    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch revParse without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchRevParseQuery({ dbId, storeId, refname });
 * ```
 */
export async function fetchRevParseQuery(
  variables?: RevParseQueryVariables,
  options?: ExecuteOptions
): Promise<RevParseQueryResult> {
  return execute<RevParseQueryResult, RevParseQueryVariables>(
    revParseQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch revParse for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchRevParseQuery(queryClient, { dbId, storeId, refname });
 * ```
 */
export async function prefetchRevParseQuery(
  queryClient: QueryClient,
  variables?: RevParseQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: revParseQueryKey(variables),
    queryFn: () =>
      execute<RevParseQueryResult, RevParseQueryVariables>(
        revParseQueryDocument,
        variables,
        options
      ),
  });
}
