/**
 * Single item query hook for Ref
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Ref } from '../types';

// Re-export entity type for convenience
export type { Ref };

// ============================================================================
// GraphQL Document
// ============================================================================
export const refQueryDocument = `
query RefQuery($id: UUID!) {
  ref(id: $id) {
    id
    name
    databaseId
    storeId
    commitId
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface RefQueryVariables {
  id: string;
}

export interface RefQueryResult {
  ref: Ref | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const refQueryKey = (id: string) => ['ref', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Ref by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useRefQuery('value-here');
 *
 * if (data?.ref) {
 *   console.log(data.ref.id);
 * }
 * ```
 */
export function useRefQuery(
  id: string,
  options?: Omit<UseQueryOptions<RefQueryResult, Error>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: refQueryKey(id),
    queryFn: () =>
      execute<RefQueryResult, RefQueryVariables>(refQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Ref by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchRefQuery('value-here');
 * ```
 */
export async function fetchRefQuery(
  id: string,
  options?: ExecuteOptions
): Promise<RefQueryResult> {
  return execute<RefQueryResult, RefQueryVariables>(
    refQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Ref for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchRefQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchRefQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: refQueryKey(id),
    queryFn: () =>
      execute<RefQueryResult, RefQueryVariables>(
        refQueryDocument,
        { id },
        options
      ),
  });
}
