/**
 * List query hook for SiteTheme
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type SiteTheme, type UUIDFilter, type JSONFilter } from '../types';

// Re-export entity type for convenience
export type { SiteTheme };

// ============================================================================
// GraphQL Document
// ============================================================================
export const siteThemesQueryDocument = `
query SiteThemesQuery($first: Int, $offset: Int, $filter: SiteThemeFilter, $orderBy: [SiteThemesOrderBy!]) {
  siteThemes(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      siteId
      theme
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface SiteThemeFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  siteId?: UUIDFilter;
  theme?: JSONFilter;
  /** Logical AND */
  and?: SiteThemeFilter[];
  /** Logical OR */
  or?: SiteThemeFilter[];
  /** Logical NOT */
  not?: SiteThemeFilter;
}

type SiteThemesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SITE_ID_ASC'
  | 'SITE_ID_DESC'
  | 'THEME_ASC'
  | 'THEME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface SiteThemesQueryVariables {
  first?: number;
  offset?: number;
  filter?: SiteThemeFilter;
  orderBy?: SiteThemesOrderBy[];
}

export interface SiteThemesQueryResult {
  siteThemes: {
    totalCount: number;
    nodes: SiteTheme[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const siteThemesQueryKey = (variables?: SiteThemesQueryVariables) =>
  ['sitetheme', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching SiteTheme list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteThemesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useSiteThemesQuery(
  variables?: SiteThemesQueryVariables,
  options?: Omit<
    UseQueryOptions<SiteThemesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: siteThemesQueryKey(variables),
    queryFn: () =>
      execute<SiteThemesQueryResult, SiteThemesQueryVariables>(
        siteThemesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch SiteTheme list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchSiteThemesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: siteThemesQueryKey(variables),
 *   queryFn: () => fetchSiteThemesQuery(variables),
 * });
 * ```
 */
export async function fetchSiteThemesQuery(
  variables?: SiteThemesQueryVariables,
  options?: ExecuteOptions
): Promise<SiteThemesQueryResult> {
  return execute<SiteThemesQueryResult, SiteThemesQueryVariables>(
    siteThemesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch SiteTheme list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteThemesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchSiteThemesQuery(
  queryClient: QueryClient,
  variables?: SiteThemesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: siteThemesQueryKey(variables),
    queryFn: () =>
      execute<SiteThemesQueryResult, SiteThemesQueryVariables>(
        siteThemesQueryDocument,
        variables,
        options
      ),
  });
}
