/**
 * Custom query hook for schemaBySchemaName
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Schema } from '../types';

/** GraphQL query document */
export const schemaBySchemaNameQueryDocument = `
query SchemaBySchemaNameQuery($schemaName: String!) {
  schemaBySchemaName(schemaName: $schemaName) {
    id
    databaseId
    name
    schemaName
    label
    description
    smartTags
    category
    module
    scope
    tags
    isPublic
    createdAt
    updatedAt
    database {
      id
      ownerId
      schemaName
      privateSchemaName
      name
      label
      hash
      createdAt
      updatedAt
    }
    tables {
      totalCount
    }
    schemaGrants {
      totalCount
    }
    apiSchemas {
      totalCount
    }
    connectedAccountsModules {
      totalCount
    }
    connectedAccountsModulesByPrivateSchemaId {
      totalCount
    }
    cryptoAddressesModules {
      totalCount
    }
    cryptoAddressesModulesByPrivateSchemaId {
      totalCount
    }
    cryptoAuthModules {
      totalCount
    }
    emailsModules {
      totalCount
    }
    emailsModulesByPrivateSchemaId {
      totalCount
    }
    encryptedSecretsModules {
      totalCount
    }
    fieldModulesByPrivateSchemaId {
      totalCount
    }
    invitesModules {
      totalCount
    }
    invitesModulesByPrivateSchemaId {
      totalCount
    }
    levelsModules {
      totalCount
    }
    levelsModulesByPrivateSchemaId {
      totalCount
    }
    limitsModules {
      totalCount
    }
    limitsModulesByPrivateSchemaId {
      totalCount
    }
    membershipTypesModules {
      totalCount
    }
    membershipsModules {
      totalCount
    }
    membershipsModulesByPrivateSchemaId {
      totalCount
    }
    permissionsModules {
      totalCount
    }
    permissionsModulesByPrivateSchemaId {
      totalCount
    }
    phoneNumbersModules {
      totalCount
    }
    phoneNumbersModulesByPrivateSchemaId {
      totalCount
    }
    profilesModules {
      totalCount
    }
    profilesModulesByPrivateSchemaId {
      totalCount
    }
    rlsModules {
      totalCount
    }
    rlsModulesByPrivateSchemaId {
      totalCount
    }
    secretsModules {
      totalCount
    }
    tokensModules {
      totalCount
    }
    userAuthModules {
      totalCount
    }
    usersModules {
      totalCount
    }
    uuidModules {
      totalCount
    }
    hierarchyModules {
      totalCount
    }
    hierarchyModulesByPrivateSchemaId {
      totalCount
    }
    userProfilesModules {
      totalCount
    }
    userProfilesModulesByPrivateSchemaId {
      totalCount
    }
    userSettingsModules {
      totalCount
    }
    userSettingsModulesByPrivateSchemaId {
      totalCount
    }
    organizationSettingsModules {
      totalCount
    }
    organizationSettingsModulesByPrivateSchemaId {
      totalCount
    }
    apisByApiSchemaSchemaIdAndApiId {
      totalCount
    }
    tablesByLevelsModulePrivateSchemaIdAndEntityTableId {
      totalCount
    }
  }
}
`;

export interface SchemaBySchemaNameQueryVariables {
  schemaName: string;
}

export interface SchemaBySchemaNameQueryResult {
  schemaBySchemaName: Schema;
}

/** Query key factory for caching */
export const schemaBySchemaNameQueryKey = (
  variables?: SchemaBySchemaNameQueryVariables
) => ['schemaBySchemaName', variables] as const;

/**
 * Query hook for schemaBySchemaName
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSchemaBySchemaNameQuery({ schemaName });
 *
 * if (data?.schemaBySchemaName) {
 *   console.log(data.schemaBySchemaName);
 * }
 * ```
 */
export function useSchemaBySchemaNameQuery(
  variables: SchemaBySchemaNameQueryVariables,
  options?: Omit<
    UseQueryOptions<SchemaBySchemaNameQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: schemaBySchemaNameQueryKey(variables),
    queryFn: () =>
      execute<SchemaBySchemaNameQueryResult, SchemaBySchemaNameQueryVariables>(
        schemaBySchemaNameQueryDocument,
        variables
      ),
    enabled: !!variables && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch schemaBySchemaName without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchSchemaBySchemaNameQuery({ schemaName });
 * ```
 */
export async function fetchSchemaBySchemaNameQuery(
  variables: SchemaBySchemaNameQueryVariables,
  options?: ExecuteOptions
): Promise<SchemaBySchemaNameQueryResult> {
  return execute<
    SchemaBySchemaNameQueryResult,
    SchemaBySchemaNameQueryVariables
  >(schemaBySchemaNameQueryDocument, variables, options);
}

/**
 * Prefetch schemaBySchemaName for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSchemaBySchemaNameQuery(queryClient, { schemaName });
 * ```
 */
export async function prefetchSchemaBySchemaNameQuery(
  queryClient: QueryClient,
  variables: SchemaBySchemaNameQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: schemaBySchemaNameQueryKey(variables),
    queryFn: () =>
      execute<SchemaBySchemaNameQueryResult, SchemaBySchemaNameQueryVariables>(
        schemaBySchemaNameQueryDocument,
        variables,
        options
      ),
  });
}
