/**
 * Single item query hook for Site
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Site } from '../types';

// Re-export entity type for convenience
export type { Site };

// ============================================================================
// GraphQL Document
// ============================================================================
export const siteQueryDocument = `
query SiteQuery($id: UUID!) {
  site(id: $id) {
    id
    databaseId
    title
    description
    ogImage
    favicon
    appleTouchIcon
    logo
    dbname
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface SiteQueryVariables {
  id: string;
}

export interface SiteQueryResult {
  site: Site | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const siteQueryKey = (id: string) => ['site', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Site by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteQuery('value-here');
 *
 * if (data?.site) {
 *   console.log(data.site.id);
 * }
 * ```
 */
export function useSiteQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<SiteQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: siteQueryKey(id),
    queryFn: () =>
      execute<SiteQueryResult, SiteQueryVariables>(siteQueryDocument, { id }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Site by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchSiteQuery('value-here');
 * ```
 */
export async function fetchSiteQuery(
  id: string,
  options?: ExecuteOptions
): Promise<SiteQueryResult> {
  return execute<SiteQueryResult, SiteQueryVariables>(
    siteQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Site for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchSiteQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: siteQueryKey(id),
    queryFn: () =>
      execute<SiteQueryResult, SiteQueryVariables>(
        siteQueryDocument,
        { id },
        options
      ),
  });
}
