/**
 * List query hook for Schema
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Schema,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type IntFilter,
  type StringListFilter,
  type BooleanFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Schema };

// ============================================================================
// GraphQL Document
// ============================================================================
export const schemasQueryDocument = `
query SchemasQuery($first: Int, $offset: Int, $filter: SchemaFilter, $orderBy: [SchemasOrderBy!]) {
  schemas(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      name
      schemaName
      label
      description
      smartTags
      category
      module
      scope
      tags
      isPublic
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface SchemaFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  name?: StringFilter;
  schemaName?: StringFilter;
  label?: StringFilter;
  description?: StringFilter;
  smartTags?: JSONFilter;
  module?: StringFilter;
  scope?: IntFilter;
  tags?: StringListFilter;
  isPublic?: BooleanFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: SchemaFilter[];
  /** Logical OR */
  or?: SchemaFilter[];
  /** Logical NOT */
  not?: SchemaFilter;
}

type SchemasOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'SCHEMA_NAME_ASC'
  | 'SCHEMA_NAME_DESC'
  | 'LABEL_ASC'
  | 'LABEL_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'SMART_TAGS_ASC'
  | 'SMART_TAGS_DESC'
  | 'CATEGORY_ASC'
  | 'CATEGORY_DESC'
  | 'MODULE_ASC'
  | 'MODULE_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'IS_PUBLIC_ASC'
  | 'IS_PUBLIC_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface SchemasQueryVariables {
  first?: number;
  offset?: number;
  filter?: SchemaFilter;
  orderBy?: SchemasOrderBy[];
}

export interface SchemasQueryResult {
  schemas: {
    totalCount: number;
    nodes: Schema[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const schemasQueryKey = (variables?: SchemasQueryVariables) =>
  ['schema', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Schema list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSchemasQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useSchemasQuery(
  variables?: SchemasQueryVariables,
  options?: Omit<
    UseQueryOptions<SchemasQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: schemasQueryKey(variables),
    queryFn: () =>
      execute<SchemasQueryResult, SchemasQueryVariables>(
        schemasQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Schema list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchSchemasQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: schemasQueryKey(variables),
 *   queryFn: () => fetchSchemasQuery(variables),
 * });
 * ```
 */
export async function fetchSchemasQuery(
  variables?: SchemasQueryVariables,
  options?: ExecuteOptions
): Promise<SchemasQueryResult> {
  return execute<SchemasQueryResult, SchemasQueryVariables>(
    schemasQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Schema list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSchemasQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchSchemasQuery(
  queryClient: QueryClient,
  variables?: SchemasQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: schemasQueryKey(variables),
    queryFn: () =>
      execute<SchemasQueryResult, SchemasQueryVariables>(
        schemasQueryDocument,
        variables,
        options
      ),
  });
}
