/**
 * List query hook for SiteModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type SiteModule,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
} from '../types';

// Re-export entity type for convenience
export type { SiteModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const siteModulesQueryDocument = `
query SiteModulesQuery($first: Int, $offset: Int, $filter: SiteModuleFilter, $orderBy: [SiteModulesOrderBy!]) {
  siteModules(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      siteId
      name
      data
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface SiteModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  siteId?: UUIDFilter;
  name?: StringFilter;
  data?: JSONFilter;
  /** Logical AND */
  and?: SiteModuleFilter[];
  /** Logical OR */
  or?: SiteModuleFilter[];
  /** Logical NOT */
  not?: SiteModuleFilter;
}

type SiteModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SITE_ID_ASC'
  | 'SITE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'DATA_ASC'
  | 'DATA_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface SiteModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: SiteModuleFilter;
  orderBy?: SiteModulesOrderBy[];
}

export interface SiteModulesQueryResult {
  siteModules: {
    totalCount: number;
    nodes: SiteModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const siteModulesQueryKey = (variables?: SiteModulesQueryVariables) =>
  ['sitemodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching SiteModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useSiteModulesQuery(
  variables?: SiteModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<SiteModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: siteModulesQueryKey(variables),
    queryFn: () =>
      execute<SiteModulesQueryResult, SiteModulesQueryVariables>(
        siteModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch SiteModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchSiteModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: siteModulesQueryKey(variables),
 *   queryFn: () => fetchSiteModulesQuery(variables),
 * });
 * ```
 */
export async function fetchSiteModulesQuery(
  variables?: SiteModulesQueryVariables,
  options?: ExecuteOptions
): Promise<SiteModulesQueryResult> {
  return execute<SiteModulesQueryResult, SiteModulesQueryVariables>(
    siteModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch SiteModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchSiteModulesQuery(
  queryClient: QueryClient,
  variables?: SiteModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: siteModulesQueryKey(variables),
    queryFn: () =>
      execute<SiteModulesQueryResult, SiteModulesQueryVariables>(
        siteModulesQueryDocument,
        variables,
        options
      ),
  });
}
