/**
 * Single item query hook for SiteMetadatum
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type SiteMetadatum } from '../types';

// Re-export entity type for convenience
export type { SiteMetadatum };

// ============================================================================
// GraphQL Document
// ============================================================================
export const siteMetadatumQueryDocument = `
query SiteMetadatumQuery($id: UUID!) {
  siteMetadatum(id: $id) {
    id
    databaseId
    siteId
    title
    description
    ogImage
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface SiteMetadatumQueryVariables {
  id: string;
}

export interface SiteMetadatumQueryResult {
  siteMetadatum: SiteMetadatum | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const siteMetadatumQueryKey = (id: string) =>
  ['sitemetadatum', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single SiteMetadatum by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteMetadatumQuery('value-here');
 *
 * if (data?.siteMetadatum) {
 *   console.log(data.siteMetadatum.id);
 * }
 * ```
 */
export function useSiteMetadatumQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<SiteMetadatumQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: siteMetadatumQueryKey(id),
    queryFn: () =>
      execute<SiteMetadatumQueryResult, SiteMetadatumQueryVariables>(
        siteMetadatumQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single SiteMetadatum by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchSiteMetadatumQuery('value-here');
 * ```
 */
export async function fetchSiteMetadatumQuery(
  id: string,
  options?: ExecuteOptions
): Promise<SiteMetadatumQueryResult> {
  return execute<SiteMetadatumQueryResult, SiteMetadatumQueryVariables>(
    siteMetadatumQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single SiteMetadatum for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteMetadatumQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchSiteMetadatumQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: siteMetadatumQueryKey(id),
    queryFn: () =>
      execute<SiteMetadatumQueryResult, SiteMetadatumQueryVariables>(
        siteMetadatumQueryDocument,
        { id },
        options
      ),
  });
}
