/**
 * List query hook for Site
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Site,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
} from '../types';

// Re-export entity type for convenience
export type { Site };

// ============================================================================
// GraphQL Document
// ============================================================================
export const sitesQueryDocument = `
query SitesQuery($first: Int, $offset: Int, $filter: SiteFilter, $orderBy: [SitesOrderBy!]) {
  sites(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      title
      description
      ogImage
      favicon
      appleTouchIcon
      logo
      dbname
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface SiteFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  title?: StringFilter;
  description?: StringFilter;
  ogImage?: JSONFilter;
  favicon?: StringFilter;
  appleTouchIcon?: JSONFilter;
  logo?: JSONFilter;
  dbname?: StringFilter;
  /** Logical AND */
  and?: SiteFilter[];
  /** Logical OR */
  or?: SiteFilter[];
  /** Logical NOT */
  not?: SiteFilter;
}

type SitesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'TITLE_ASC'
  | 'TITLE_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'OG_IMAGE_ASC'
  | 'OG_IMAGE_DESC'
  | 'FAVICON_ASC'
  | 'FAVICON_DESC'
  | 'APPLE_TOUCH_ICON_ASC'
  | 'APPLE_TOUCH_ICON_DESC'
  | 'LOGO_ASC'
  | 'LOGO_DESC'
  | 'DBNAME_ASC'
  | 'DBNAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface SitesQueryVariables {
  first?: number;
  offset?: number;
  filter?: SiteFilter;
  orderBy?: SitesOrderBy[];
}

export interface SitesQueryResult {
  sites: {
    totalCount: number;
    nodes: Site[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const sitesQueryKey = (variables?: SitesQueryVariables) =>
  ['site', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Site list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSitesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useSitesQuery(
  variables?: SitesQueryVariables,
  options?: Omit<
    UseQueryOptions<SitesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: sitesQueryKey(variables),
    queryFn: () =>
      execute<SitesQueryResult, SitesQueryVariables>(
        sitesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Site list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchSitesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: sitesQueryKey(variables),
 *   queryFn: () => fetchSitesQuery(variables),
 * });
 * ```
 */
export async function fetchSitesQuery(
  variables?: SitesQueryVariables,
  options?: ExecuteOptions
): Promise<SitesQueryResult> {
  return execute<SitesQueryResult, SitesQueryVariables>(
    sitesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Site list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSitesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchSitesQuery(
  queryClient: QueryClient,
  variables?: SitesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: sitesQueryKey(variables),
    queryFn: () =>
      execute<SitesQueryResult, SitesQueryVariables>(
        sitesQueryDocument,
        variables,
        options
      ),
  });
}
