/**
 * Single item query hook for SiteTheme
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type SiteTheme } from '../types';

// Re-export entity type for convenience
export type { SiteTheme };

// ============================================================================
// GraphQL Document
// ============================================================================
export const siteThemeQueryDocument = `
query SiteThemeQuery($id: UUID!) {
  siteTheme(id: $id) {
    id
    databaseId
    siteId
    theme
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface SiteThemeQueryVariables {
  id: string;
}

export interface SiteThemeQueryResult {
  siteTheme: SiteTheme | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const siteThemeQueryKey = (id: string) =>
  ['sitetheme', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single SiteTheme by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteThemeQuery('value-here');
 *
 * if (data?.siteTheme) {
 *   console.log(data.siteTheme.id);
 * }
 * ```
 */
export function useSiteThemeQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<SiteThemeQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: siteThemeQueryKey(id),
    queryFn: () =>
      execute<SiteThemeQueryResult, SiteThemeQueryVariables>(
        siteThemeQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single SiteTheme by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchSiteThemeQuery('value-here');
 * ```
 */
export async function fetchSiteThemeQuery(
  id: string,
  options?: ExecuteOptions
): Promise<SiteThemeQueryResult> {
  return execute<SiteThemeQueryResult, SiteThemeQueryVariables>(
    siteThemeQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single SiteTheme for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteThemeQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchSiteThemeQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: siteThemeQueryKey(id),
    queryFn: () =>
      execute<SiteThemeQueryResult, SiteThemeQueryVariables>(
        siteThemeQueryDocument,
        { id },
        options
      ),
  });
}
