/**
 * List query hook for SchemaGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type SchemaGrant,
  type UUIDFilter,
  type StringFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { SchemaGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const schemaGrantsQueryDocument = `
query SchemaGrantsQuery($first: Int, $offset: Int, $filter: SchemaGrantFilter, $orderBy: [SchemaGrantsOrderBy!]) {
  schemaGrants(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      granteeName
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface SchemaGrantFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  granteeName?: StringFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: SchemaGrantFilter[];
  /** Logical OR */
  or?: SchemaGrantFilter[];
  /** Logical NOT */
  not?: SchemaGrantFilter;
}

type SchemaGrantsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'GRANTEE_NAME_ASC'
  | 'GRANTEE_NAME_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface SchemaGrantsQueryVariables {
  first?: number;
  offset?: number;
  filter?: SchemaGrantFilter;
  orderBy?: SchemaGrantsOrderBy[];
}

export interface SchemaGrantsQueryResult {
  schemaGrants: {
    totalCount: number;
    nodes: SchemaGrant[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const schemaGrantsQueryKey = (variables?: SchemaGrantsQueryVariables) =>
  ['schemagrant', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching SchemaGrant list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSchemaGrantsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useSchemaGrantsQuery(
  variables?: SchemaGrantsQueryVariables,
  options?: Omit<
    UseQueryOptions<SchemaGrantsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: schemaGrantsQueryKey(variables),
    queryFn: () =>
      execute<SchemaGrantsQueryResult, SchemaGrantsQueryVariables>(
        schemaGrantsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch SchemaGrant list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchSchemaGrantsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: schemaGrantsQueryKey(variables),
 *   queryFn: () => fetchSchemaGrantsQuery(variables),
 * });
 * ```
 */
export async function fetchSchemaGrantsQuery(
  variables?: SchemaGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<SchemaGrantsQueryResult> {
  return execute<SchemaGrantsQueryResult, SchemaGrantsQueryVariables>(
    schemaGrantsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch SchemaGrant list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSchemaGrantsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchSchemaGrantsQuery(
  queryClient: QueryClient,
  variables?: SchemaGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: schemaGrantsQueryKey(variables),
    queryFn: () =>
      execute<SchemaGrantsQueryResult, SchemaGrantsQueryVariables>(
        schemaGrantsQueryDocument,
        variables,
        options
      ),
  });
}
