/**
 * List query hook for Table
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Table,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type IntFilter,
  type BooleanFilter,
  type StringListFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Table };

// ============================================================================
// GraphQL Document
// ============================================================================
export const tablesQueryDocument = `
query TablesQuery($first: Int, $offset: Int, $filter: TableFilter, $orderBy: [TablesOrderBy!]) {
  tables(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      name
      label
      description
      smartTags
      category
      module
      scope
      useRls
      timestamps
      peoplestamps
      pluralName
      singularName
      tags
      inheritsId
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface TableFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  name?: StringFilter;
  label?: StringFilter;
  description?: StringFilter;
  smartTags?: JSONFilter;
  module?: StringFilter;
  scope?: IntFilter;
  useRls?: BooleanFilter;
  timestamps?: BooleanFilter;
  peoplestamps?: BooleanFilter;
  pluralName?: StringFilter;
  singularName?: StringFilter;
  tags?: StringListFilter;
  inheritsId?: UUIDFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: TableFilter[];
  /** Logical OR */
  or?: TableFilter[];
  /** Logical NOT */
  not?: TableFilter;
}

type TablesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'LABEL_ASC'
  | 'LABEL_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'SMART_TAGS_ASC'
  | 'SMART_TAGS_DESC'
  | 'CATEGORY_ASC'
  | 'CATEGORY_DESC'
  | 'MODULE_ASC'
  | 'MODULE_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'USE_RLS_ASC'
  | 'USE_RLS_DESC'
  | 'TIMESTAMPS_ASC'
  | 'TIMESTAMPS_DESC'
  | 'PEOPLESTAMPS_ASC'
  | 'PEOPLESTAMPS_DESC'
  | 'PLURAL_NAME_ASC'
  | 'PLURAL_NAME_DESC'
  | 'SINGULAR_NAME_ASC'
  | 'SINGULAR_NAME_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'INHERITS_ID_ASC'
  | 'INHERITS_ID_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface TablesQueryVariables {
  first?: number;
  offset?: number;
  filter?: TableFilter;
  orderBy?: TablesOrderBy[];
}

export interface TablesQueryResult {
  tables: {
    totalCount: number;
    nodes: Table[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const tablesQueryKey = (variables?: TablesQueryVariables) =>
  ['table', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Table list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTablesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useTablesQuery(
  variables?: TablesQueryVariables,
  options?: Omit<
    UseQueryOptions<TablesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: tablesQueryKey(variables),
    queryFn: () =>
      execute<TablesQueryResult, TablesQueryVariables>(
        tablesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Table list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchTablesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: tablesQueryKey(variables),
 *   queryFn: () => fetchTablesQuery(variables),
 * });
 * ```
 */
export async function fetchTablesQuery(
  variables?: TablesQueryVariables,
  options?: ExecuteOptions
): Promise<TablesQueryResult> {
  return execute<TablesQueryResult, TablesQueryVariables>(
    tablesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Table list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTablesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchTablesQuery(
  queryClient: QueryClient,
  variables?: TablesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: tablesQueryKey(variables),
    queryFn: () =>
      execute<TablesQueryResult, TablesQueryVariables>(
        tablesQueryDocument,
        variables,
        options
      ),
  });
}
