/**
 * Single item query hook for TokensModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type TokensModule } from '../types';

// Re-export entity type for convenience
export type { TokensModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const tokensModuleQueryDocument = `
query TokensModuleQuery($id: UUID!) {
  tokensModule(id: $id) {
    id
    databaseId
    schemaId
    tableId
    ownedTableId
    tokensDefaultExpiration
    tokensTable
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface TokensModuleQueryVariables {
  id: string;
}

export interface TokensModuleQueryResult {
  tokensModule: TokensModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const tokensModuleQueryKey = (id: string) =>
  ['tokensmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single TokensModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTokensModuleQuery('value-here');
 *
 * if (data?.tokensModule) {
 *   console.log(data.tokensModule.id);
 * }
 * ```
 */
export function useTokensModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<TokensModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: tokensModuleQueryKey(id),
    queryFn: () =>
      execute<TokensModuleQueryResult, TokensModuleQueryVariables>(
        tokensModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single TokensModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchTokensModuleQuery('value-here');
 * ```
 */
export async function fetchTokensModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<TokensModuleQueryResult> {
  return execute<TokensModuleQueryResult, TokensModuleQueryVariables>(
    tokensModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single TokensModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTokensModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchTokensModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: tokensModuleQueryKey(id),
    queryFn: () =>
      execute<TokensModuleQueryResult, TokensModuleQueryVariables>(
        tokensModuleQueryDocument,
        { id },
        options
      ),
  });
}
