/**
 * Single item query hook for TriggerFunction
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type TriggerFunction } from '../types';

// Re-export entity type for convenience
export type { TriggerFunction };

// ============================================================================
// GraphQL Document
// ============================================================================
export const triggerFunctionQueryDocument = `
query TriggerFunctionQuery($id: UUID!) {
  triggerFunction(id: $id) {
    id
    databaseId
    name
    code
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface TriggerFunctionQueryVariables {
  id: string;
}

export interface TriggerFunctionQueryResult {
  triggerFunction: TriggerFunction | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const triggerFunctionQueryKey = (id: string) =>
  ['triggerfunction', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single TriggerFunction by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTriggerFunctionQuery('value-here');
 *
 * if (data?.triggerFunction) {
 *   console.log(data.triggerFunction.id);
 * }
 * ```
 */
export function useTriggerFunctionQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<TriggerFunctionQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: triggerFunctionQueryKey(id),
    queryFn: () =>
      execute<TriggerFunctionQueryResult, TriggerFunctionQueryVariables>(
        triggerFunctionQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single TriggerFunction by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchTriggerFunctionQuery('value-here');
 * ```
 */
export async function fetchTriggerFunctionQuery(
  id: string,
  options?: ExecuteOptions
): Promise<TriggerFunctionQueryResult> {
  return execute<TriggerFunctionQueryResult, TriggerFunctionQueryVariables>(
    triggerFunctionQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single TriggerFunction for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTriggerFunctionQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchTriggerFunctionQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: triggerFunctionQueryKey(id),
    queryFn: () =>
      execute<TriggerFunctionQueryResult, TriggerFunctionQueryVariables>(
        triggerFunctionQueryDocument,
        { id },
        options
      ),
  });
}
