/**
 * Single item query hook for Table
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Table } from '../types';

// Re-export entity type for convenience
export type { Table };

// ============================================================================
// GraphQL Document
// ============================================================================
export const tableQueryDocument = `
query TableQuery($id: UUID!) {
  table(id: $id) {
    id
    databaseId
    schemaId
    name
    label
    description
    smartTags
    category
    module
    scope
    useRls
    timestamps
    peoplestamps
    pluralName
    singularName
    tags
    inheritsId
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface TableQueryVariables {
  id: string;
}

export interface TableQueryResult {
  table: Table | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const tableQueryKey = (id: string) => ['table', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Table by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTableQuery('value-here');
 *
 * if (data?.table) {
 *   console.log(data.table.id);
 * }
 * ```
 */
export function useTableQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<TableQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: tableQueryKey(id),
    queryFn: () =>
      execute<TableQueryResult, TableQueryVariables>(tableQueryDocument, {
        id,
      }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Table by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchTableQuery('value-here');
 * ```
 */
export async function fetchTableQuery(
  id: string,
  options?: ExecuteOptions
): Promise<TableQueryResult> {
  return execute<TableQueryResult, TableQueryVariables>(
    tableQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Table for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTableQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchTableQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: tableQueryKey(id),
    queryFn: () =>
      execute<TableQueryResult, TableQueryVariables>(
        tableQueryDocument,
        { id },
        options
      ),
  });
}
