/**
 * List query hook for TableGrant
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type TableGrant,
  type UUIDFilter,
  type StringFilter,
  type UUIDListFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { TableGrant };

// ============================================================================
// GraphQL Document
// ============================================================================
export const tableGrantsQueryDocument = `
query TableGrantsQuery($first: Int, $offset: Int, $filter: TableGrantFilter, $orderBy: [TableGrantsOrderBy!]) {
  tableGrants(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      tableId
      privilege
      roleName
      fieldIds
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface TableGrantFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  tableId?: UUIDFilter;
  privilege?: StringFilter;
  roleName?: StringFilter;
  fieldIds?: UUIDListFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: TableGrantFilter[];
  /** Logical OR */
  or?: TableGrantFilter[];
  /** Logical NOT */
  not?: TableGrantFilter;
}

type TableGrantsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'PRIVILEGE_ASC'
  | 'PRIVILEGE_DESC'
  | 'ROLE_NAME_ASC'
  | 'ROLE_NAME_DESC'
  | 'FIELD_IDS_ASC'
  | 'FIELD_IDS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface TableGrantsQueryVariables {
  first?: number;
  offset?: number;
  filter?: TableGrantFilter;
  orderBy?: TableGrantsOrderBy[];
}

export interface TableGrantsQueryResult {
  tableGrants: {
    totalCount: number;
    nodes: TableGrant[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const tableGrantsQueryKey = (variables?: TableGrantsQueryVariables) =>
  ['tablegrant', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching TableGrant list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTableGrantsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useTableGrantsQuery(
  variables?: TableGrantsQueryVariables,
  options?: Omit<
    UseQueryOptions<TableGrantsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: tableGrantsQueryKey(variables),
    queryFn: () =>
      execute<TableGrantsQueryResult, TableGrantsQueryVariables>(
        tableGrantsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch TableGrant list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchTableGrantsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: tableGrantsQueryKey(variables),
 *   queryFn: () => fetchTableGrantsQuery(variables),
 * });
 * ```
 */
export async function fetchTableGrantsQuery(
  variables?: TableGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<TableGrantsQueryResult> {
  return execute<TableGrantsQueryResult, TableGrantsQueryVariables>(
    tableGrantsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch TableGrant list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTableGrantsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchTableGrantsQuery(
  queryClient: QueryClient,
  variables?: TableGrantsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: tableGrantsQueryKey(variables),
    queryFn: () =>
      execute<TableGrantsQueryResult, TableGrantsQueryVariables>(
        tableGrantsQueryDocument,
        variables,
        options
      ),
  });
}
