/**
 * Single item query hook for Trigger
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type Trigger } from '../types';

// Re-export entity type for convenience
export type { Trigger };

// ============================================================================
// GraphQL Document
// ============================================================================
export const triggerQueryDocument = `
query TriggerQuery($id: UUID!) {
  trigger(id: $id) {
    id
    databaseId
    tableId
    name
    event
    functionName
    smartTags
    category
    module
    scope
    tags
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface TriggerQueryVariables {
  id: string;
}

export interface TriggerQueryResult {
  trigger: Trigger | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const triggerQueryKey = (id: string) =>
  ['trigger', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single Trigger by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTriggerQuery('value-here');
 *
 * if (data?.trigger) {
 *   console.log(data.trigger.id);
 * }
 * ```
 */
export function useTriggerQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<TriggerQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: triggerQueryKey(id),
    queryFn: () =>
      execute<TriggerQueryResult, TriggerQueryVariables>(triggerQueryDocument, {
        id,
      }),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single Trigger by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchTriggerQuery('value-here');
 * ```
 */
export async function fetchTriggerQuery(
  id: string,
  options?: ExecuteOptions
): Promise<TriggerQueryResult> {
  return execute<TriggerQueryResult, TriggerQueryVariables>(
    triggerQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single Trigger for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTriggerQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchTriggerQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: triggerQueryKey(id),
    queryFn: () =>
      execute<TriggerQueryResult, TriggerQueryVariables>(
        triggerQueryDocument,
        { id },
        options
      ),
  });
}
