/**
 * List query hook for TokensModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type TokensModule,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { TokensModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const tokensModulesQueryDocument = `
query TokensModulesQuery($first: Int, $offset: Int, $filter: TokensModuleFilter, $orderBy: [TokensModulesOrderBy!]) {
  tokensModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      tableId
      ownedTableId
      tokensDefaultExpiration
      tokensTable
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface TokensModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  ownedTableId?: UUIDFilter;
  tokensDefaultExpiration?: StringFilter;
  tokensTable?: StringFilter;
  /** Logical AND */
  and?: TokensModuleFilter[];
  /** Logical OR */
  or?: TokensModuleFilter[];
  /** Logical NOT */
  not?: TokensModuleFilter;
}

type TokensModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'OWNED_TABLE_ID_ASC'
  | 'OWNED_TABLE_ID_DESC'
  | 'TOKENS_DEFAULT_EXPIRATION_ASC'
  | 'TOKENS_DEFAULT_EXPIRATION_DESC'
  | 'TOKENS_TABLE_ASC'
  | 'TOKENS_TABLE_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface TokensModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: TokensModuleFilter;
  orderBy?: TokensModulesOrderBy[];
}

export interface TokensModulesQueryResult {
  tokensModules: {
    totalCount: number;
    nodes: TokensModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const tokensModulesQueryKey = (
  variables?: TokensModulesQueryVariables
) => ['tokensmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching TokensModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTokensModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useTokensModulesQuery(
  variables?: TokensModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<TokensModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: tokensModulesQueryKey(variables),
    queryFn: () =>
      execute<TokensModulesQueryResult, TokensModulesQueryVariables>(
        tokensModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch TokensModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchTokensModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: tokensModulesQueryKey(variables),
 *   queryFn: () => fetchTokensModulesQuery(variables),
 * });
 * ```
 */
export async function fetchTokensModulesQuery(
  variables?: TokensModulesQueryVariables,
  options?: ExecuteOptions
): Promise<TokensModulesQueryResult> {
  return execute<TokensModulesQueryResult, TokensModulesQueryVariables>(
    tokensModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch TokensModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTokensModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchTokensModulesQuery(
  queryClient: QueryClient,
  variables?: TokensModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: tokensModulesQueryKey(variables),
    queryFn: () =>
      execute<TokensModulesQueryResult, TokensModulesQueryVariables>(
        tokensModulesQueryDocument,
        variables,
        options
      ),
  });
}
