/**
 * List query hook for Trigger
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type Trigger,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type IntFilter,
  type StringListFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { Trigger };

// ============================================================================
// GraphQL Document
// ============================================================================
export const triggersQueryDocument = `
query TriggersQuery($first: Int, $offset: Int, $filter: TriggerFilter, $orderBy: [TriggersOrderBy!]) {
  triggers(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      tableId
      name
      event
      functionName
      smartTags
      category
      module
      scope
      tags
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface TriggerFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  tableId?: UUIDFilter;
  name?: StringFilter;
  event?: StringFilter;
  functionName?: StringFilter;
  smartTags?: JSONFilter;
  module?: StringFilter;
  scope?: IntFilter;
  tags?: StringListFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: TriggerFilter[];
  /** Logical OR */
  or?: TriggerFilter[];
  /** Logical NOT */
  not?: TriggerFilter;
}

type TriggersOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'EVENT_ASC'
  | 'EVENT_DESC'
  | 'FUNCTION_NAME_ASC'
  | 'FUNCTION_NAME_DESC'
  | 'SMART_TAGS_ASC'
  | 'SMART_TAGS_DESC'
  | 'CATEGORY_ASC'
  | 'CATEGORY_DESC'
  | 'MODULE_ASC'
  | 'MODULE_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface TriggersQueryVariables {
  first?: number;
  offset?: number;
  filter?: TriggerFilter;
  orderBy?: TriggersOrderBy[];
}

export interface TriggersQueryResult {
  triggers: {
    totalCount: number;
    nodes: Trigger[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const triggersQueryKey = (variables?: TriggersQueryVariables) =>
  ['trigger', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching Trigger list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTriggersQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useTriggersQuery(
  variables?: TriggersQueryVariables,
  options?: Omit<
    UseQueryOptions<TriggersQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: triggersQueryKey(variables),
    queryFn: () =>
      execute<TriggersQueryResult, TriggersQueryVariables>(
        triggersQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch Trigger list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchTriggersQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: triggersQueryKey(variables),
 *   queryFn: () => fetchTriggersQuery(variables),
 * });
 * ```
 */
export async function fetchTriggersQuery(
  variables?: TriggersQueryVariables,
  options?: ExecuteOptions
): Promise<TriggersQueryResult> {
  return execute<TriggersQueryResult, TriggersQueryVariables>(
    triggersQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch Trigger list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTriggersQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchTriggersQuery(
  queryClient: QueryClient,
  variables?: TriggersQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: triggersQueryKey(variables),
    queryFn: () =>
      execute<TriggersQueryResult, TriggersQueryVariables>(
        triggersQueryDocument,
        variables,
        options
      ),
  });
}
