/**
 * List query hook for TriggerFunction
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type TriggerFunction,
  type UUIDFilter,
  type StringFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { TriggerFunction };

// ============================================================================
// GraphQL Document
// ============================================================================
export const triggerFunctionsQueryDocument = `
query TriggerFunctionsQuery($first: Int, $offset: Int, $filter: TriggerFunctionFilter, $orderBy: [TriggerFunctionsOrderBy!]) {
  triggerFunctions(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      name
      code
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface TriggerFunctionFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  name?: StringFilter;
  code?: StringFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: TriggerFunctionFilter[];
  /** Logical OR */
  or?: TriggerFunctionFilter[];
  /** Logical NOT */
  not?: TriggerFunctionFilter;
}

type TriggerFunctionsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'CODE_ASC'
  | 'CODE_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface TriggerFunctionsQueryVariables {
  first?: number;
  offset?: number;
  filter?: TriggerFunctionFilter;
  orderBy?: TriggerFunctionsOrderBy[];
}

export interface TriggerFunctionsQueryResult {
  triggerFunctions: {
    totalCount: number;
    nodes: TriggerFunction[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const triggerFunctionsQueryKey = (
  variables?: TriggerFunctionsQueryVariables
) => ['triggerfunction', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching TriggerFunction list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTriggerFunctionsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useTriggerFunctionsQuery(
  variables?: TriggerFunctionsQueryVariables,
  options?: Omit<
    UseQueryOptions<TriggerFunctionsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: triggerFunctionsQueryKey(variables),
    queryFn: () =>
      execute<TriggerFunctionsQueryResult, TriggerFunctionsQueryVariables>(
        triggerFunctionsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch TriggerFunction list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchTriggerFunctionsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: triggerFunctionsQueryKey(variables),
 *   queryFn: () => fetchTriggerFunctionsQuery(variables),
 * });
 * ```
 */
export async function fetchTriggerFunctionsQuery(
  variables?: TriggerFunctionsQueryVariables,
  options?: ExecuteOptions
): Promise<TriggerFunctionsQueryResult> {
  return execute<TriggerFunctionsQueryResult, TriggerFunctionsQueryVariables>(
    triggerFunctionsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch TriggerFunction list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTriggerFunctionsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchTriggerFunctionsQuery(
  queryClient: QueryClient,
  variables?: TriggerFunctionsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: triggerFunctionsQueryKey(variables),
    queryFn: () =>
      execute<TriggerFunctionsQueryResult, TriggerFunctionsQueryVariables>(
        triggerFunctionsQueryDocument,
        variables,
        options
      ),
  });
}
