/**
 * List query hook for User
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type User,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type FullTextFilter,
  type IntFilter,
  type DatetimeFilter,
  type FloatFilter,
} from '../types';

// Re-export entity type for convenience
export type { User };

// ============================================================================
// GraphQL Document
// ============================================================================
export const usersQueryDocument = `
query UsersQuery($first: Int, $offset: Int, $filter: UserFilter, $orderBy: [UsersOrderBy!]) {
  users(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      username
      displayName
      profilePicture
      searchTsv
      type
      createdAt
      updatedAt
      searchTsvRank
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface UserFilter {
  id?: UUIDFilter;
  username?: StringFilter;
  displayName?: StringFilter;
  profilePicture?: JSONFilter;
  searchTsv?: FullTextFilter;
  type?: IntFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  searchTsvRank?: FloatFilter;
  /** Logical AND */
  and?: UserFilter[];
  /** Logical OR */
  or?: UserFilter[];
  /** Logical NOT */
  not?: UserFilter;
}

type UsersOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'USERNAME_ASC'
  | 'USERNAME_DESC'
  | 'DISPLAY_NAME_ASC'
  | 'DISPLAY_NAME_DESC'
  | 'PROFILE_PICTURE_ASC'
  | 'PROFILE_PICTURE_DESC'
  | 'SEARCH_TSV_ASC'
  | 'SEARCH_TSV_DESC'
  | 'TYPE_ASC'
  | 'TYPE_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'SEARCH_TSV_RANK_ASC'
  | 'SEARCH_TSV_RANK_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface UsersQueryVariables {
  first?: number;
  offset?: number;
  filter?: UserFilter;
  orderBy?: UsersOrderBy[];
}

export interface UsersQueryResult {
  users: {
    totalCount: number;
    nodes: User[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const usersQueryKey = (variables?: UsersQueryVariables) =>
  ['user', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching User list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUsersQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useUsersQuery(
  variables?: UsersQueryVariables,
  options?: Omit<
    UseQueryOptions<UsersQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: usersQueryKey(variables),
    queryFn: () =>
      execute<UsersQueryResult, UsersQueryVariables>(
        usersQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch User list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchUsersQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: usersQueryKey(variables),
 *   queryFn: () => fetchUsersQuery(variables),
 * });
 * ```
 */
export async function fetchUsersQuery(
  variables?: UsersQueryVariables,
  options?: ExecuteOptions
): Promise<UsersQueryResult> {
  return execute<UsersQueryResult, UsersQueryVariables>(
    usersQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch User list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUsersQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchUsersQuery(
  queryClient: QueryClient,
  variables?: UsersQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: usersQueryKey(variables),
    queryFn: () =>
      execute<UsersQueryResult, UsersQueryVariables>(
        usersQueryDocument,
        variables,
        options
      ),
  });
}
