/**
 * Single item query hook for UserAuthModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type UserAuthModule } from '../types';

// Re-export entity type for convenience
export type { UserAuthModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const userAuthModuleQueryDocument = `
query UserAuthModuleQuery($id: UUID!) {
  userAuthModule(id: $id) {
    id
    databaseId
    schemaId
    emailsTableId
    usersTableId
    secretsTableId
    encryptedTableId
    tokensTableId
    auditsTableId
    auditsTableName
    signInFunction
    signUpFunction
    signOutFunction
    setPasswordFunction
    resetPasswordFunction
    forgotPasswordFunction
    sendVerificationEmailFunction
    verifyEmailFunction
    verifyPasswordFunction
    checkPasswordFunction
    sendAccountDeletionEmailFunction
    deleteAccountFunction
    signInOneTimeTokenFunction
    oneTimeTokenFunction
    extendTokenExpires
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface UserAuthModuleQueryVariables {
  id: string;
}

export interface UserAuthModuleQueryResult {
  userAuthModule: UserAuthModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const userAuthModuleQueryKey = (id: string) =>
  ['userauthmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single UserAuthModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUserAuthModuleQuery('value-here');
 *
 * if (data?.userAuthModule) {
 *   console.log(data.userAuthModule.id);
 * }
 * ```
 */
export function useUserAuthModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<UserAuthModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: userAuthModuleQueryKey(id),
    queryFn: () =>
      execute<UserAuthModuleQueryResult, UserAuthModuleQueryVariables>(
        userAuthModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single UserAuthModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchUserAuthModuleQuery('value-here');
 * ```
 */
export async function fetchUserAuthModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<UserAuthModuleQueryResult> {
  return execute<UserAuthModuleQueryResult, UserAuthModuleQueryVariables>(
    userAuthModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single UserAuthModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUserAuthModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchUserAuthModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: userAuthModuleQueryKey(id),
    queryFn: () =>
      execute<UserAuthModuleQueryResult, UserAuthModuleQueryVariables>(
        userAuthModuleQueryDocument,
        { id },
        options
      ),
  });
}
