/**
 * List query hook for UsersModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type UsersModule, type UUIDFilter, type StringFilter } from '../types';

// Re-export entity type for convenience
export type { UsersModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const usersModulesQueryDocument = `
query UsersModulesQuery($first: Int, $offset: Int, $filter: UsersModuleFilter, $orderBy: [UsersModulesOrderBy!]) {
  usersModules(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      tableId
      tableName
      typeTableId
      typeTableName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface UsersModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  tableName?: StringFilter;
  typeTableId?: UUIDFilter;
  typeTableName?: StringFilter;
  /** Logical AND */
  and?: UsersModuleFilter[];
  /** Logical OR */
  or?: UsersModuleFilter[];
  /** Logical NOT */
  not?: UsersModuleFilter;
}

type UsersModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'TABLE_NAME_ASC'
  | 'TABLE_NAME_DESC'
  | 'TYPE_TABLE_ID_ASC'
  | 'TYPE_TABLE_ID_DESC'
  | 'TYPE_TABLE_NAME_ASC'
  | 'TYPE_TABLE_NAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface UsersModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: UsersModuleFilter;
  orderBy?: UsersModulesOrderBy[];
}

export interface UsersModulesQueryResult {
  usersModules: {
    totalCount: number;
    nodes: UsersModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const usersModulesQueryKey = (variables?: UsersModulesQueryVariables) =>
  ['usersmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching UsersModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUsersModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useUsersModulesQuery(
  variables?: UsersModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<UsersModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: usersModulesQueryKey(variables),
    queryFn: () =>
      execute<UsersModulesQueryResult, UsersModulesQueryVariables>(
        usersModulesQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch UsersModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchUsersModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: usersModulesQueryKey(variables),
 *   queryFn: () => fetchUsersModulesQuery(variables),
 * });
 * ```
 */
export async function fetchUsersModulesQuery(
  variables?: UsersModulesQueryVariables,
  options?: ExecuteOptions
): Promise<UsersModulesQueryResult> {
  return execute<UsersModulesQueryResult, UsersModulesQueryVariables>(
    usersModulesQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch UsersModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUsersModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchUsersModulesQuery(
  queryClient: QueryClient,
  variables?: UsersModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: usersModulesQueryKey(variables),
    queryFn: () =>
      execute<UsersModulesQueryResult, UsersModulesQueryVariables>(
        usersModulesQueryDocument,
        variables,
        options
      ),
  });
}
