/**
 * Single item query hook for UuidModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type UuidModule } from '../types';

// Re-export entity type for convenience
export type { UuidModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const uuidModuleQueryDocument = `
query UuidModuleQuery($id: UUID!) {
  uuidModule(id: $id) {
    id
    databaseId
    schemaId
    uuidFunction
    uuidSeed
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface UuidModuleQueryVariables {
  id: string;
}

export interface UuidModuleQueryResult {
  uuidModule: UuidModule | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const uuidModuleQueryKey = (id: string) =>
  ['uuidmodule', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single UuidModule by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUuidModuleQuery('value-here');
 *
 * if (data?.uuidModule) {
 *   console.log(data.uuidModule.id);
 * }
 * ```
 */
export function useUuidModuleQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<UuidModuleQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: uuidModuleQueryKey(id),
    queryFn: () =>
      execute<UuidModuleQueryResult, UuidModuleQueryVariables>(
        uuidModuleQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single UuidModule by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchUuidModuleQuery('value-here');
 * ```
 */
export async function fetchUuidModuleQuery(
  id: string,
  options?: ExecuteOptions
): Promise<UuidModuleQueryResult> {
  return execute<UuidModuleQueryResult, UuidModuleQueryVariables>(
    uuidModuleQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single UuidModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUuidModuleQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchUuidModuleQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: uuidModuleQueryKey(id),
    queryFn: () =>
      execute<UuidModuleQueryResult, UuidModuleQueryVariables>(
        uuidModuleQueryDocument,
        { id },
        options
      ),
  });
}
