/**
 * List query hook for UniqueConstraint
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type UniqueConstraint,
  type UUIDFilter,
  type StringFilter,
  type JSONFilter,
  type UUIDListFilter,
  type IntFilter,
  type StringListFilter,
  type DatetimeFilter,
} from '../types';

// Re-export entity type for convenience
export type { UniqueConstraint };

// ============================================================================
// GraphQL Document
// ============================================================================
export const uniqueConstraintsQueryDocument = `
query UniqueConstraintsQuery($first: Int, $offset: Int, $filter: UniqueConstraintFilter, $orderBy: [UniqueConstraintsOrderBy!]) {
  uniqueConstraints(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      tableId
      name
      description
      smartTags
      type
      fieldIds
      category
      module
      scope
      tags
      createdAt
      updatedAt
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface UniqueConstraintFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  tableId?: UUIDFilter;
  name?: StringFilter;
  description?: StringFilter;
  smartTags?: JSONFilter;
  type?: StringFilter;
  fieldIds?: UUIDListFilter;
  module?: StringFilter;
  scope?: IntFilter;
  tags?: StringListFilter;
  createdAt?: DatetimeFilter;
  updatedAt?: DatetimeFilter;
  /** Logical AND */
  and?: UniqueConstraintFilter[];
  /** Logical OR */
  or?: UniqueConstraintFilter[];
  /** Logical NOT */
  not?: UniqueConstraintFilter;
}

type UniqueConstraintsOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'SMART_TAGS_ASC'
  | 'SMART_TAGS_DESC'
  | 'TYPE_ASC'
  | 'TYPE_DESC'
  | 'FIELD_IDS_ASC'
  | 'FIELD_IDS_DESC'
  | 'CATEGORY_ASC'
  | 'CATEGORY_DESC'
  | 'MODULE_ASC'
  | 'MODULE_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface UniqueConstraintsQueryVariables {
  first?: number;
  offset?: number;
  filter?: UniqueConstraintFilter;
  orderBy?: UniqueConstraintsOrderBy[];
}

export interface UniqueConstraintsQueryResult {
  uniqueConstraints: {
    totalCount: number;
    nodes: UniqueConstraint[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const uniqueConstraintsQueryKey = (
  variables?: UniqueConstraintsQueryVariables
) => ['uniqueconstraint', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching UniqueConstraint list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUniqueConstraintsQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useUniqueConstraintsQuery(
  variables?: UniqueConstraintsQueryVariables,
  options?: Omit<
    UseQueryOptions<UniqueConstraintsQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: uniqueConstraintsQueryKey(variables),
    queryFn: () =>
      execute<UniqueConstraintsQueryResult, UniqueConstraintsQueryVariables>(
        uniqueConstraintsQueryDocument,
        variables
      ),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch UniqueConstraint list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchUniqueConstraintsQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: uniqueConstraintsQueryKey(variables),
 *   queryFn: () => fetchUniqueConstraintsQuery(variables),
 * });
 * ```
 */
export async function fetchUniqueConstraintsQuery(
  variables?: UniqueConstraintsQueryVariables,
  options?: ExecuteOptions
): Promise<UniqueConstraintsQueryResult> {
  return execute<UniqueConstraintsQueryResult, UniqueConstraintsQueryVariables>(
    uniqueConstraintsQueryDocument,
    variables,
    options
  );
}

/**
 * Prefetch UniqueConstraint list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUniqueConstraintsQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchUniqueConstraintsQuery(
  queryClient: QueryClient,
  variables?: UniqueConstraintsQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: uniqueConstraintsQueryKey(variables),
    queryFn: () =>
      execute<UniqueConstraintsQueryResult, UniqueConstraintsQueryVariables>(
        uniqueConstraintsQueryDocument,
        variables,
        options
      ),
  });
}
