/**
 * Single item query hook for UniqueConstraint
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type UniqueConstraint } from '../types';

// Re-export entity type for convenience
export type { UniqueConstraint };

// ============================================================================
// GraphQL Document
// ============================================================================
export const uniqueConstraintQueryDocument = `
query UniqueConstraintQuery($id: UUID!) {
  uniqueConstraint(id: $id) {
    id
    databaseId
    tableId
    name
    description
    smartTags
    type
    fieldIds
    category
    module
    scope
    tags
    createdAt
    updatedAt
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface UniqueConstraintQueryVariables {
  id: string;
}

export interface UniqueConstraintQueryResult {
  uniqueConstraint: UniqueConstraint | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const uniqueConstraintQueryKey = (id: string) =>
  ['uniqueconstraint', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single UniqueConstraint by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUniqueConstraintQuery('value-here');
 *
 * if (data?.uniqueConstraint) {
 *   console.log(data.uniqueConstraint.id);
 * }
 * ```
 */
export function useUniqueConstraintQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<UniqueConstraintQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: uniqueConstraintQueryKey(id),
    queryFn: () =>
      execute<UniqueConstraintQueryResult, UniqueConstraintQueryVariables>(
        uniqueConstraintQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single UniqueConstraint by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchUniqueConstraintQuery('value-here');
 * ```
 */
export async function fetchUniqueConstraintQuery(
  id: string,
  options?: ExecuteOptions
): Promise<UniqueConstraintQueryResult> {
  return execute<UniqueConstraintQueryResult, UniqueConstraintQueryVariables>(
    uniqueConstraintQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single UniqueConstraint for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUniqueConstraintQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchUniqueConstraintQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: uniqueConstraintQueryKey(id),
    queryFn: () =>
      execute<UniqueConstraintQueryResult, UniqueConstraintQueryVariables>(
        uniqueConstraintQueryDocument,
        { id },
        options
      ),
  });
}
