/**
 * Single item query hook for UserSetting
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import { type UserSetting } from '../types';

// Re-export entity type for convenience
export type { UserSetting };

// ============================================================================
// GraphQL Document
// ============================================================================
export const userSettingQueryDocument = `
query UserSettingQuery($id: UUID!) {
  userSetting(id: $id) {
    id
    ownerId
    searchRadius
    zip
    location
    createdAt
    updatedAt
    createdBy
    updatedBy
  }
}
`;

// ============================================================================
// Types
// ============================================================================
export interface UserSettingQueryVariables {
  id: string;
}

export interface UserSettingQueryResult {
  userSetting: UserSetting | null;
}

// ============================================================================
// Query Key
// ============================================================================
export const userSettingQueryKey = (id: string) =>
  ['usersetting', 'detail', id] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching a single UserSetting by primary key
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUserSettingQuery('value-here');
 *
 * if (data?.userSetting) {
 *   console.log(data.userSetting.id);
 * }
 * ```
 */
export function useUserSettingQuery(
  id: string,
  options?: Omit<
    UseQueryOptions<UserSettingQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: userSettingQueryKey(id),
    queryFn: () =>
      execute<UserSettingQueryResult, UserSettingQueryVariables>(
        userSettingQueryDocument,
        { id }
      ),
    enabled: !!id && options?.enabled !== false,
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch a single UserSetting by primary key without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchUserSettingQuery('value-here');
 * ```
 */
export async function fetchUserSettingQuery(
  id: string,
  options?: ExecuteOptions
): Promise<UserSettingQueryResult> {
  return execute<UserSettingQueryResult, UserSettingQueryVariables>(
    userSettingQueryDocument,
    { id },
    options
  );
}

/**
 * Prefetch a single UserSetting for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUserSettingQuery(queryClient, 'value-here');
 * ```
 */
export async function prefetchUserSettingQuery(
  queryClient: QueryClient,
  id: string,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: userSettingQueryKey(id),
    queryFn: () =>
      execute<UserSettingQueryResult, UserSettingQueryVariables>(
        userSettingQueryDocument,
        { id },
        options
      ),
  });
}
