/**
 * List query hook for UserProfilesModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import {
  useQuery,
  type UseQueryOptions,
  type QueryClient,
} from '@tanstack/react-query';
import { execute, type ExecuteOptions } from '../client';
import {
  type UserProfilesModule,
  type UUIDFilter,
  type StringFilter,
} from '../types';

// Re-export entity type for convenience
export type { UserProfilesModule };

// ============================================================================
// GraphQL Document
// ============================================================================
export const userProfilesModulesQueryDocument = `
query UserProfilesModulesQuery($first: Int, $offset: Int, $filter: UserProfilesModuleFilter, $orderBy: [UserProfilesModulesOrderBy!]) {
  userProfilesModules(
    first: $first
    offset: $offset
    filter: $filter
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      databaseId
      schemaId
      privateSchemaId
      tableId
      ownerTableId
      tableName
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
`;

// ============================================================================
// Types
// ============================================================================
interface UserProfilesModuleFilter {
  id?: UUIDFilter;
  databaseId?: UUIDFilter;
  schemaId?: UUIDFilter;
  privateSchemaId?: UUIDFilter;
  tableId?: UUIDFilter;
  ownerTableId?: UUIDFilter;
  tableName?: StringFilter;
  /** Logical AND */
  and?: UserProfilesModuleFilter[];
  /** Logical OR */
  or?: UserProfilesModuleFilter[];
  /** Logical NOT */
  not?: UserProfilesModuleFilter;
}

type UserProfilesModulesOrderBy =
  | 'ID_ASC'
  | 'ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'SCHEMA_ID_ASC'
  | 'SCHEMA_ID_DESC'
  | 'PRIVATE_SCHEMA_ID_ASC'
  | 'PRIVATE_SCHEMA_ID_DESC'
  | 'TABLE_ID_ASC'
  | 'TABLE_ID_DESC'
  | 'OWNER_TABLE_ID_ASC'
  | 'OWNER_TABLE_ID_DESC'
  | 'TABLE_NAME_ASC'
  | 'TABLE_NAME_DESC'
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC';

export interface UserProfilesModulesQueryVariables {
  first?: number;
  offset?: number;
  filter?: UserProfilesModuleFilter;
  orderBy?: UserProfilesModulesOrderBy[];
}

export interface UserProfilesModulesQueryResult {
  userProfilesModules: {
    totalCount: number;
    nodes: UserProfilesModule[];
    pageInfo: {
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor: string | null;
      endCursor: string | null;
    };
  };
}

// ============================================================================
// Query Key
// ============================================================================
export const userProfilesModulesQueryKey = (
  variables?: UserProfilesModulesQueryVariables
) => ['userprofilesmodule', 'list', variables] as const;

// ============================================================================
// Hook
// ============================================================================
/**
 * Query hook for fetching UserProfilesModule list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUserProfilesModulesQuery({
 *   first: 10,
 *   filter: { name: { equalTo: "example" } },
 *   orderBy: ['CREATED_AT_DESC'],
 * });
 * ```
 */
export function useUserProfilesModulesQuery(
  variables?: UserProfilesModulesQueryVariables,
  options?: Omit<
    UseQueryOptions<UserProfilesModulesQueryResult, Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: userProfilesModulesQueryKey(variables),
    queryFn: () =>
      execute<
        UserProfilesModulesQueryResult,
        UserProfilesModulesQueryVariables
      >(userProfilesModulesQueryDocument, variables),
    ...options,
  });
}

// ============================================================================
// Standalone Functions (non-React)
// ============================================================================
/**
 * Fetch UserProfilesModule list without React hooks
 *
 * @example
 * ```ts
 * // Direct fetch
 * const data = await fetchUserProfilesModulesQuery({ first: 10 });
 *
 * // With QueryClient
 * const data = await queryClient.fetchQuery({
 *   queryKey: userProfilesModulesQueryKey(variables),
 *   queryFn: () => fetchUserProfilesModulesQuery(variables),
 * });
 * ```
 */
export async function fetchUserProfilesModulesQuery(
  variables?: UserProfilesModulesQueryVariables,
  options?: ExecuteOptions
): Promise<UserProfilesModulesQueryResult> {
  return execute<
    UserProfilesModulesQueryResult,
    UserProfilesModulesQueryVariables
  >(userProfilesModulesQueryDocument, variables, options);
}

/**
 * Prefetch UserProfilesModule list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUserProfilesModulesQuery(queryClient, { first: 10 });
 * ```
 */
export async function prefetchUserProfilesModulesQuery(
  queryClient: QueryClient,
  variables?: UserProfilesModulesQueryVariables,
  options?: ExecuteOptions
): Promise<void> {
  await queryClient.prefetchQuery({
    queryKey: userProfilesModulesQueryKey(variables),
    queryFn: () =>
      execute<
        UserProfilesModulesQueryResult,
        UserProfilesModulesQueryVariables
      >(userProfilesModulesQueryDocument, variables, options),
  });
}
